/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ADInterstitialAdDelegate <NSObject>
-(void)interstitialAd:(id)ad didFailWithError:(id)error;
-(void)interstitialAdDidUnload:(id)interstitialAd;
@optional
-(void)interstitialAdActionDidFinish:(id)interstitialAdAction;
-(BOOL)interstitialAdActionShouldBegin:(id)interstitialAdAction willLeaveApplication:(BOOL)application;
-(void)interstitialAdDidLoad:(id)interstitialAd;
-(void)interstitialAdWillLoad:(id)interstitialAd;
@end

