/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "NSCoding.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ADJActivityState : XXUnknownSuperclass <NSCoding, NSCopying> {
	BOOL _enabled;
	BOOL _askingAttribution;
	NSString* _uuid;
	int _eventCount;
	int _sessionCount;
	int _subsessionCount;
	NSMutableArray* _transactionIds;
	double _sessionLength;
	double _timeSpent;
	double _lastActivity;
	double _createdAt;
	double _lastInterval;
}
@property(assign, nonatomic) double lastInterval;
@property(retain, nonatomic) NSMutableArray* transactionIds;
@property(assign, nonatomic) double createdAt;
@property(assign, nonatomic) double lastActivity;
@property(assign, nonatomic) double timeSpent;
@property(assign, nonatomic) double sessionLength;
@property(assign, nonatomic) int subsessionCount;
@property(assign, nonatomic) int sessionCount;
@property(assign, nonatomic) int eventCount;
@property(assign, nonatomic) BOOL askingAttribution;
@property(assign, nonatomic) BOOL enabled;
@property(copy, nonatomic) NSString* uuid;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)description;
-(BOOL)findTransactionId:(id)anId;
-(void)addTransactionId:(id)anId;
-(void)resetSessionAttributes:(double)attributes;
-(id)init;
@end

