/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "NSCoding.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface ADJAttribution : XXUnknownSuperclass <NSCoding, NSCopying> {
	NSString* _trackerToken;
	NSString* _trackerName;
	NSString* _network;
	NSString* _campaign;
	NSString* _adgroup;
	NSString* _creative;
}
@property(copy, nonatomic) NSString* creative;
@property(copy, nonatomic) NSString* adgroup;
@property(copy, nonatomic) NSString* campaign;
@property(copy, nonatomic) NSString* network;
@property(copy, nonatomic) NSString* trackerName;
@property(copy, nonatomic) NSString* trackerToken;
+(id)dataWithJsonDict:(id)jsonDict;
-(void).cxx_destruct;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)copyWithZone:(NSZone*)zone;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)description;
-(id)dictionary;
-(BOOL)isEqualToAttribution:(id)attribution;
-(id)initWithJsonDict:(id)jsonDict;
@end

