/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ADJAttributionHandler.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class ADJActivityPackage, ADJTimer, NSObject;
@protocol OS_dispatch_queue, ADJLogger, ADJActivityHandler;

@protocol ADJAttributionHandler
-(void)getAttribution;
-(void)checkAttribution:(id)attribution;
-(id)initWithActivityHandler:(id)activityHandler withMaxDelay:(id)maxDelay withAttributionPackage:(id)attributionPackage;
@end

__attribute__((visibility("hidden")))
@interface ADJAttributionHandler : XXUnknownSuperclass <ADJAttributionHandler> {
	NSObject<OS_dispatch_queue>* _internalQueue;
	id<ADJActivityHandler> _activityHandler;
	id<ADJLogger> _logger;
	ADJTimer* _askInTimer;
	ADJTimer* _maxDelayTimer;
	ADJActivityPackage* _attributionPackage;
}
@property(retain, nonatomic) ADJActivityPackage* attributionPackage;
@property(retain, nonatomic) ADJTimer* maxDelayTimer;
@property(retain, nonatomic) ADJTimer* askInTimer;
@property(assign, nonatomic) id<ADJLogger> logger;
@property(assign, nonatomic) id<ADJActivityHandler> activityHandler;
@property(retain, nonatomic) NSObject<OS_dispatch_queue>* internalQueue;
+(id)handlerWithActivityHandler:(id)activityHandler withMaxDelay:(id)maxDelay withAttributionPackage:(id)attributionPackage;
-(void).cxx_destruct;
-(id)url;
-(id)request;
-(void)getAttributionInternal;
-(void)checkAttributionInternal:(id)internal;
-(void)getAttribution;
-(void)checkAttribution:(id)attribution;
-(id)initWithActivityHandler:(id)activityHandler withMaxDelay:(id)maxDelay withAttributionPackage:(id)attributionPackage;
@end

