/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSObject.h"
#import "ADJActivityHandler.h"

@class ADJActivityState, NSObject, ADJAttribution, ADJDeviceInfo, NSString, ADJConfig, ADJTimer;
@protocol AdjustDelegate, ADJPackageHandler, OS_dispatch_queue, ADJLogger, ADJAttributionHandler;

@protocol ADJActivityHandler <NSObject>
-(void)setOfflineMode:(BOOL)mode;
-(void)launchAttributionDelegate;
-(void)setIadDate:(id)date withPurchaseDate:(id)purchaseDate;
-(BOOL)updateAttribution:(id)attribution;
-(void)setAskingAttribution:(BOOL)attribution;
-(void)setAttribution:(id)attribution;
-(id)attribution;
-(void)setDeviceToken:(id)token;
-(void)appWillOpenUrl:(id)app;
-(BOOL)isEnabled;
-(void)setEnabled:(BOOL)enabled;
-(void)finishedTrackingWithResponse:(id)response;
-(void)trackEvent:(id)event;
-(void)trackSubsessionEnd;
-(void)trackSubsessionStart;
-(id)initWithConfig:(id)config;
@end

__attribute__((visibility("hidden")))
@interface ADJActivityHandler : XXUnknownSuperclass <ADJActivityHandler> {
	BOOL _enabled;
	BOOL _offline;
	BOOL _shouldGetAttribution;
	NSObject<OS_dispatch_queue>* _internalQueue;
	id<ADJPackageHandler> _packageHandler;
	id<ADJAttributionHandler> _attributionHandler;
	ADJActivityState* _activityState;
	ADJTimer* _timer;
	id<ADJLogger> _logger;
	NSObject<AdjustDelegate>* _delegate;
	ADJAttribution* _attribution;
	ADJConfig* _adjustConfig;
	ADJDeviceInfo* _deviceInfo;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) ADJDeviceInfo* deviceInfo;
@property(assign, nonatomic) BOOL shouldGetAttribution;
@property(assign, nonatomic) BOOL offline;
@property(assign, nonatomic) BOOL enabled;
@property(copy, nonatomic) ADJConfig* adjustConfig;
@property(copy, nonatomic) ADJAttribution* attribution;
@property(retain, nonatomic) NSObject<AdjustDelegate>* delegate;
@property(retain, nonatomic) id<ADJLogger> logger;
@property(retain, nonatomic) ADJTimer* timer;
@property(retain, nonatomic) ADJActivityState* activityState;
@property(retain, nonatomic) id<ADJAttributionHandler> attributionHandler;
@property(retain, nonatomic) id<ADJPackageHandler> packageHandler;
@property(retain, nonatomic) NSObject<OS_dispatch_queue>* internalQueue;
+(id)handlerWithConfig:(id)config;
-(void).cxx_destruct;
-(BOOL)checkTransactionId:(id)anId;
-(BOOL)checkActivityState:(id)state;
-(void)removeNotificationObserver;
-(void)addNotificationObserver;
-(void)timerFired;
-(void)stopTimer;
-(void)startTimer;
-(void)transferSessionPackage;
-(void)readAttribution;
-(void)readActivityState;
-(void)writeAttribution;
-(void)writeActivityState;
-(BOOL)updateActivityState:(double)state;
-(void)setDeviceTokenInternal:(id)internal;
-(BOOL)trySetAttributionDeeplink:(id)deeplink withKey:(id)key withValue:(id)value;
-(void)appWillOpenUrlInternal:(id)app;
-(void)eventInternal:(id)internal;
-(void)endInternal;
-(void)startInternal;
-(id)buildAttributionHandler;
-(void)initInternal;
-(void)setAskingAttribution:(BOOL)attribution;
-(void)setOfflineMode:(BOOL)mode;
-(void)launchAttributionDelegate;
-(BOOL)updateAttribution:(id)attribution;
-(void)setIadDate:(id)date withPurchaseDate:(id)purchaseDate;
-(void)setDeviceToken:(id)token;
-(void)appWillOpenUrl:(id)app;
-(BOOL)isEnabled;
-(void)launchDeepLink:(id)link;
-(void)finishedTrackingWithResponse:(id)response;
-(void)trackEvent:(id)event;
-(void)trackSubsessionEnd;
-(void)trackSubsessionStart;
-(id)initWithConfig:(id)config;
@end

