/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSObject;
@protocol AdjustDelegate;

__attribute__((visibility("hidden")))
@interface ADJConfig : XXUnknownSuperclass <NSCopying> {
	BOOL _eventBufferingEnabled;
	BOOL _macMd5TrackingEnabled;
	BOOL _hasDelegate;
	NSString* _appToken;
	int _logLevel;
	NSString* _environment;
	NSString* _sdkPrefix;
	NSObject<AdjustDelegate>* _delegate;
}
@property(assign, nonatomic) BOOL hasDelegate;
@property(retain, nonatomic) NSObject<AdjustDelegate>* delegate;
@property(assign, nonatomic) BOOL macMd5TrackingEnabled;
@property(assign, nonatomic) BOOL eventBufferingEnabled;
@property(copy, nonatomic) NSString* sdkPrefix;
@property(readonly, copy, nonatomic) NSString* environment;
@property(assign, nonatomic) int logLevel;
@property(readonly, copy, nonatomic) NSString* appToken;
+(id)configWithAppToken:(id)appToken environment:(id)environment;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(BOOL)isValid;
-(BOOL)checkAppToken:(id)token;
-(BOOL)checkEnvironment:(id)environment logAssert:(BOOL)anAssert;
-(id)initWithoutCheckAppToken:(id)token environment:(id)environment;
-(id)initWithAppToken:(id)appToken environment:(id)environment;
@end

