/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSNumber, NSMutableDictionary, NSString, NSDictionary;
@protocol ADJLogger;

__attribute__((visibility("hidden")))
@interface ADJEvent : XXUnknownSuperclass <NSCopying> {
	NSString* _eventToken;
	NSNumber* _revenue;
	NSDictionary* _callbackParameters;
	NSDictionary* _partnerParameters;
	NSString* _transactionId;
	NSString* _currency;
	id<ADJLogger> _logger;
	NSMutableDictionary* _callbackMutableParameters;
	NSMutableDictionary* _partnerMutableParameters;
}
@property(retain, nonatomic) NSMutableDictionary* partnerMutableParameters;
@property(retain, nonatomic) NSMutableDictionary* callbackMutableParameters;
@property(retain, nonatomic) id<ADJLogger> logger;
@property(readonly, copy, nonatomic) NSString* currency;
@property(copy, nonatomic) NSString* transactionId;
@property(retain, nonatomic) NSDictionary* partnerParameters;
@property(retain, nonatomic) NSDictionary* callbackParameters;
@property(readonly, copy, nonatomic) NSNumber* revenue;
@property(readonly, copy, nonatomic) NSString* eventToken;
+(id)eventWithEventToken:(id)eventToken;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(BOOL)isValidParameter:(id)parameter attributeType:(id)type parameterName:(id)name;
-(BOOL)isValid;
-(BOOL)checkRevenue:(id)revenue currency:(id)currency;
-(BOOL)checkEventToken:(id)token;
-(void)setRevenue:(double)revenue currency:(id)currency;
-(void)addPartnerParameter:(id)parameter value:(id)value;
-(void)addCallbackParameter:(id)parameter value:(id)value;
-(id)initWithEventToken:(id)eventToken;
@end

