/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ADJLogger.h"
#import <XXUnknownSuperclass.h> // Unknown library


@protocol ADJLogger
-(void)assert:(id)anAssert;
-(void)error:(id)error;
-(void)warn:(id)warn;
-(void)info:(id)info;
-(void)debug:(id)debug;
-(void)verbose:(id)verbose;
-(void)setLogLevel:(int)level;
@end

__attribute__((visibility("hidden")))
@interface ADJLogger : XXUnknownSuperclass <ADJLogger> {
	int _loglevel;
}
@property(assign, nonatomic) int loglevel;
+(int)LogLevelFromString:(id)string;
-(void)logLevel:(id)level format:(id)format parameters:(void*)parameters;
-(void)assert:(id)anAssert;
-(void)error:(id)error;
-(void)warn:(id)warn;
-(void)info:(id)info;
-(void)debug:(id)debug;
-(void)verbose:(id)verbose;
-(void)setLogLevel:(int)level;
@end

