/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ADJPackageHandler.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSObject;
@protocol OS_dispatch_queue, ADJLogger, OS_dispatch_semaphore, ADJActivityHandler, ADJRequestHandler;

@protocol ADJPackageHandler
-(void)sendClickPackage:(id)package;
-(void)finishedTrackingActivity:(id)activity;
-(void)resumeSending;
-(void)pauseSending;
-(void)closeFirstPackage;
-(void)sendNextPackage;
-(void)sendFirstPackage;
-(void)addPackage:(id)package;
-(id)initWithActivityHandler:(id)activityHandler;
@end

__attribute__((visibility("hidden")))
@interface ADJPackageHandler : XXUnknownSuperclass <ADJPackageHandler> {
	BOOL _paused;
	NSObject<OS_dispatch_queue>* _internalQueue;
	NSObject<OS_dispatch_semaphore>* _sendingSemaphore;
	id<ADJActivityHandler> _activityHandler;
	id<ADJRequestHandler> _requestHandler;
	id<ADJLogger> _logger;
	NSMutableArray* _packageQueue;
}
@property(assign, nonatomic, getter=isPaused) BOOL paused;
@property(retain, nonatomic) NSMutableArray* packageQueue;
@property(retain, nonatomic) id<ADJLogger> logger;
@property(retain, nonatomic) id<ADJRequestHandler> requestHandler;
@property(assign, nonatomic) id<ADJActivityHandler> activityHandler;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore>* sendingSemaphore;
@property(retain, nonatomic) NSObject<OS_dispatch_queue>* internalQueue;
+(id)handlerWithActivityHandler:(id)activityHandler;
-(void).cxx_destruct;
-(id)packageQueueFilename;
-(void)writePackageQueue;
-(void)readPackageQueue;
-(void)sendNextInternal;
-(void)sendFirstInternal;
-(void)addInternal:(id)internal;
-(void)initInternal;
-(void)sendClickPackage:(id)package;
-(void)finishedTrackingActivity:(id)activity;
-(void)resumeSending;
-(void)pauseSending;
-(void)closeFirstPackage;
-(void)sendNextPackage;
-(void)sendFirstPackage;
-(void)addPackage:(id)package;
-(id)initWithActivityHandler:(id)activityHandler;
@end

