/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ADJRequestHandler.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSObject;
@protocol OS_dispatch_queue, ADJLogger, ADJPackageHandler;

@protocol ADJRequestHandler
-(void)sendClickPackage:(id)package;
-(void)sendPackage:(id)package;
-(id)initWithPackageHandler:(id)packageHandler;
@end

__attribute__((visibility("hidden")))
@interface ADJRequestHandler : XXUnknownSuperclass <ADJRequestHandler> {
	NSObject<OS_dispatch_queue>* _internalQueue;
	id<ADJPackageHandler> _packageHandler;
	id<ADJLogger> _logger;
	NSURL* _baseUrl;
}
@property(retain, nonatomic) NSURL* baseUrl;
@property(assign, nonatomic) id<ADJLogger> logger;
@property(assign, nonatomic) id<ADJPackageHandler> packageHandler;
@property(retain, nonatomic) NSObject<OS_dispatch_queue>* internalQueue;
+(id)handlerWithPackageHandler:(id)packageHandler;
-(void).cxx_destruct;
-(void)checkErrorResponse:(id)response;
-(void)checkMessageResponse:(id)response;
-(id)bodyForParameters:(id)parameters;
-(id)requestForPackage:(id)package;
-(void)sendInternal:(id)internal sendToPackageHandler:(BOOL)packageHandler;
-(void)sendClickPackage:(id)package;
-(void)sendPackage:(id)package;
-(id)initWithPackageHandler:(id)packageHandler;
@end

