/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject;
@protocol OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface ADJTimer : XXUnknownSuperclass {
	BOOL _suspended;
	NSObject<OS_dispatch_source>* _source;
}
@property(assign, nonatomic) BOOL suspended;
@property(retain, nonatomic) NSObject<OS_dispatch_source>* source;
+(id)timerWithStart:(unsigned long long)start leeway:(unsigned long long)leeway queue:(id)queue block:(id)block;
+(id)timerWithInterval:(unsigned long long)interval leeway:(unsigned long long)leeway queue:(id)queue block:(id)block;
-(void).cxx_destruct;
-(void)cancel;
-(void)suspend;
-(void)resume;
-(id)initWithStart:(unsigned long long)start leeway:(unsigned long long)leeway queue:(id)queue block:(id)block;
-(id)initWithInterval:(unsigned long long)interval leeway:(unsigned long long)leeway queue:(id)queue block:(id)block;
@end

