/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol ADJLogger, ADJActivityHandler;

__attribute__((visibility("hidden")))
@interface Adjust : XXUnknownSuperclass {
	id<ADJActivityHandler> _activityHandler;
	id<ADJLogger> _logger;
}
@property(retain, nonatomic) id<ADJLogger> logger;
@property(retain, nonatomic) id<ADJActivityHandler> activityHandler;
+(id)getInstance;
+(void)setOfflineMode:(BOOL)mode;
+(void)setDeviceToken:(id)token;
+(void)appWillOpenUrl:(id)app;
+(BOOL)isEnabled;
+(void)setEnabled:(BOOL)enabled;
+(void)trackSubsessionEnd;
+(void)trackSubsessionStart;
+(void)trackEvent:(id)event;
+(void)appDidLaunch:(id)app;
-(void).cxx_destruct;
-(BOOL)checkActivityHandler;
-(void)setOfflineMode:(BOOL)mode;
-(void)setDeviceToken:(id)token;
-(void)appWillOpenUrl:(id)app;
-(BOOL)isEnabled;
-(void)setEnabled:(BOOL)enabled;
-(void)trackSubsessionEnd;
-(void)trackSubsessionStart;
-(void)trackEvent:(id)event;
-(void)appDidLaunch:(id)app;
-(id)init;
@end

