/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ADJUtil : XXUnknownSuperclass {
}
+(id)queryString:(id)string;
+(void)writeObject:(id)object filename:(id)filename objectName:(id)name;
+(id)readObject:(id)object objectName:(id)name class:(Class)aClass;
+(id)getFullFilename:(id)filename;
+(id)buildJsonDict:(id)dict;
+(id)formatDate:(id)date;
+(id)formatSeconds1970:(double)a1970;
+(void)excludeFromBackup:(id)backup;
+(id)clientSdk;
+(id)baseUrl;
+(void)initialize;
@end

