/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "BITCrashManagerDelegate.h"
#import "BITHockeyManagerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "HelpshiftDelegate.h"
#import "SKProductsRequestDelegate.h"
#import "SKPaymentTransactionObserver.h"
#import "MFMailComposeViewControllerDelegate.h"
#import "ADInterstitialAdDelegate.h"
#import "MFMessageComposeViewControllerDelegate.h"
#import "UITextFieldDelegate.h"
#import "UIWebViewDelegate.h"
#import "UIApplicationDelegate.h"

@class UIWindow, EAGLView, SplashView, NSMutableArray, UITextField, NSPredicate, UIWebView, UIImageView, SKProductsRequest, NSString;

__attribute__((visibility("hidden")))
@interface AppDelegate : XXUnknownSuperclass <BITHockeyManagerDelegate, BITCrashManagerDelegate, HelpshiftDelegate, SKProductsRequestDelegate, SKPaymentTransactionObserver, MFMailComposeViewControllerDelegate, ADInterstitialAdDelegate, MFMessageComposeViewControllerDelegate, UITextFieldDelegate, UIWebViewDelegate, UIApplicationDelegate> {
	UIWindow* window;
	EAGLView* eglView;
	UITextField* textView;
	NSPredicate* predicate;
	UIWebView* webView;
	UIImageView* loadingView;
	BOOL isLagging;
	SplashView* splashView;
	NSMutableArray* products;
	SKProductsRequest* productsRequest;
}
@property(retain, nonatomic) UIWindow* window;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)sharedDelegate;
-(void)presentFrame;
-(void)refreshLoading;
-(void)appFrame:(id)frame;
-(void)stopAppThread;
-(void)startAppThread;
-(unsigned)application:(id)application supportedInterfaceOrientationsForWindow:(id)window;
-(void)applicationDidReceiveMemoryWarning:(id)application;
-(void)applicationWillResignActive:(id)application;
-(void)applicationDidBecomeActive:(id)application;
-(void)applicationWillTerminate:(id)application;
-(BOOL)application:(id)application openURL:(id)url sourceApplication:(id)application3 annotation:(id)annotation;
-(void)applicationDidEnterBackground:(id)application;
-(void)applicationWillEnterForeground:(id)application;
-(BOOL)application:(id)application didFinishLaunchingWithOptions:(id)options;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)userIDForHockeyManager:(id)hockeyManager componentManager:(id)manager;
-(id)applicationLogForCrashManager:(id)crashManager;
-(void)helpshiftSessionHasEnded;
-(void)didReceiveInAppNotificationWithMessageCount:(int)messageCount;
-(void)didReceiveNotificationCount:(int)count;
-(void)paymentQueue:(id)queue updatedTransactions:(id)transactions;
-(void)productsRequest:(id)request didReceiveResponse:(id)response;
-(void)requestDidFinish:(id)request;
-(void)request:(id)request didFailWithError:(id)error;
-(void)consume:(id)consume;
-(void)purchase:(id)purchase;
-(void)requestInventory:(id)inventory;
-(void)stopIAP;
-(void)startIAP;
-(void)mailComposeController:(id)controller didFinishWithResult:(int)result error:(id)error;
-(void)interstitialAd:(id)ad didFailWithError:(id)error;
-(void)interstitialAdDidUnload:(id)interstitialAd;
-(void)interstitialAdDidLoad:(id)interstitialAd;
-(void)messageComposeViewController:(id)controller didFinishWithResult:(int)result;
-(BOOL)textFieldShouldReturn:(id)textField;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(void)onEditingChanged:(id)changed;
-(void)onKeyboardWillHideNotification:(id)onKeyboard;
-(void)onKeyboardWillShowNotification:(id)onKeyboard;
-(void)audioSessionDidChangeInterruptionType:(id)audioSession;
-(void)webViewDidFinishLoad:(id)webView;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)application:(id)application didFailToRegisterForRemoteNotificationsWithError:(id)error;
-(void)application:(id)application didRegisterForRemoteNotificationsWithDeviceToken:(id)deviceToken;
-(void)application:(id)application didReceiveLocalNotification:(id)notification;
-(void)application:(id)application didReceiveRemoteNotification:(id)notification;
@end

