/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface Base64 : XXUnknownSuperclass {
}
+(id)decode:(id)decode;
+(id)decode:(const char*)decode length:(int)length;
+(id)encode:(id)encode;
+(id)encode:(const char*)encode length:(int)length;
+(void)initialize;
@end

