/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSArray;

@interface BFAppLink : XXUnknownSuperclass {
	BOOL _isBackToReferrer;
	NSURL* _sourceURL;
	NSArray* _targets;
	NSURL* _webURL;
}
@property(assign, nonatomic) BOOL isBackToReferrer;
@property(retain, nonatomic) NSURL* webURL;
@property(copy, nonatomic) NSArray* targets;
@property(retain, nonatomic) NSURL* sourceURL;
+(id)appLinkWithSourceURL:(id)sourceURL targets:(id)targets webURL:(id)url;
+(id)appLinkWithSourceURL:(id)sourceURL targets:(id)targets webURL:(id)url isBackToReferrer:(BOOL)referrer;
-(void).cxx_destruct;
-(id)initWithIsBackToReferrer:(BOOL)referrer;
@end

