/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "headshot-Structs.h"

@class UIView, BFAppLink, UIButton, UITapGestureRecognizer, UIColor, UILabel;
@protocol BFAppLinkReturnToRefererViewDelegate;

@interface BFAppLinkReturnToRefererView : XXUnknownSuperclass {
	BOOL _closed;
	id<BFAppLinkReturnToRefererViewDelegate> _delegate;
	UIColor* _textColor;
	BFAppLink* _refererAppLink;
	int _includeStatusBarInSize;
	UILabel* _labelView;
	UIButton* _closeButton;
	UITapGestureRecognizer* _insideTapGestureRecognizer;
	UIView* _viewToMoveWithNavController;
}
@property(retain, nonatomic) UIView* viewToMoveWithNavController;
@property(retain, nonatomic) UITapGestureRecognizer* insideTapGestureRecognizer;
@property(retain, nonatomic) UIButton* closeButton;
@property(retain, nonatomic) UILabel* labelView;
@property(assign, nonatomic) BOOL closed;
@property(assign, nonatomic) int includeStatusBarInSize;
@property(retain, nonatomic) BFAppLink* refererAppLink;
@property(retain, nonatomic) UIColor* textColor;
@property(assign, nonatomic) __weak id<BFAppLinkReturnToRefererViewDelegate> delegate;
-(void).cxx_destruct;
-(void)onTapInside:(id)inside;
-(void)closeButtonTapped:(id)tapped;
-(BOOL)hasRefererData;
-(id)localizedLabelForReferer:(id)referer;
-(id)drawCloseButtonImageWithColor:(id)color;
-(void)updateColors;
-(void)updateLabelText;
-(float)statusBarHeight;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)layoutSubviews;
-(void)initViews;
-(void)commonInit;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
@end

