/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BFAppLinkReturnToRefererViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UINavigationController, BFURL, NSString, NSURL, BFAppLinkReturnToRefererView;
@protocol BFAppLinkReturnToRefererControllerDelegate;

@interface BFAppLinkReturnToRefererController : XXUnknownSuperclass <BFAppLinkReturnToRefererViewDelegate> {
	BFURL* _lastShownBFUrl;
	NSURL* _lastShownUrl;
	BFAppLinkReturnToRefererView* _view;
	id<BFAppLinkReturnToRefererControllerDelegate> _delegate;
	UINavigationController* _attachedToNavController;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UINavigationController* attachedToNavController;
@property(retain, nonatomic) BFAppLinkReturnToRefererView* view;
@property(assign, nonatomic) __weak id<BFAppLinkReturnToRefererControllerDelegate> delegate;
-(void).cxx_destruct;
-(void)openRefererAppLink:(id)link;
-(void)closeViewAnimated:(BOOL)animated;
-(void)moveNavigationBar;
-(void)orientationDidChange:(id)orientation;
-(void)statusBarFrameDidChange:(id)statusBarFrame;
-(void)statusBarFrameWillChange:(id)statusBarFrame;
-(void)returnToRefererViewDidTapInsideLink:(id)returnToRefererView link:(id)link;
-(void)returnToRefererViewDidTapInsideCloseButton:(id)returnToRefererView;
-(void)removeFromNavController;
-(void)showViewForRefererURL:(id)refererURL;
-(void)showViewForRefererAppLink:(id)refererAppLink;
-(void)dealloc;
-(id)initForDisplayAboveNavController:(id)displayAboveNavController;
-(id)init;
@end

