/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSException, NSCondition, NSMutableArray, NSError, NSObject;

@interface BFTask : XXUnknownSuperclass {
	id _result;
	NSError* _error;
	NSException* _exception;
	BOOL _cancelled;
	BOOL _completed;
	NSObject* _lock;
	NSCondition* _condition;
	NSMutableArray* _callbacks;
}
@property(retain, nonatomic) NSMutableArray* callbacks;
@property(retain, nonatomic) NSCondition* condition;
@property(retain, nonatomic) NSObject* lock;
@property(assign, nonatomic, getter=isCompleted) BOOL completed;
@property(assign, nonatomic, getter=isCancelled) BOOL cancelled;
@property(readonly, assign, nonatomic) NSException* exception;
@property(readonly, assign, nonatomic) NSError* error;
@property(readonly, assign, nonatomic) id result;
+(id)taskFromExecutor:(id)executor withBlock:(id)block;
+(id)taskWithDelay:(int)delay;
+(id)taskForCompletionOfAllTasks:(id)allTasks;
+(id)cancelledTask;
+(id)taskWithException:(id)exception;
+(id)taskWithError:(id)error;
+(id)taskWithResult:(id)result;
-(void).cxx_destruct;
-(void)waitUntilFinished;
-(void)warnOperationOnMainThread;
-(id)continueWithSuccessBlock:(id)successBlock;
-(id)continueWithExecutor:(id)executor withSuccessBlock:(id)successBlock;
-(id)continueWithBlock:(id)block;
-(id)continueWithExecutor:(id)executor withBlock:(id)block;
-(void)runContinuations;
-(void)setCompleted;
-(BOOL)trySetCancelled;
-(void)cancel;
-(BOOL)trySetException:(id)exception;
-(void)setException:(id)exception;
-(BOOL)trySetError:(id)error;
-(void)setError:(id)error;
-(BOOL)trySetResult:(id)result;
-(void)setResult:(id)result;
-(id)init;
@end

