/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BFAppLinkResolving.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface BFWebViewAppLinkResolver : XXUnknownSuperclass <BFAppLinkResolving> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)sharedInstance;
-(id)appLinkFromALData:(id)aldata destination:(id)destination;
-(id)getALDataFromLoadedPage:(id)loadedPage;
-(id)parseALData:(id)data;
-(id)appLinkFromURLInBackground:(id)background;
-(id)followRedirects:(id)redirects;
@end

