/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "headshot-Structs.h"
#import "UITextFieldDelegate.h"

@class UITextField, NSString;
@protocol BITAuthenticationViewControllerDelegate;

@interface BITAuthenticationViewController : XXUnknownSuperclass <UITextFieldDelegate> {
	int _statusBarStyle;
	UITextField* _emailField;
	BOOL _showsLoginViaWebButton;
	BOOL _requirePassword;
	NSString* _tableViewTitle;
	id<BITAuthenticationViewControllerDelegate> _delegate;
	NSString* _email;
	NSString* _password;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) NSString* password;
@property(copy, nonatomic) NSString* email;
@property(assign, nonatomic) __weak id<BITAuthenticationViewControllerDelegate> delegate;
@property(assign, nonatomic) BOOL requirePassword;
@property(copy, nonatomic) NSString* tableViewTitle;
@property(assign, nonatomic) BOOL showsLoginViaWebButton;
-(void).cxx_destruct;
-(void)setLoginUIEnabled:(BOOL)enabled;
-(void)saveAction:(id)action;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)userPasswordEntered:(id)entered;
-(void)userEmailEntered:(id)entered;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForFooterInSection:(int)section;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)allRequiredFieldsEntered;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)handleWebLoginButton:(id)button;
-(void)updateWebLoginButton;
-(void)updateBarButtons;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)initWithDelegate:(id)delegate;
@end

