/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BITImageAnnotation.h"
#import "headshot-Structs.h"

@class CAShapeLayer;

@interface BITArrowImageAnnotation : BITImageAnnotation {
	CAShapeLayer* _shapeLayer;
	CAShapeLayer* _strokeLayer;
}
@property(retain, nonatomic) CAShapeLayer* strokeLayer;
@property(retain, nonatomic) CAShapeLayer* shapeLayer;
+(CGAffineTransform)dqd_transformForStartPoint:(CGPoint)startPoint endPoint:(CGPoint)point length:(float)length;
-(void).cxx_destruct;
-(void)layoutSubviews;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(CGAffineTransform)transformForStartPoint:(CGPoint)startPoint endPoint:(CGPoint)point length:(float)length;
-(void)getAxisAlignedArrowPoints:(CGPoint [7])points forLength:(float)length tailWidth:(float)width headWidth:(float)width4 headLength:(float)length5;
-(id)bezierPathWithArrowFromPoint:(CGPoint)point toPoint:(CGPoint)point2 tailWidth:(float)width headWidth:(float)width4 headLength:(float)length;
-(void)buildShape;
-(id)initWithFrame:(CGRect)frame;
@end

