/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIActivityIndicatorView;

@interface BITActivityIndicatorButton : XXUnknownSuperclass {
	BOOL _indicatorVisible;
	UIActivityIndicatorView* _indicator;
}
@property(assign, nonatomic) BOOL indicatorVisible;
@property(retain, nonatomic) UIActivityIndicatorView* indicator;
-(void).cxx_destruct;
-(void)layoutSubviews;
-(void)setShowsActivityIndicator:(BOOL)indicator;
@end

