/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BITImageAnnotation.h"
#import "headshot-Structs.h"

@class CALayer, UIImage;

@interface BITBlurImageAnnotation : BITImageAnnotation {
	CALayer* _imageLayer;
	UIImage* _scaledImage;
	CALayer* _selectedLayer;
}
@property(retain, nonatomic) CALayer* selectedLayer;
@property(retain, nonatomic) UIImage* scaledImage;
@property(retain, nonatomic) CALayer* imageLayer;
-(void).cxx_destruct;
-(BOOL)resizable;
-(void)layoutSubviews;
-(void)setSelected:(BOOL)selected;
-(void)setSourceImage:(id)image;
-(id)initWithFrame:(CGRect)frame;
@end

