/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BITHockeyBaseManager.h"
#import "headshot-Structs.h"

@class BITPLCrashReporter, NSMutableArray, BITHockeyAppClient, BITCrashDetails, NSMutableDictionary, NSFileManager, NSString;

@interface BITCrashManager : BITHockeyBaseManager {
	NSMutableDictionary* _approvedCrashReports;
	NSMutableArray* _crashFiles;
	NSString* _lastCrashFilename;
	NSString* _settingsFile;
	NSString* _analyzerInProgressFile;
	NSFileManager* _fileManager;
	PLCrashReporterCallbacks* _crashCallBacks;
	BOOL _crashIdenticalCurrentVersion;
	BOOL _sendingInProgress;
	BOOL _isSetup;
	BOOL _didLogLowMemoryWarning;
	id _appDidBecomeActiveObserver;
	id _appWillTerminateObserver;
	id _appDidEnterBackgroundObserver;
	id _appWillEnterForegroundObserver;
	id _appDidReceiveLowMemoryWarningObserver;
	id _networkDidBecomeReachableObserver;
	BOOL _enableMachExceptionHandler;
	BOOL _enableOnDeviceSymbolication;
	BOOL _enableAppNotTerminatingCleanlyDetection;
	BOOL _showAlwaysButton;
	BOOL _didCrashInLastSession;
	BOOL _didReceiveMemoryWarningInLastSession;
	unsigned _crashManagerStatus;
	BITCrashDetails* _lastSessionCrashDetails;
	id _delegate;
	BITHockeyAppClient* _hockeyAppClient;
	/*function-pointer*/ void* _exceptionHandler;
	BITPLCrashReporter* _plCrashReporter;
	id _alertViewHandler;
	NSString* _crashesDir;
	double _timeintervalCrashInLastSessionOccured;
}
@property(retain, nonatomic) NSString* crashesDir;
@property(copy, nonatomic, setter=setAlertViewHandler:) id alertViewHandler;
@property(retain, nonatomic) NSString* lastCrashFilename;
@property(retain, nonatomic) BITPLCrashReporter* plCrashReporter;
@property(retain, nonatomic) NSFileManager* fileManager;
@property(assign, nonatomic) /*function-pointer*/ void* exceptionHandler;
@property(retain, nonatomic) BITHockeyAppClient* hockeyAppClient;
@property(assign, nonatomic) __weak id delegate;
@property(readonly, assign, nonatomic) double timeintervalCrashInLastSessionOccured;
@property(readonly, assign, nonatomic) BOOL didReceiveMemoryWarningInLastSession;
@property(readonly, assign, nonatomic) BITCrashDetails* lastSessionCrashDetails;
@property(readonly, assign, nonatomic) BOOL didCrashInLastSession;
@property(assign, nonatomic, getter=shouldShowAlwaysButton) BOOL showAlwaysButton;
@property(assign, nonatomic, getter=isAppNotTerminatingCleanlyDetectionEnabled) BOOL enableAppNotTerminatingCleanlyDetection;
@property(assign, nonatomic, getter=isOnDeviceSymbolicationEnabled) BOOL enableOnDeviceSymbolication;
@property(assign, nonatomic, getter=isMachExceptionHandlerEnabled) BOOL enableMachExceptionHandler;
@property(assign, nonatomic) unsigned crashManagerStatus;
-(void).cxx_destruct;
-(void)sendCrashReportWithFilename:(id)filename xml:(id)xml attachment:(id)attachment;
-(id)requestWithXML:(id)xml attachment:(id)attachment;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(void)sendNextCrashReport;
-(void)createCrashReportForAppKill;
-(void)startManager;
-(void)invokeDelayedProcessing;
-(void)triggerDelayedProcessing;
-(BOOL)hasPendingCrashReport;
-(id)firstNotApprovedCrashReport;
-(void)handleCrashReport;
-(BOOL)handleUserInput:(unsigned)input withUserProvidedMetaData:(id)userProvidedMetaData;
-(void)storeMetaDataForCrashReportFilename:(id)crashReportFilename;
-(void)generateTestCrash;
-(BOOL)isDebuggerAttached;
-(void)setCrashCallbacks:(BITCrashManagerCallbacks*)callbacks;
-(id)userEmailForCrashReport;
-(id)userNameForCrashReport;
-(id)userIDForCrashReport;
-(id)osBuild;
-(id)deviceArchitecture;
-(void)appEnteredForeground;
-(void)leavingAppSafely;
-(void)unregisterObserver:(id)observer;
-(void)unregisterObservers;
-(void)registerObservers;
-(id)extractAppUUIDs:(id)uuids;
-(id)attachmentForCrashReport:(id)crashReport;
-(void)persistUserProvidedMetaData:(id)data;
-(void)persistAttachment:(id)attachment withFilename:(id)filename;
-(void)cleanCrashReports;
-(void)cleanCrashReportWithFilename:(id)filename;
-(void)loadSettings;
-(void)saveSettings;
-(void)dealloc;
-(id)init;
@end

