/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface BITCrashMetaData : XXUnknownSuperclass {
	NSString* _userDescription;
	NSString* _userName;
	NSString* _userEmail;
	NSString* _userID;
}
@property(copy, nonatomic) NSString* userID;
@property(copy, nonatomic) NSString* userEmail;
@property(copy, nonatomic) NSString* userName;
@property(copy, nonatomic) NSString* userDescription;
-(void).cxx_destruct;
@end

