/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BITHockeyAttachment.h"


@interface BITCrashAttachment : BITHockeyAttachment {
}
-(id)initWithFilename:(id)filename crashAttachmentData:(id)data contentType:(id)type;
@end

