/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDate;

@interface BITCrashDetails : XXUnknownSuperclass {
	NSString* _incidentIdentifier;
	NSString* _reporterKey;
	NSString* _signal;
	NSString* _exceptionName;
	NSString* _exceptionReason;
	NSDate* _appStartTime;
	NSDate* _crashTime;
	NSString* _osVersion;
	NSString* _osBuild;
	NSString* _appBuild;
}
@property(readonly, assign, nonatomic) NSString* appBuild;
@property(readonly, assign, nonatomic) NSString* osBuild;
@property(readonly, assign, nonatomic) NSString* osVersion;
@property(readonly, assign, nonatomic) NSDate* crashTime;
@property(readonly, assign, nonatomic) NSDate* appStartTime;
@property(readonly, assign, nonatomic) NSString* exceptionReason;
@property(readonly, assign, nonatomic) NSString* exceptionName;
@property(readonly, assign, nonatomic) NSString* signal;
@property(readonly, assign, nonatomic) NSString* reporterKey;
@property(readonly, assign, nonatomic) NSString* incidentIdentifier;
-(void).cxx_destruct;
-(BOOL)isAppKill;
-(id)initWithIncidentIdentifier:(id)incidentIdentifier reporterKey:(id)key signal:(id)signal exceptionName:(id)name exceptionReason:(id)reason appStartTime:(id)time crashTime:(id)time7 osVersion:(id)version osBuild:(id)build appBuild:(id)build10;
@end

