/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol BITCrashManagerDelegate <NSObject>
@optional
-(BOOL)considerAppNotTerminatedCleanlyReportForCrashManager:(id)crashManager;
-(void)crashManagerDidFinishSendingCrashReport:(id)crashManager;
-(void)crashManager:(id)manager didFailWithError:(id)error;
-(void)crashManagerWillSendCrashReport:(id)crashManager;
-(void)crashManagerWillSendCrashReportsAlways:(id)crashManager;
-(void)crashManagerWillCancelSendingCrashReport:(id)crashManager;
-(void)crashManagerWillShowSubmitCrashReportAlert:(id)crashManager;
-(id)userEmailForCrashManager:(id)crashManager;
-(id)userNameForCrashManager:(id)crashManager;
-(id)attachmentForCrashManager:(id)crashManager;
-(id)applicationLogForCrashManager:(id)crashManager;
@end

