/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSNumber, NSString, NSDate;

@interface BITFeedbackMessage : XXUnknownSuperclass {
	BOOL _userMessage;
	NSString* _text;
	NSString* _userID;
	NSString* _name;
	NSString* _email;
	NSDate* _date;
	NSNumber* _identifier;
	NSString* _token;
	NSArray* _attachments;
	int _status;
}
@property(assign, nonatomic) BOOL userMessage;
@property(assign, nonatomic) int status;
@property(retain, nonatomic) NSArray* attachments;
@property(copy, nonatomic) NSString* token;
@property(copy, nonatomic) NSNumber* identifier;
@property(copy, nonatomic) NSDate* date;
@property(copy, nonatomic) NSString* email;
@property(copy, nonatomic) NSString* name;
@property(copy, nonatomic) NSString* userID;
@property(copy, nonatomic) NSString* text;
-(void).cxx_destruct;
-(void)addAttachmentsObject:(id)object;
-(id)previewableAttachments;
-(void)deleteContents;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)init;
@end

