/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDateFormatter, BITAttributedLabel, UILabel, UIView, BITFeedbackMessage, NSMutableArray;
@protocol BITFeedbackListViewCellDelegate;

@interface BITFeedbackListViewCell : XXUnknownSuperclass {
	BITFeedbackMessage* _message;
	unsigned _style;
	unsigned _backgroundStyle;
	BITAttributedLabel* _labelText;
	id<BITFeedbackListViewCellDelegate> _delegate;
	NSDateFormatter* _dateFormatter;
	NSDateFormatter* _timeFormatter;
	UILabel* _labelTitle;
	NSMutableArray* _attachmentViews;
	UIView* _accessoryBackgroundView;
}
@property(retain, nonatomic) UIView* accessoryBackgroundView;
@property(retain, nonatomic) NSMutableArray* attachmentViews;
@property(retain, nonatomic) UILabel* labelTitle;
@property(retain, nonatomic) NSDateFormatter* timeFormatter;
@property(retain, nonatomic) NSDateFormatter* dateFormatter;
@property(assign, nonatomic) __weak id<BITFeedbackListViewCellDelegate> delegate;
@property(retain, nonatomic) BITAttributedLabel* labelText;
@property(assign, nonatomic) unsigned backgroundStyle;
@property(assign, nonatomic) unsigned style;
@property(retain, nonatomic) BITFeedbackMessage* message;
+(float)heightForTextInRowWithMessage:(id)message tableViewWidth:(float)width;
+(float)heightForRowWithMessage:(id)message tableViewWidth:(float)width;
-(void).cxx_destruct;
-(void)imageButtonPressed:(id)pressed;
-(void)layoutSubviews;
-(void)setAttachments:(id)attachments;
-(BOOL)isSameDayWithDate1:(id)date1 date2:(id)a2;
-(id)backgroundColor;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

