/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSURLConnectionDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSData, NSString, NSURLRequest, NSURLConnection, NSMutableData, NSHTTPURLResponse, NSError;

@interface BITHTTPOperation : XXUnknownSuperclass <NSURLConnectionDelegate> {
	NSURLRequest* _URLRequest;
	NSURLConnection* _connection;
	NSMutableData* _data;
	BOOL _isExecuting;
	BOOL _isFinished;
	NSHTTPURLResponse* _response;
	NSError* _error;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) NSError* error;
@property(readonly, assign, nonatomic) NSData* data;
@property(readonly, assign, nonatomic) NSHTTPURLResponse* response;
@property(readonly, assign, nonatomic) NSURLRequest* URLRequest;
+(id)operationWithRequest:(id)request;
-(void).cxx_destruct;
-(BOOL)isExecuting;
-(BOOL)isFinished;
-(void)setCompletion:(id)completion;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)finish;
-(void)start;
-(void)cancel;
-(BOOL)isConcurrent;
@end

