/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCoding.h"

@class NSData, NSString;

@interface BITHockeyAttachment : XXUnknownSuperclass <NSCoding> {
	NSString* _filename;
	NSData* _hockeyAttachmentData;
	NSString* _contentType;
}
@property(readonly, assign, nonatomic) NSString* contentType;
@property(readonly, assign, nonatomic) NSData* hockeyAttachmentData;
@property(readonly, assign, nonatomic) NSString* filename;
-(void).cxx_destruct;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)initWithFilename:(id)filename hockeyAttachmentData:(id)data contentType:(id)type;
@end

