/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDateFormatter, UINavigationController, UIColor, NSString;

@interface BITHockeyBaseManager : XXUnknownSuperclass {
	UINavigationController* _navController;
	NSDateFormatter* _rfc3339Formatter;
	BOOL _isAppStoreEnvironment;
	NSString* _serverURL;
	int _barStyle;
	UIColor* _navigationBarTintColor;
	int _modalPresentationStyle;
	NSString* _appIdentifier;
}
@property(retain, nonatomic) NSString* appIdentifier;
@property(assign, nonatomic) int modalPresentationStyle;
@property(retain, nonatomic) UIColor* navigationBarTintColor;
@property(assign, nonatomic) int barStyle;
@property(copy, nonatomic) NSString* serverURL;
-(void).cxx_destruct;
-(id)parseRFC3339Date:(id)date;
-(void)startManager;
-(BOOL)removeKeyFromKeychain:(id)keychain;
-(id)stringValueFromKeychainForKey:(id)key;
-(BOOL)addStringValueToKeychainForThisDeviceOnly:(id)thisDeviceOnly forKey:(id)key;
-(BOOL)addStringValueToKeychain:(id)keychain forKey:(id)key;
-(void)showView:(id)view;
-(id)customNavigationControllerWithRootViewController:(id)rootViewController presentationStyle:(int)style;
-(id)findVisibleWindow;
-(id)executableUUID;
-(id)getDevicePlatform;
-(BOOL)isPreiOS7Environment;
-(id)encodedAppIdentifier;
-(BOOL)isAppStoreEnvironment;
-(void)reportError:(id)error;
-(id)initWithAppIdentifier:(id)appIdentifier isAppStoreEnvironment:(BOOL)environment;
-(id)init;
@end

