/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class BITCrashManager, BITHockeyAppClient, NSString, BITUpdateManager, BITStoreUpdateManager, BITAuthenticator, BITFeedbackManager;
@protocol BITHockeyManagerDelegate;

@interface BITHockeyManager : XXUnknownSuperclass {
	NSString* _appIdentifier;
	NSString* _liveIdentifier;
	BOOL _validAppIdentifier;
	BOOL _startManagerIsInvoked;
	BOOL _startUpdateManagerIsInvoked;
	BOOL _managersInitialized;
	BITHockeyAppClient* _hockeyAppClient;
	BOOL _disableCrashManager;
	BOOL _disableUpdateManager;
	BOOL _enableStoreUpdateManager;
	BOOL _disableFeedbackManager;
	BOOL _appStoreEnvironment;
	BOOL _debugLogEnabled;
	id<BITHockeyManagerDelegate> _delegate;
	NSString* _serverURL;
	BITCrashManager* _crashManager;
	BITUpdateManager* _updateManager;
	BITStoreUpdateManager* _storeUpdateManager;
	BITFeedbackManager* _feedbackManager;
	BITAuthenticator* _authenticator;
	NSString* _installString;
	NSString* _userID;
	NSString* _userName;
	NSString* _userEmail;
}
@property(retain, nonatomic) NSString* userEmail;
@property(retain, nonatomic) NSString* userName;
@property(retain, nonatomic) NSString* userID;
@property(assign, nonatomic, getter=isDebugLogEnabled) BOOL debugLogEnabled;
@property(readonly, assign, nonatomic) NSString* installString;
@property(readonly, assign, nonatomic, getter=isAppStoreEnvironment) BOOL appStoreEnvironment;
@property(readonly, assign, nonatomic) BITAuthenticator* authenticator;
@property(assign, nonatomic, getter=isFeedbackManagerDisabled) BOOL disableFeedbackManager;
@property(readonly, assign, nonatomic) BITFeedbackManager* feedbackManager;
@property(assign, nonatomic, getter=isStoreUpdateManagerEnabled) BOOL enableStoreUpdateManager;
@property(readonly, assign, nonatomic) BITStoreUpdateManager* storeUpdateManager;
@property(assign, nonatomic, getter=isUpdateManagerDisabled) BOOL disableUpdateManager;
@property(readonly, assign, nonatomic) BITUpdateManager* updateManager;
@property(assign, nonatomic, getter=isCrashManagerDisabled) BOOL disableCrashManager;
@property(readonly, assign, nonatomic) BITCrashManager* crashManager;
@property(retain, nonatomic) NSString* serverURL;
@property(assign, nonatomic) __weak id<BITHockeyManagerDelegate> delegate;
+(id)sharedHockeyManager;
-(void).cxx_destruct;
-(void)initializeModules;
-(BOOL)shouldUseLiveIdentifier;
-(BOOL)isSetUpOnMainThread;
-(void)validateStartManagerIsInvoked;
-(void)pingServerForIntegrationStartWorkflowWithTimeString:(id)timeString appIdentifier:(id)identifier;
-(BOOL)integrationFlowStartedWithTimeString:(id)timeString;
-(id)integrationFlowTimeString;
-(id)hockeyAppClient;
-(id)build;
-(id)version;
-(void)testIdentifier;
-(void)modifyKeychainUserValue:(id)value forKey:(id)key;
-(void)startManager;
-(void)configureWithBetaIdentifier:(id)betaIdentifier liveIdentifier:(id)identifier delegate:(id)delegate;
-(void)configureWithIdentifier:(id)identifier delegate:(id)delegate;
-(void)configureWithIdentifier:(id)identifier;
-(void)dealloc;
-(id)init;
-(void)logInvalidIdentifier:(id)identifier;
-(BOOL)checkValidityOfAppIdentifier:(id)appIdentifier;
@end

