/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface BITHockeyBaseViewController : XXUnknownSuperclass {
	BOOL _modal;
	int _statusBarStyle;
	BOOL _modalAnimated;
}
@property(assign, nonatomic) BOOL modalAnimated;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)onDismissModal:(id)modal;
-(id)initWithModalStyle:(BOOL)modalStyle;
-(id)initWithStyle:(int)style modal:(BOOL)modal;
-(id)initWithStyle:(int)style;
@end

