/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"
#import "BITCrashManagerDelegate.h"


@protocol BITHockeyManagerDelegate <NSObject, BITCrashManagerDelegate>
@optional
-(id)userEmailForHockeyManager:(id)hockeyManager componentManager:(id)manager;
-(id)userNameForHockeyManager:(id)hockeyManager componentManager:(id)manager;
-(id)userIDForHockeyManager:(id)hockeyManager componentManager:(id)manager;
-(id)viewControllerForHockeyManager:(id)hockeyManager componentManager:(id)manager;
-(BOOL)shouldUseLiveIdentifierForHockeyManager:(id)hockeyManager;
@end

