/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class BITImageAnnotation, UIImageView, NSMutableArray, UISegmentedControl, UITapGestureRecognizer, UIPanGestureRecognizer, UIPinchGestureRecognizer, UIImage;
@protocol BITImageAnnotationDelegate;

@interface BITImageAnnotationViewController : XXUnknownSuperclass {
	UIImage* _image;
	id<BITImageAnnotationDelegate> _delegate;
	UIImageView* _imageView;
	UISegmentedControl* _editingControls;
	NSMutableArray* _objects;
	UITapGestureRecognizer* _tapRecognizer;
	UIPanGestureRecognizer* _panRecognizer;
	UIPinchGestureRecognizer* _pinchRecognizer;
	float _scaleFactor;
	BITImageAnnotation* _currentAnnotation;
	int _currentInteraction;
	CGPoint _panStart;
	CGRect _pinchStartingFrame;
}
@property(assign, nonatomic) CGRect pinchStartingFrame;
@property(assign, nonatomic) int currentInteraction;
@property(retain, nonatomic) BITImageAnnotation* currentAnnotation;
@property(assign, nonatomic) CGPoint panStart;
@property(assign, nonatomic) float scaleFactor;
@property(retain, nonatomic) UIPinchGestureRecognizer* pinchRecognizer;
@property(retain, nonatomic) UIPanGestureRecognizer* panRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer* tapRecognizer;
@property(retain, nonatomic) NSMutableArray* objects;
@property(retain, nonatomic) UISegmentedControl* editingControls;
@property(retain, nonatomic) UIImageView* imageView;
@property(assign, nonatomic) __weak id<BITImageAnnotationDelegate> delegate;
@property(retain, nonatomic) UIImage* image;
-(void).cxx_destruct;
-(BOOL)canDrawNewAnnotation;
-(id)firstAnnotationThatIsNotBlur;
-(void)tapped:(id)tapped;
-(void)pinched:(id)pinched;
-(void)panned:(id)panned;
-(id)extractImage;
-(void)save:(id)save;
-(void)discard:(id)discard;
-(id)annotationForCurrentMode;
-(void)editingAction:(id)action;
-(void)fitImageViewFrame;
-(void)orientationDidChange:(id)orientation;
-(BOOL)prefersStatusBarHidden;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
@end

