/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface BITPLCrashHostInfo : XXUnknownSuperclass {
	PLCrashHostInfoVersion _darwinVersion;
}
@property(readonly, assign, nonatomic) PLCrashHostInfoVersion darwinVersion;
+(id)currentHostInfo;
-(id)init;
@end

