/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "headshot-Structs.h"

@class NSString;

@interface BITPLCrashProcessInfo : XXUnknownSuperclass {
	int _processID;
	NSString* _processName;
	int _parentProcessID;
	timeval _startTime;
	BOOL _traced;
}
@property(readonly, assign, nonatomic, getter=isTraced) BOOL traced;
@property(readonly, assign, nonatomic) timeval startTime;
@property(readonly, assign, nonatomic) int parentProcessID;
@property(readonly, assign, nonatomic) NSString* processName;
@property(readonly, assign, nonatomic) int processID;
+(id)currentProcessInfo;
-(void)dealloc;
-(id)initWithProcessID:(int)processID;
@end

