/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface BITPLCrashSignalHandler : XXUnknownSuperclass {
	darwin_sigaltstack _sigstk;
}
+(void)resetHandlers;
+(id)sharedHandler;
+(void)initialize;
-(id).cxx_construct;
-(BOOL)registerHandlerForSignal:(int)signal callback:(/*function-pointer*/ void*)callback context:(void*)context error:(id*)error;
-(BOOL)registerHandlerWithSignal:(int)signal error:(id*)error;
-(id)init;
@end

