/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class BITPLCrashReportSymbolInfo;

@interface BITPLCrashReportStackFrameInfo : XXUnknownSuperclass {
	unsigned long long _instructionPointer;
	BITPLCrashReportSymbolInfo* _symbolInfo;
}
@property(readonly, assign, nonatomic) BITPLCrashReportSymbolInfo* symbolInfo;
@property(readonly, assign, nonatomic) unsigned long long instructionPointer;
-(void)dealloc;
-(id)initWithInstructionPointer:(unsigned long long)instructionPointer symbolInfo:(id)info;
@end

