/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class BITPLCrashReportSystemInfo, BITPLCrashReportApplicationInfo, BITPLCrashReportExceptionInfo, BITPLCrashReportSignalInfo, BITPLCrashReportProcessInfo, BITPLCrashReportMachineInfo, BITPLCrashReportMachExceptionInfo, NSArray;

@interface BITPLCrashReport : XXUnknownSuperclass {
	PLCrashReportDecoder* _decoder;
	BITPLCrashReportSystemInfo* _systemInfo;
	BITPLCrashReportMachineInfo* _machineInfo;
	BITPLCrashReportApplicationInfo* _applicationInfo;
	BITPLCrashReportProcessInfo* _processInfo;
	BITPLCrashReportSignalInfo* _signalInfo;
	BITPLCrashReportMachExceptionInfo* _machExceptionInfo;
	NSArray* _threads;
	NSArray* _images;
	BITPLCrashReportExceptionInfo* _exceptionInfo;
	CFUUIDRef _uuid;
}
@property(readonly, assign, nonatomic) CFUUIDRef uuidRef;
@property(readonly, assign, nonatomic) BITPLCrashReportExceptionInfo* exceptionInfo;
@property(readonly, assign, nonatomic) BOOL hasExceptionInfo;
@property(readonly, assign, nonatomic) NSArray* images;
@property(readonly, assign, nonatomic) NSArray* threads;
@property(readonly, assign, nonatomic) BITPLCrashReportMachExceptionInfo* machExceptionInfo;
@property(readonly, assign, nonatomic) BITPLCrashReportSignalInfo* signalInfo;
@property(readonly, assign, nonatomic) BITPLCrashReportProcessInfo* processInfo;
@property(readonly, assign, nonatomic) BOOL hasProcessInfo;
@property(readonly, assign, nonatomic) BITPLCrashReportApplicationInfo* applicationInfo;
@property(readonly, assign, nonatomic) BITPLCrashReportMachineInfo* machineInfo;
@property(readonly, assign, nonatomic) BOOL hasMachineInfo;
@property(readonly, assign, nonatomic) BITPLCrashReportSystemInfo* systemInfo;
-(id)imageForAddress:(unsigned long long)address;
-(void)dealloc;
-(id)initWithData:(id)data error:(id*)error;
-(id)extractMachExceptionInfo:(Plcrash__CrashReport__Signal__MachException*)info error:(id*)error;
-(id)extractSignalInfo:(Plcrash__CrashReport__Signal*)info error:(id*)error;
-(id)extractExceptionInfo:(Plcrash__CrashReport__Exception*)info error:(id*)error;
-(id)extractImageInfo:(Plcrash__CrashReport*)info error:(id*)error;
-(id)extractThreadInfo:(Plcrash__CrashReport*)info error:(id*)error;
-(id)extractStackFrameInfo:(Plcrash__CrashReport__Thread__StackFrame*)info error:(id*)error;
-(id)extractSymbolInfo:(Plcrash__CrashReport__Symbol*)info error:(id*)error;
-(id)extractProcessInfo:(Plcrash__CrashReport__ProcessInfo*)info error:(id*)error;
-(id)extractApplicationInfo:(Plcrash__CrashReport__ApplicationInfo*)info error:(id*)error;
-(id)extractMachineInfo:(Plcrash__CrashReport__MachineInfo*)info error:(id*)error;
-(id)extractProcessorInfo:(Plcrash__CrashReport__Processor*)info error:(id*)error;
-(id)extractSystemInfo:(Plcrash__CrashReport__SystemInfo*)info error:(id*)error;
-(Plcrash__CrashReport*)decodeCrashData:(id)data error:(id*)error;
@end

