/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface BITPLCrashMachExceptionServer : XXUnknownSuperclass {
	plcrash_exception_server_context* _serverContext;
}
@property(readonly, assign, nonatomic) unsigned serverThread;
-(void)dealloc;
-(id)exceptionPortWithMask:(unsigned)mask error:(id*)error;
-(unsigned)copySendRightForServerAndReturningError:(id*)serverAndReturningError;
-(id)initWithCallBack:(/*function-pointer*/ void*)callBack context:(void*)context error:(id*)error;
@end

