/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BITImageAnnotation.h"
#import "headshot-Structs.h"

@class CAShapeLayer;

@interface BITRectangleImageAnnotation : BITImageAnnotation {
	CAShapeLayer* _shapeLayer;
	CAShapeLayer* _strokeLayer;
}
@property(retain, nonatomic) CAShapeLayer* strokeLayer;
@property(retain, nonatomic) CAShapeLayer* shapeLayer;
-(void).cxx_destruct;
-(BOOL)resizable;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

