/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class BITStoreButtonData, CALayer;
@protocol BITStoreButtonDelegate;

@interface BITStoreButton : XXUnknownSuperclass {
	CALayer* _defaultBorderLayer;
	CALayer* _inActiveBorderLayer;
	id<BITStoreButtonDelegate> _buttonDelegate;
	BITStoreButtonData* _buttonData;
	unsigned _style;
	CGPoint _customPadding;
}
@property(assign, nonatomic) unsigned style;
@property(assign, nonatomic) CGPoint customPadding;
@property(retain, nonatomic) BITStoreButtonData* buttonData;
@property(assign, nonatomic) __weak id<BITStoreButtonDelegate> buttonDelegate;
-(void).cxx_destruct;
-(void)setButtonData:(id)data animated:(BOOL)animated;
-(void)setFrame:(CGRect)frame;
-(CGSize)sizeThatFits:(CGSize)fits;
-(id)initWithPadding:(CGPoint)padding style:(unsigned)style;
-(id)initWithFrame:(CGRect)frame;
-(void)alignToSuperview;
-(void)updateButtonAnimated:(BOOL)animated;
-(void)animationDidStop:(id)animation finished:(id)finished context:(void*)context;
-(void)buttonPressed:(id)pressed;
@end

