/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIWebViewDelegate.h"
#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor, NSString, UIWebView;

@interface BITWebTableViewCell : XXUnknownSuperclass <UIWebViewDelegate> {
	UIWebView* _webView;
	NSString* _webViewContent;
	UIColor* _cellBackgroundColor;
	CGSize _webViewSize;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UIColor* cellBackgroundColor;
@property(assign, nonatomic) CGSize webViewSize;
@property(copy, nonatomic) NSString* webViewContent;
@property(retain, nonatomic) UIWebView* webView;
-(void).cxx_destruct;
-(void)webViewDidFinishLoad:(id)webView;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)prepareForReuse;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(void)removeWebView;
-(void)showWebView;
-(void)addWebView;
@end

