/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface DateComponent : XXUnknownSuperclass {
	NSString* _unitString;
	int _value;
}
@property(assign, nonatomic) int value;
@property(retain, nonatomic) NSString* unitString;
+(id)dateComponentWithUnit:(id)unit value:(int)value;
-(void).cxx_destruct;
-(id)stringValue;
@end

