/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSString, NSDate;

@interface FBAccessTokenData : XXUnknownSuperclass <NSCopying> {
	NSString* _accessToken;
	NSString* _appID;
	NSString* _userID;
	NSArray* _permissions;
	NSArray* _declinedPermissions;
	NSDate* _expirationDate;
	unsigned _loginType;
	NSDate* _refreshDate;
	NSDate* _permissionsRefreshDate;
}
@property(copy, nonatomic) NSDate* permissionsRefreshDate;
@property(copy, nonatomic) NSDate* refreshDate;
@property(readonly, assign, nonatomic) unsigned loginType;
@property(readonly, copy, nonatomic) NSDate* expirationDate;
@property(copy, nonatomic) NSArray* declinedPermissions;
@property(copy, nonatomic) NSArray* permissions;
@property(copy, nonatomic) NSString* userID;
@property(copy, nonatomic) NSString* appID;
@property(readonly, copy, nonatomic) NSString* accessToken;
+(id)createTokenFromString:(id)string permissions:(id)permissions declinedPermissions:(id)permissions3 expirationDate:(id)date loginType:(unsigned)type refreshDate:(id)date6 permissionsRefreshDate:(id)date7 appID:(id)anId userID:(id)anId9;
+(id)createTokenFromString:(id)string permissions:(id)permissions expirationDate:(id)date loginType:(unsigned)type refreshDate:(id)date5 permissionsRefreshDate:(id)date6 appID:(id)anId;
+(id)createTokenFromString:(id)string permissions:(id)permissions expirationDate:(id)date loginType:(unsigned)type refreshDate:(id)date5 permissionsRefreshDate:(id)date6;
+(id)createTokenFromString:(id)string permissions:(id)permissions expirationDate:(id)date loginType:(unsigned)type refreshDate:(id)date5;
+(id)createTokenFromDictionary:(id)dictionary;
+(id)createTokenFromFacebookURL:(id)facebookURL appID:(id)anId urlSchemeSuffix:(id)suffix;
-(id)description;
-(id)dictionary;
-(BOOL)isEqualToAccessTokenData:(id)accessTokenData;
-(id)copyWithZone:(NSZone*)zone;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(void)dealloc;
-(id)initWithToken:(id)token permissions:(id)permissions declinedPermissions:(id)permissions3 expirationDate:(id)date loginType:(unsigned)type refreshDate:(id)date6 permissionsRefreshDate:(id)date7 appID:(id)anId userID:(id)anId9;
@end

