/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSString, NSURL, NSDictionary;

@interface FBAppLinkData : XXUnknownSuperclass {
	NSURL* _targetURL;
	NSArray* _actionTypes;
	NSArray* _actionIDs;
	NSString* _ref;
	NSString* _userAgent;
	NSDictionary* _refererData;
	NSDictionary* _originalQueryParameters;
	NSURL* _originalURL;
	NSDictionary* _arguments;
}
@property(copy) NSDictionary* arguments;
@property(retain) NSURL* originalURL;
@property(copy) NSDictionary* originalQueryParameters;
@property(copy) NSDictionary* refererData;
@property(copy) NSString* userAgent;
@property(copy) NSString* ref;
@property(copy) NSArray* actionIDs;
@property(copy) NSArray* actionTypes;
@property(retain) NSURL* targetURL;
+(id)createFromURL:(id)url;
-(id)description;
-(BOOL)isValid;
-(void)dealloc;
-(id)initWithURL:(id)url targetURL:(id)url2 ref:(id)ref userAgent:(id)agent refererData:(id)data originalParams:(id)params;
-(id)initWithURL:(id)url targetURL:(id)url2 originalParams:(id)params arguments:(id)arguments;
-(id)initWithURL:(id)url;
@end

