/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface FBAppBridgeScheme : XXUnknownSuperclass {
	NSString* _version;
}
@property(copy, nonatomic) NSString* version;
+(id)_validAppBridgeSchemeWithConfig:(id)config forMethod:(id)method;
+(id)_validAppBridgeSchemeForMethod:(id)method minVersion:(id)version;
+(id)_URLForMethod:(id)method queryParams:(id)params schemeVersion:(id)version version:(id)version4;
+(id)_installedAppBridgeSchemeForMethod:(id)method minVersion:(id)version;
+(BOOL)isSupportedScheme:(id)scheme;
+(id)bridgeSchemeForFBMessengerForOpenGraphActionShareDialogParams:(id)openGraphActionShareDialogParams;
+(id)bridgeSchemeForFBMessengerForShareDialogPhotos;
+(id)bridgeSchemeForFBMessengerForShareDialogParams:(id)shareDialogParams;
+(id)bridgeSchemeForFBAppForLike;
+(id)bridgeSchemeForFBAppForOpenGraphActionShareDialogParams:(id)openGraphActionShareDialogParams;
+(id)bridgeSchemeForFBAppForShareDialogPhotos;
+(id)bridgeSchemeForFBAppForShareDialogParams:(id)shareDialogParams;
+(id)bridgeVersions;
+(id)schemePrefix;
+(void)updateDialogConfigs;
+(void)initialize;
-(id)URLForMethod:(id)method queryParams:(id)params;
-(void)dealloc;
-(id)initWithVersion:(id)version;
@end

