/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableDictionary, FBAppBridgeTypeToJSONConverter;

@interface FBAppBridge : XXUnknownSuperclass {
	NSMutableDictionary* _pendingAppCalls;
	NSMutableDictionary* _callbacks;
	FBAppBridgeTypeToJSONConverter* _jsonConverter;
	NSString* _appID;
	NSString* _bundleID;
	NSString* _appName;
}
@property(copy, nonatomic) NSString* appName;
@property(copy, nonatomic) NSString* bundleID;
@property(copy, nonatomic) NSString* appID;
@property(retain, nonatomic) FBAppBridgeTypeToJSONConverter* jsonConverter;
@property(retain, nonatomic) NSMutableDictionary* callbacks;
@property(retain, nonatomic) NSMutableDictionary* pendingAppCalls;
+(id)errorFromDictionary:(id)dictionary;
+(void)_copyValueForKey:(id)key fromDictionary:(id)dictionary toDictionary:(id)dictionary3;
+(id)_coerceValue:(id)value;
+(id)appIconFromBundleInfo:(id)bundleInfo;
+(id)symmetricKeyAndForceRefresh:(BOOL)refresh;
+(id)sharedInstance;
-(void)deletePasteboardsForAppCallID:(id)appCallID;
-(void)savePasteboardNames:(id)names forAppCallID:(id)appCallID;
-(id)dictionaryFromJSONString:(id)jsonstring;
-(id)jsonStringFromDictionary:(id)dictionary;
-(void)stopTrackingCallWithID:(id)anId;
-(void)trackAppCall:(id)call withCompletionHandler:(id)completionHandler;
-(void)addAppMetadataToDictionary:(id)dictionary;
-(id)decryptUrlQueryParams:(id)params method:(id)method fallbackHandler:(id)handler;
-(BOOL)processResponse:(id)response method:(id)method session:(id)session fallbackHandler:(id)handler;
-(void)handleDidBecomeActive;
-(BOOL)handleOpenURL:(id)url sourceApplication:(id)application session:(id)session fallbackHandler:(id)handler;
-(void)invoke:(id)invoke forFailedAppCall:(id)failedAppCall withMessage:(id)message;
-(void)performDialogAppCall:(id)call bridgeScheme:(id)scheme session:(id)session completionHandler:(id)handler;
-(void)dispatchDialogAppCall:(id)call bridgeScheme:(id)scheme session:(id)session completionHandler:(id)handler;
-(void)dealloc;
-(id)init;
@end

