/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCacheDelegate.h"

@class NSCache, NSString, NSObject;
@protocol OS_dispatch_queue, FBCacheIndexFileDelegate;

@interface FBCacheIndex : XXUnknownSuperclass <NSCacheDelegate> {
	id<FBCacheIndexFileDelegate> _delegate;
	NSCache* _cachedEntries;
	unsigned _currentDiskUsage;
	unsigned _diskCapacity;
	sqlite3* _database;
	sqlite3_stmt* _insertStatement;
	sqlite3_stmt* _removeByKeyStatement;
	sqlite3_stmt* _selectByKeyStatement;
	sqlite3_stmt* _selectByKeyFragmentStatement;
	sqlite3_stmt* _selectExcludingKeyFragmentStatement;
	sqlite3_stmt* _trimStatement;
	sqlite3_stmt* _updateStatement;
	NSObject<OS_dispatch_queue>* _databaseQueue;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) NSObject<OS_dispatch_queue>* databaseQueue;
@property(assign, nonatomic) unsigned entryCacheCountLimit;
@property(assign, nonatomic) unsigned diskCapacity;
@property(readonly, assign, nonatomic) unsigned currentDiskUsage;
@property(assign) id delegate;
-(void)_trimDatabase;
-(void)_flushOrphanedFiles;
-(void)_dropTrimmingTable;
-(void)_removeEntryFromDatabaseForKey:(id)key;
-(id)_entryForKey:(id)key;
-(void)_fetchCurrentDiskUsage;
-(id)_createCacheEntityInfo:(sqlite3_stmt*)info;
-(id)_readEntriesFromDatabase:(id)database excludingFragment:(BOOL)fragment;
-(id)_readEntryFromDatabase:(id)database;
-(void)_writeEntryInDatabase:(id)database;
-(void)_updateEntryInDatabaseForKey:(id)key entry:(id)entry;
-(void)cache:(id)cache willEvictObject:(id)object;
-(void)removeEntries:(id)entries excludingFragment:(BOOL)fragment;
-(void)removeEntryForKey:(id)key;
-(id)storeFileForKey:(id)key withData:(id)data;
-(id)fileNameForKey:(id)key;
-(void)dealloc;
-(id)initWithCacheFolder:(id)cacheFolder;
@end

