/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDictionary;

@interface FBDialogsData : XXUnknownSuperclass {
	NSString* _method;
	NSDictionary* _arguments;
	NSDictionary* _clientState;
	NSDictionary* _results;
}
@property(copy, nonatomic) NSDictionary* results;
@property(copy, nonatomic) NSDictionary* clientState;
@property(copy, nonatomic) NSDictionary* arguments;
@property(copy, nonatomic) NSString* method;
-(BOOL)isValid;
-(void)dealloc;
-(id)description;
-(id)initWithMethod:(id)method arguments:(id)arguments;
@end

