/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface FBErrorUtility : XXUnknownSuperclass {
}
+(BOOL)isTransientError:(id)error;
+(id)apiUserMessageForError:(id)error;
+(id)userTitleForError:(id)error;
+(id)innerErrorInfoFromError:(id)error;
+(BOOL)errorIsNetworkError:(id)error;
+(id)jsonDictionaryForError:(id)error;
+(id)fberrorForSystemPasswordChange:(id)systemPasswordChange;
+(id)fberrorForRetry:(id)retry;
+(void)fberrorGetCodeValueForError:(id)error index:(unsigned)index code:(int*)code subcode:(int*)subcode;
+(unsigned)errorSubcodeForError:(id)error;
+(unsigned)errorCodeForError:(id)error;
+(BOOL)fberrorIsErrorFromSystemSession:(id)systemSession;
+(int)fberrorCategoryFromError:(id)error code:(int)code subcode:(int)subcode returningUserMessage:(id*)message andShouldNotifyUser:(BOOL*)anAnd;
+(id)userMessageForError:(id)error;
+(BOOL)shouldNotifyUserForError:(id)error;
+(int)errorCategoryForError:(id)error;
@end

