/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDictionary;

@interface FBFetchedAppSettings : XXUnknownSuperclass {
	BOOL _supportsAttribution;
	BOOL _supportsImplicitSdkLogging;
	BOOL _enableLoginTooltip;
	NSString* _serverAppName;
	NSString* _appID;
	NSString* _loginTooltipContent;
	NSDictionary* _dialogConfigs;
	unsigned _appEventsFeatureOptions;
}
@property(assign) unsigned appEventsFeatureOptions;
@property(copy, nonatomic) NSDictionary* dialogConfigs;
@property(copy, nonatomic) NSString* loginTooltipContent;
@property(retain, nonatomic) NSString* appID;
@property(assign) BOOL enableLoginTooltip;
@property(assign) BOOL supportsImplicitSdkLogging;
@property(assign) BOOL supportsAttribution;
@property(copy, nonatomic) NSString* serverAppName;
-(BOOL)shouldAccessAdvertisingID;
-(void)dealloc;
-(id)initWithAppID:(id)appID appEventsFeatureOptions:(unsigned)options;
-(id)init;
@end

