/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "FBRequestDelegate.h"

@class NSArray, FBRequest, NSString;

@interface FBFrictionlessRequestSettings : XXUnknownSuperclass <FBRequestDelegate> {
	NSArray* _allowedRecipients;
	FBRequest* _activeRequest;
	BOOL _enabled;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) FBRequest* activeRequest;
@property(retain) NSArray* allowedRecipients;
@property(readonly, assign, nonatomic) NSArray* recipientIDs;
@property(readonly, assign, nonatomic) BOOL enabled;
-(void)dealloc;
-(void)request:(id)request didFailWithError:(id)error;
-(void)request:(id)request didLoad:(id)load;
-(void)updateRecipientCacheWithRequestResult:(id)requestResult;
-(BOOL)isFrictionlessEnabledForRecipients:(id)recipients;
-(BOOL)isFrictionlessEnabledForRecipient:(id)recipient;
-(void)updateRecipientCacheWithRecipients:(id)recipients;
-(void)reloadRecipientCacheWithFacebook:(id)facebook;
-(void)enableWithFacebook:(id)facebook;
-(id)init;
@end

