/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBCacheDescriptor.h"
#import "FBWebDialogsDelegate.h"
#import "FBFrictionlessDialogSupportDelegate.h"

@class NSArray, FBFrictionlessRequestSettings, NSString;

@interface FBFrictionlessRecipientCache : FBCacheDescriptor <FBFrictionlessDialogSupportDelegate, FBWebDialogsDelegate> {
	BOOL _frictionlessShouldMakeViewInvisible;
	FBFrictionlessRequestSettings* _frictionlessSettings;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) FBFrictionlessRequestSettings* frictionlessSettings;
@property(assign, nonatomic) BOOL frictionlessShouldMakeViewInvisible;
@property(copy, nonatomic) NSArray* recipientIDs;
-(void)webDialogsWillPresentDialog:(id)webDialogs parameters:(id)parameters session:(id)session;
-(void)prefetchAndCacheForSession:(id)session completionHandler:(id)handler;
-(void)prefetchAndCacheForSession:(id)session;
-(BOOL)areFrictionlessRecipients:(id)recipients;
-(BOOL)isFrictionlessRecipient:(id)recipient;
-(void)dealloc;
-(id)init;
@end

