/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBPeoplePickerViewController.h"

@class NSArray;

@interface FBFriendPickerViewController : FBPeoplePickerViewController {
}
@property(copy, nonatomic) NSArray* selection;
+(id)cacheIdentity;
+(id)graphAPIName;
+(double)cacheRefreshDelay;
+(id)firstRenderLogString;
+(unsigned)graphObjectPagingMode;
+(id)cacheDescriptorWithUserID:(id)userID fieldsForRequest:(id)request;
+(id)cacheDescriptor;
-(void)logAppEvents:(BOOL)events;
-(BOOL)delegateIncludesGraphObject:(id)object;
-(void)notifyDelegateOfError:(id)error;
-(void)notifyDelegateSelectionDidChange;
-(void)notifyDelegateDataDidChange;
-(void)configureUsingCachedDescriptor:(id)descriptor;
@end

