/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBCacheDescriptor.h"
#import "FBGraphObjectPagingLoaderDelegate.h"

@class FBGraphObjectPagingLoader, NSString, NSSet;

@interface FBFriendPickerCacheDescriptor : FBCacheDescriptor <FBGraphObjectPagingLoaderDelegate> {
	BOOL _hasCompletedFetch;
	BOOL _usePageLimitOfOne;
	NSSet* _fieldsForRequest;
	NSString* _userID;
	FBGraphObjectPagingLoader* _loader;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL usePageLimitOfOne;
@property(assign, nonatomic) BOOL hasCompletedFetch;
@property(retain, nonatomic) FBGraphObjectPagingLoader* loader;
@property(copy, nonatomic) NSString* userID;
@property(copy, nonatomic) NSSet* fieldsForRequest;
-(void)pagingLoaderDidFinishLoading:(id)pagingLoader;
-(void)setUsePageLimitOfOne;
-(void)prefetchAndCacheForSession:(id)session;
-(void)dealloc;
-(id)initWithUserID:(id)userID fieldsForRequest:(id)request;
-(id)initWithFieldsForRequest:(id)request;
-(id)initWithUserID:(id)userID;
-(id)init;
@end

