/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBViewController.h"
#import "FBGraphObjectSelectionChangedDelegate.h"
#import "FBGraphObjectPagingLoaderDelegate.h"

@class FBGraphObjectTableDataSource, NSSet, FBSession, UIActivityIndicatorView, UITableView, FBGraphObjectTableSelection, FBGraphObjectPagingLoader, NSString;

@interface FBGraphObjectPickerViewController : FBViewController <FBGraphObjectSelectionChangedDelegate, FBGraphObjectPagingLoaderDelegate> {
	FBSession* _session;
	BOOL _allowsMultipleSelection;
	BOOL _implicitSession;
	UIActivityIndicatorView* _spinner;
	UITableView* _tableView;
	NSSet* _fieldsForRequest;
	FBGraphObjectTableDataSource* _dataSource;
	FBGraphObjectTableSelection* _selectionManager;
	FBGraphObjectPagingLoader* _loader;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) FBGraphObjectPagingLoader* loader;
@property(retain, nonatomic) FBGraphObjectTableSelection* selectionManager;
@property(retain, nonatomic) FBGraphObjectTableDataSource* dataSource;
@property(assign, nonatomic) BOOL allowsMultipleSelection;
@property(retain, nonatomic) FBSession* session;
@property(assign, nonatomic) BOOL itemPicturesEnabled;
@property(copy, nonatomic) NSSet* fieldsForRequest;
@property(retain, nonatomic) UITableView* tableView;
@property(retain, nonatomic) UIActivityIndicatorView* spinner;
+(id)firstRenderLogString;
+(double)cacheRefreshDelay;
+(unsigned)graphObjectPagingMode;
-(void)pagingLoaderWasCancelled:(id)cancelled;
-(void)pagingLoader:(id)loader handleError:(id)error;
-(void)pagingLoaderDidFinishLoading:(id)pagingLoader;
-(void)pagingLoader:(id)loader didLoadData:(id)data;
-(void)pagingLoader:(id)loader willLoadURL:(id)url;
-(void)graphObjectTableSelectionDidChange:(id)graphObjectTableSelection;
-(void)_clearData;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)_removeSessionObserver:(id)observer;
-(void)_addSessionObserver:(id)observer;
-(void)_centerAndStartSpinner;
-(BOOL)delegateIncludesGraphObject:(id)object;
-(void)notifyDelegateOfError:(id)error;
-(void)notifyDelegateSelectionDidChange;
-(void)notifyDelegateDataDidChange;
-(void)loadDataSkippingRoundTripIfCached:(id)cached;
-(void)loadDataThrottledSkippingRoundTripIfCached:(id)cached;
-(void)configureDataSource:(id)source;
-(void)clearSelection;
-(void)updateView;
-(void)loadData;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)setSession:(id)session implicit:(BOOL)implicit;
-(void)dealloc;
-(void)initializeGraphObjectPicker;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(id)initWithCoder:(id)coder;
@end

