/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBGraphObjectSelectionQueryDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "headshot-Structs.h"
#import "UITableViewDelegate.h"

@class FBGraphObjectTableDataSource, NSObject, NSArray, NSString;
@protocol FBGraphObjectSelectionChangedDelegate;

@interface FBGraphObjectTableSelection : XXUnknownSuperclass <FBGraphObjectSelectionQueryDelegate, UITableViewDelegate> {
	BOOL _allowsMultipleSelection;
	NSObject<FBGraphObjectSelectionChangedDelegate>* _delegate;
	NSArray* _selection;
	FBGraphObjectTableDataSource* _dataSource;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) FBGraphObjectTableDataSource* dataSource;
@property(assign, nonatomic) BOOL allowsMultipleSelection;
@property(retain, nonatomic) NSArray* selection;
@property(assign, nonatomic) NSObject<FBGraphObjectSelectionChangedDelegate>* delegate;
-(void)tableView:(id)view didDeselectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)graphObjectTableDataSource:(id)source selectionIncludesItem:(id)item;
-(BOOL)selectionIncludesItem:(id)item;
-(void)selectionChanged;
-(void)deselectItems:(id)items tableView:(id)view;
-(void)deselectItem:(id)item cell:(id)cell raiseSelectionChanged:(BOOL)changed;
-(void)selectItem:(id)item tableView:(id)view;
-(void)selectItem:(id)item cell:(id)cell raiseSelectionChanged:(BOOL)changed;
-(void)clearSelectionInTableView:(id)tableView;
-(void)dealloc;
-(id)initWithDataSource:(id)dataSource;
@end

