/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBGraphObject.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSObject.h"

@class NSMutableDictionary, NSString;

@protocol FBGraphObject <NSObject>
@optional
@property(assign, nonatomic) BOOL provisionedForPost;
@required
-(void)setObject:(id)object forKey:(id)key;
-(void)removeObjectForKey:(id)key;
-(id)keyEnumerator;
-(id)objectForKey:(id)key;
-(unsigned)count;
@end

@interface FBGraphObject : XXUnknownSuperclass <FBGraphObject> {
	NSMutableDictionary* _jsonObject;
}
@property(assign, nonatomic) BOOL provisionedForPost;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(BOOL)isProtocolImplementationInferable:(id)inferable checkFBGraphObjectAdoption:(BOOL)adoption;
+(unsigned)inferredImplTypeForSelector:(SEL)selector;
+(id)graphObjectWrappingObject:(id)object;
+(BOOL)isGraphObjectID:(id)anId sameAs:(id)as;
+(id)openGraphObjectForPostWithType:(id)type title:(id)title image:(id)image url:(id)url description:(id)description;
+(id)openGraphObjectForPost;
+(id)openGraphActionForPost;
+(id)graphObjectWrappingDictionary:(id)dictionary;
+(id)graphObject;
-(void)removeObjectForKey:(id)key;
-(void)setObject:(id)object forKey:(id)key;
-(id)keyEnumerator;
-(id)objectForKey:(id)key;
-(unsigned)count;
-(void)graphObjectifyAll;
-(id)graphObjectifyAtKey:(id)key;
-(void)forwardInvocation:(id)invocation;
-(id)methodSignatureForSelector:(SEL)selector;
-(BOOL)conformsToProtocol:(id)protocol;
-(BOOL)respondsToSelector:(SEL)selector;
-(void)dealloc;
-(void)setObjectDescription:(id)description;
-(id)objectDescription;
-(void)setObjectID:(id)anId;
-(id)objectID;
-(id)initWrappingDictionary:(id)dictionary;
@end

