/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FBGraphObjectViewControllerDelegate <NSObject>
-(id)graphObjectTableDataSource:(id)source titleOfItem:(id)item;
@optional
-(void)graphObjectTableDataSource:(id)source customizeTableCell:(id)cell;
-(BOOL)graphObjectTableDataSource:(id)source filterIncludesItem:(id)item;
-(id)graphObjectTableDataSource:(id)source pictureUrlOfItem:(id)item;
-(id)graphObjectTableDataSource:(id)source subtitleOfItem:(id)item;
-(id)graphObjectTableDataSource:(id)source titleSuffixOfItem:(id)item;
@end

