/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBGraphObjectDataSourceDataNeededDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class FBRequestConnection, NSString, FBGraphObjectTableDataSource, UITableView, FBSession;
@protocol FBGraphObjectPagingLoaderDelegate;

@interface FBGraphObjectPagingLoader : XXUnknownSuperclass <FBGraphObjectDataSourceDataNeededDelegate> {
	BOOL _isResultFromCache;
	BOOL _skipRoundtripIfCached;
	UITableView* _tableView;
	FBGraphObjectTableDataSource* _dataSource;
	FBSession* _session;
	id<FBGraphObjectPagingLoaderDelegate> _delegate;
	unsigned _pagingMode;
	NSString* _nextLink;
	FBRequestConnection* _connection;
	NSString* _cacheIdentity;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL skipRoundtripIfCached;
@property(copy, nonatomic) NSString* cacheIdentity;
@property(retain, nonatomic) FBRequestConnection* connection;
@property(retain, nonatomic) NSString* nextLink;
@property(readonly, assign, nonatomic) BOOL isResultFromCache;
@property(assign, nonatomic) unsigned pagingMode;
@property(assign, nonatomic) id<FBGraphObjectPagingLoaderDelegate> delegate;
@property(retain, nonatomic) FBSession* session;
@property(retain, nonatomic) FBGraphObjectTableDataSource* dataSource;
@property(retain, nonatomic) UITableView* tableView;
-(void)graphObjectTableDataSourceNeedsData:(id)data triggeredByIndexPath:(id)path;
-(void)requestCompleted:(id)completed result:(id)result error:(id)error;
-(void)reset;
-(void)cancel;
-(void)startLoadingWithRequest:(id)request cacheIdentity:(id)identity skipRoundtripIfCached:(BOOL)cached;
-(void)followNextLink;
-(void)addResultsAndUpdateView:(id)view;
-(void)updateView;
-(void)dealloc;
-(id)initWithDataSource:(id)dataSource pagingMode:(unsigned)mode;
@end

