/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIActivityIndicatorView, UILabel, NSString, UIImage, UIImageView;

@interface FBGraphObjectTableCell : XXUnknownSuperclass {
	BOOL _boldTitle;
	BOOL _boldTitleSuffix;
	UIImageView* _pictureView;
	UILabel* _titleSuffixLabel;
	UIActivityIndicatorView* _activityIndicator;
}
@property(retain, nonatomic) UIActivityIndicatorView* activityIndicator;
@property(retain, nonatomic) UILabel* titleSuffixLabel;
@property(retain, nonatomic) UIImageView* pictureView;
@property(retain, nonatomic) UIImage* picture;
@property(copy, nonatomic) NSString* subtitle;
@property(assign, nonatomic) BOOL boldTitleSuffix;
@property(assign, nonatomic) BOOL boldTitle;
@property(copy, nonatomic) NSString* titleSuffix;
@property(copy, nonatomic) NSString* title;
+(float)rowHeight;
-(void)createTitleSuffixLabel;
-(void)updateFonts;
-(void)stopAnimatingActivityIndicator;
-(void)startAnimatingActivityIndicator;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

