/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface FBGraphObjectArray : XXUnknownSuperclass {
	NSMutableArray* _jsonArray;
}
-(void)replaceObjectAtIndex:(unsigned)index withObject:(id)object;
-(void)removeLastObject;
-(void)addObject:(id)object;
-(void)removeObjectAtIndex:(unsigned)index;
-(void)insertObject:(id)object atIndex:(unsigned)index;
-(id)reverseObjectEnumerator;
-(id)objectEnumerator;
-(id)objectAtIndex:(unsigned)index;
-(void)graphObjectifyAll;
-(id)graphObjectifyAtIndex:(unsigned)index;
-(unsigned)count;
-(void)dealloc;
-(id)initWrappingArray:(id)array;
@end

