/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface FBImageResourceLoader : XXUnknownSuperclass {
}
+(id)imageNamed:(id)named fromBytes:(const char*)bytes length:(unsigned)length fromRetinaBytes:(const char*)retinaBytes retinaLength:(unsigned)length5;
+(id)imageFromBytes:(const char*)bytes length:(unsigned)length fromRetinaBytes:(const char*)retinaBytes retinaLength:(unsigned)length4;
+(id)loadImageFromBytes:(const char*)bytes length:(unsigned)length scale:(float)scale;
@end

