/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface FBKeychainStore : XXUnknownSuperclass {
	NSString* _service;
	NSString* _accessGroup;
}
@property(readonly, copy, nonatomic) NSString* accessGroup;
@property(readonly, copy, nonatomic) NSString* service;
-(id)queryForKey:(id)key;
-(id)dataForKey:(id)key;
-(BOOL)setData:(id)data forKey:(id)key accessibility:(void*)accessibility;
-(BOOL)setData:(id)data forKey:(id)key;
-(id)stringForKey:(id)key;
-(BOOL)setString:(id)string forKey:(id)key accessibility:(void*)accessibility;
-(BOOL)setString:(id)string forKey:(id)key;
-(id)dictionaryForKey:(id)key;
-(BOOL)setDictionary:(id)dictionary forKey:(id)key accessibility:(void*)accessibility;
-(BOOL)setDictionary:(id)dictionary forKey:(id)key;
-(void)dealloc;
-(id)initWithService:(id)service accessGroup:(id)group;
-(id)initWithService:(id)service;
@end

