/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "FBDialogsParams.h"

@class NSArray, NSString, NSURL;

@interface FBLinkShareParams : FBDialogsParams {
	BOOL _dataFailuresFatal;
	NSURL* _link;
	NSString* _name;
	NSString* _caption;
	NSString* _linkDescription;
	NSURL* _picture;
	NSArray* _friends;
	id _place;
	NSString* _ref;
}
@property(assign, nonatomic) BOOL dataFailuresFatal;
@property(copy, nonatomic) NSString* ref;
@property(copy, nonatomic) id place;
@property(copy, nonatomic) NSArray* friends;
@property(copy, nonatomic) NSURL* picture;
@property(copy, nonatomic) NSString* linkDescription;
@property(copy, nonatomic) NSString* caption;
@property(copy, nonatomic) NSString* name;
@property(copy, nonatomic) NSURL* link;
+(id)methodName;
-(id)copyWithZone:(NSZone*)zone;
-(id)validate;
-(id)dictionaryMethodArgs;
-(void)dealloc;
-(id)initWithLink:(id)link name:(id)name caption:(id)caption description:(id)description picture:(id)picture;
@end

