/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBDialogsParams.h"
#import "headshot-Structs.h"

@class NSString;

@interface FBLikeDialogParams : FBDialogsParams {
	NSString* _objectID;
	unsigned _objectType;
}
@property(assign, nonatomic) unsigned objectType;
@property(copy, nonatomic) NSString* objectID;
+(id)methodName;
-(id)copyWithZone:(NSZone*)zone;
-(id)validate;
-(id)dictionaryMethodArgs;
-(void)dealloc;
@end

