/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSCache;

@interface FBLikeActionControllerCache : XXUnknownSuperclass {
	NSCache* _cache;
}
-(void)_activeSessionDidChangeWithNotification:(id)_activeSession;
-(void)setObject:(id)object forKeyedSubscript:(id)keyedSubscript;
-(id)objectForKeyedSubscript:(id)keyedSubscript;
-(void)dealloc;
-(id)init;
@end

