/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class FBRequestConnection, UIButton, NSNumber, NSArray, FBSession, NSString, UILabel;
@protocol FBLoginViewDelegate, FBGraphUser;

@interface FBLoginView : XXUnknownSuperclass <UIActionSheetDelegate> {
	BOOL _hasShownTooltipBubble;
	NSArray* _permissions;
	NSArray* _readPermissions;
	NSArray* _publishPermissions;
	unsigned _defaultAudience;
	unsigned _loginBehavior;
	unsigned _tooltipBehavior;
	unsigned _tooltipColorStyle;
	id<FBLoginViewDelegate> _delegate;
	UILabel* _label;
	UIButton* _button;
	FBSession* _session;
	FBRequestConnection* _requestConnection;
	id<FBGraphUser> _user;
	id _sessionStateHandler;
	id _requestHandler;
	NSNumber* _lastObservedStateWasOpen;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL hasShownTooltipBubble;
@property(copy) NSNumber* lastObservedStateWasOpen;
@property(copy, nonatomic) id requestHandler;
@property(copy, nonatomic) id sessionStateHandler;
@property(retain, nonatomic) id<FBGraphUser> user;
@property(retain, nonatomic) FBRequestConnection* requestConnection;
@property(retain, nonatomic) FBSession* session;
@property(retain, nonatomic) UIButton* button;
@property(retain, nonatomic) UILabel* label;
@property(assign, nonatomic) id<FBLoginViewDelegate> delegate;
@property(assign, nonatomic) unsigned tooltipColorStyle;
@property(assign, nonatomic) unsigned tooltipBehavior;
@property(assign, nonatomic) unsigned loginBehavior;
@property(assign, nonatomic) unsigned defaultAudience;
@property(copy, nonatomic) NSArray* publishPermissions;
@property(copy, nonatomic) NSArray* readPermissions;
@property(copy) NSArray* permissions;
-(void)buttonPressed:(id)pressed;
-(void)actionSheet:(id)sheet didDismissWithButtonIndex:(int)buttonIndex;
-(void)handleActiveSessionUnsetNotifications:(id)notifications;
-(void)handleActiveSessionSetNotifications:(id)notifications;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)unwireViewForSession;
-(void)wireViewForSession:(id)session userInfo:(id)info;
-(void)wireViewForSessionWithoutOpening:(id)sessionWithoutOpening;
-(void)informDelegateOfError:(id)error;
-(void)informDelegate:(BOOL)delegate;
-(void)didMoveToWindow;
-(void)showTooltipIfNeeded;
-(void)fetchMeInfo;
-(void)configureViewForStateLoggedIn:(BOOL)anIn;
-(id)logOutText;
-(id)logInText;
-(CGSize)sizeThatFits:(CGSize)fits;
-(CGSize)intrinsicContentSize;
-(void)initialize;
-(void)initializeBlocks;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithPublishPermissions:(id)publishPermissions defaultAudience:(unsigned)audience;
-(id)initWithReadPermissions:(id)readPermissions;
-(id)initWithPermissions:(id)permissions;
-(id)init;
@end

