/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "FBDialogsParams.h"

@class FBAppBridgeScheme, NSString;
@protocol FBOpenGraphAction;

@interface FBOpenGraphActionParams : FBDialogsParams {
	id<FBOpenGraphAction> _action;
	NSString* _previewPropertyName;
	NSString* _actionType;
	FBAppBridgeScheme* _bridgeScheme;
}
@property(retain, nonatomic) FBAppBridgeScheme* bridgeScheme;
@property(copy, nonatomic) NSString* actionType;
@property(copy, nonatomic) NSString* previewPropertyName;
@property(retain, nonatomic) id<FBOpenGraphAction> action;
+(id)getIdOrUrlFromObject:(id)object;
+(id)getPostedObjectTypeFromObject:(id)object;
+(id)methodName;
-(id)copyWithZone:(NSZone*)zone;
-(BOOL)containsUIImages:(id)images;
-(id)dictionaryMethodArgs;
-(id)flattenGraphObjects:(id)objects;
-(id)flattenObject:(id)object;
-(id)validate;
-(void)dealloc;
-(id)initWithAction:(id)action actionType:(id)type previewPropertyName:(id)name;
@end

