/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBGraphObjectViewControllerDelegate.h"
#import "FBGraphObjectPickerViewController.h"

@class NSArray, NSString;

@interface FBPeoplePickerViewController : FBGraphObjectPickerViewController <FBGraphObjectViewControllerDelegate> {
	NSString* _userID;
	unsigned _sortOrdering;
	unsigned _displayOrdering;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned displayOrdering;
@property(assign, nonatomic) unsigned sortOrdering;
@property(readonly, copy, nonatomic) NSArray* selection;
@property(copy, nonatomic) NSString* userID;
@property(assign, nonatomic) BOOL allowsMultipleSelection;
+(id)cacheIdentity;
+(id)requestWithUserID:(id)userID fields:(id)fields dataSource:(id)source session:(id)session;
+(id)graphAPIName;
-(void)graphObjectTableDataSource:(id)source customizeTableCell:(id)cell;
-(id)graphObjectTableDataSource:(id)source pictureUrlOfItem:(id)item;
-(id)graphObjectTableDataSource:(id)source titleSuffixOfItem:(id)item;
-(id)graphObjectTableDataSource:(id)source titleOfItem:(id)item;
-(BOOL)graphObjectTableDataSource:(id)source filterIncludesItem:(id)item;
-(void)loadDataSkippingRoundTripIfCached:(id)cached;
-(id)requestForLoadData;
-(void)configureDataSource:(id)source;
-(void)dealloc;
-(void)initializePeoplePicker;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(id)initWithCoder:(id)coder;
@end

