/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "FBDialogsParams.h"

@class NSArray;

@interface FBPhotoParams : FBDialogsParams {
	BOOL _dataFailuresFatal;
	NSArray* _friends;
	id _place;
	NSArray* _photos;
}
@property(copy, nonatomic) NSArray* photos;
@property(assign, nonatomic) BOOL dataFailuresFatal;
@property(copy, nonatomic) id place;
@property(copy, nonatomic) NSArray* friends;
+(id)methodName;
-(id)copyWithZone:(NSZone*)zone;
-(id)validate;
-(id)dictionaryMethodArgs;
-(void)dealloc;
-(id)initWithPhotos:(id)photos;
@end

