/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "FBCacheDescriptor.h"
#import "FBGraphObjectPagingLoaderDelegate.h"

@class FBGraphObjectPagingLoader, NSString, NSSet;

@interface FBPlacePickerCacheDescriptor : FBCacheDescriptor <FBGraphObjectPagingLoaderDelegate> {
	BOOL _hasCompletedFetch;
	int _radiusInMeters;
	int _resultsLimit;
	NSString* _searchText;
	NSSet* _fieldsForRequest;
	FBGraphObjectPagingLoader* _loader;
	XXStruct_zYrK5D _locationCoordinate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL hasCompletedFetch;
@property(retain, nonatomic) FBGraphObjectPagingLoader* loader;
@property(copy, nonatomic) NSSet* fieldsForRequest;
@property(copy, nonatomic) NSString* searchText;
@property(assign, nonatomic) int resultsLimit;
@property(assign, nonatomic) int radiusInMeters;
@property(assign, nonatomic) XXStruct_zYrK5D locationCoordinate;
-(void)pagingLoaderDidFinishLoading:(id)pagingLoader;
-(void)prefetchAndCacheForSession:(id)session;
-(void)dealloc;
-(id)initWithLocationCoordinate:(XXStruct_zYrK5D)locationCoordinate radiusInMeters:(int)meters searchText:(id)text resultsLimit:(int)limit fieldsForRequest:(id)request;
@end

