/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "FBGraphObjectViewControllerDelegate.h"
#import "FBGraphObjectPickerViewController.h"

@class NSTimer, NSString;
@protocol FBGraphPlace;

@interface FBPlacePickerViewController : FBGraphObjectPickerViewController <FBGraphObjectViewControllerDelegate> {
	BOOL _hasSearchTextChangedSinceLastQuery;
	int _radiusInMeters;
	int _resultsLimit;
	NSString* _searchText;
	NSTimer* _searchTextChangedTimer;
	XXStruct_zYrK5D _locationCoordinate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSTimer* searchTextChangedTimer;
@property(readonly, retain, nonatomic) id<FBGraphPlace> selection;
@property(copy, nonatomic) NSString* searchText;
@property(assign, nonatomic) int resultsLimit;
@property(assign, nonatomic) int radiusInMeters;
@property(assign, nonatomic) XXStruct_zYrK5D locationCoordinate;
+(id)requestForPlacesSearchAtCoordinate:(XXStruct_zYrK5D)coordinate radiusInMeters:(int)meters resultsLimit:(int)limit searchText:(id)text fields:(id)fields datasource:(id)datasource session:(id)session;
+(id)firstRenderLogString;
+(unsigned)graphObjectPagingMode;
+(id)cacheDescriptorWithLocationCoordinate:(XXStruct_zYrK5D)locationCoordinate radiusInMeters:(int)meters searchText:(id)text resultsLimit:(int)limit fieldsForRequest:(id)request;
-(id)graphObjectTableDataSource:(id)source pictureUrlOfItem:(id)item;
-(id)graphObjectTableDataSource:(id)source subtitleOfItem:(id)item;
-(id)graphObjectTableDataSource:(id)source titleOfItem:(id)item;
-(BOOL)graphObjectTableDataSource:(id)source filterIncludesItem:(id)item;
-(void)logAppEvents:(BOOL)events;
-(void)searchTextChangedTimerFired:(id)fired;
-(id)createSearchTextChangedTimer;
-(void)loadDataSkippingRoundTripIfCached:(id)cached;
-(BOOL)delegateIncludesGraphObject:(id)object;
-(void)notifyDelegateOfError:(id)error;
-(void)notifyDelegateSelectionDidChange;
-(void)notifyDelegateDataDidChange;
-(void)loadDataThrottledSkippingRoundTripIfCached:(id)cached;
-(void)configureDataSource:(id)source;
-(void)configureUsingCachedDescriptor:(id)descriptor;
-(void)dealloc;
-(void)initializePlacePicker;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(id)initWithCoder:(id)coder;
@end

