/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class FBURLConnection, NSString, UIImageView, NSDictionary;

@interface FBProfilePictureView : XXUnknownSuperclass {
	NSString* _profileID;
	unsigned _pictureCropping;
	NSDictionary* _currentImageQueryParams;
	FBURLConnection* _connection;
	UIImageView* _imageView;
}
@property(retain, nonatomic) UIImageView* imageView;
@property(retain, nonatomic) FBURLConnection* connection;
@property(copy, nonatomic) NSDictionary* currentImageQueryParams;
@property(assign, nonatomic) unsigned pictureCropping;
@property(copy, nonatomic) NSString* profileID;
-(CGSize)intrinsicContentSize;
-(void)layoutSubviews;
-(void)ensureImageViewContentMode;
-(void)refreshImage:(BOOL)image;
-(void)initialize;
-(id)_placeholderImage;
-(id)_generateQueryParams;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithProfileID:(id)profileID pictureCropping:(unsigned)cropping;
-(id)init;
-(void)dealloc;
@end

