/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSError, FBRequest, NSDictionary;

@interface FBRequestMetadata : XXUnknownSuperclass {
	FBRequest* _request;
	id _completionHandler;
	NSDictionary* _batchParameters;
	unsigned _behavior;
	id _originalCompletionHandler;
	int _retryCount;
	id _originalResult;
	NSError* _originalError;
}
@property(retain, nonatomic) NSError* originalError;
@property(retain, nonatomic) id originalResult;
@property(assign, nonatomic) int retryCount;
@property(copy, nonatomic) id originalCompletionHandler;
@property(assign, nonatomic) unsigned behavior;
@property(copy, nonatomic) NSDictionary* batchParameters;
@property(copy, nonatomic) id completionHandler;
@property(retain, nonatomic) FBRequest* request;
-(id)description;
-(void)invokeCompletionHandlerForConnection:(id)connection withResults:(id)results error:(id)error;
-(void)dealloc;
-(id)initWithRequest:(id)request completionHandler:(id)handler batchParameters:(id)parameters behavior:(unsigned)behavior;
@end

