/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class FBRequestConnection, FBRequestConnectionRetryManagerAlertViewHelper, NSString, NSMutableArray, FBSession;
@protocol FBRequestConnectionRetryManagerDelegate;

@interface FBRequestConnectionRetryManager : XXUnknownSuperclass {
	FBRequestConnection<FBRequestConnectionRetryManagerDelegate>* _requestConnection;
	unsigned _state;
	FBSession* _sessionToReconnect;
	NSString* _alertMessage;
	NSMutableArray* _requestMetadatas;
	FBRequestConnectionRetryManagerAlertViewHelper* _alertViewHelper;
}
@property(retain, nonatomic) FBRequestConnectionRetryManagerAlertViewHelper* alertViewHelper;
@property(retain, nonatomic) NSMutableArray* requestMetadatas;
@property(copy, nonatomic) NSString* alertMessage;
@property(retain, nonatomic) FBSession* sessionToReconnect;
@property(assign, nonatomic) unsigned state;
@property(assign, nonatomic) FBRequestConnection<FBRequestConnectionRetryManagerDelegate>* requestConnection;
-(void)notifyConnectionWillRetryWithConnection:(id)notifyConnection;
-(void)notifyConnectionDidFinishAbortingRetries;
-(void)notifyConnectionDidFinishWithNoRetries;
-(void)dealloc;
-(void)repairFailed;
-(void)repairSuccess;
-(void)performRetries;
-(void)addRequestMetadata:(id)metadata;
-(id)initWithFBRequestConnection:(id)fbrequestConnection;
@end

