/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "headshot-Structs.h"
#import "FBURLConnectionDelegate.h"
#import "FBRequestConnectionRetryManagerDelegate.h"

@class NSHTTPURLResponse, NSError, FBRequestConnectionRetryManager, NSMutableArray, NSMutableURLRequest, FBURLConnection, FBLogger, FBRequest, NSString;
@protocol FBRequestConnectionDelegate;

@interface FBRequestConnection : XXUnknownSuperclass <FBURLConnectionDelegate, FBRequestConnectionRetryManagerDelegate> {
	NSString* _overrideVersionPart;
	BOOL _isResultFromCache;
	NSHTTPURLResponse* _urlResponse;
	unsigned _errorBehavior;
	id<FBRequestConnectionDelegate> _delegate;
	FBURLConnection* _connection;
	NSMutableArray* _requests;
	unsigned _state;
	NSMutableURLRequest* _internalUrlRequest;
	FBRequest* _deprecatedRequest;
	FBLogger* _logger;
	unsigned long _requestStartTime;
	FBRequestConnectionRetryManager* _retryManager;
	NSError* _connectionError;
	double _timeout;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSError* connectionError;
@property(retain, nonatomic) FBRequestConnectionRetryManager* retryManager;
@property(readonly, assign, nonatomic) BOOL isResultFromCache;
@property(assign, nonatomic) unsigned long requestStartTime;
@property(retain, nonatomic) FBLogger* logger;
@property(retain, nonatomic) FBRequest* deprecatedRequest;
@property(retain, nonatomic) NSMutableURLRequest* internalUrlRequest;
@property(assign, nonatomic) double timeout;
@property(assign, nonatomic) unsigned state;
@property(retain, nonatomic) NSMutableArray* requests;
@property(retain, nonatomic) FBURLConnection* connection;
@property(assign, nonatomic) id<FBRequestConnectionDelegate> delegate;
@property(assign, nonatomic) unsigned errorBehavior;
@property(retain, nonatomic) NSHTTPURLResponse* urlResponse;
@property(retain, nonatomic) NSMutableURLRequest* urlRequest;
+(void)addRequestToRefreshPermissionsSession:(id)refreshPermissionsSession connection:(id)connection;
+(void)addRequestToExtendTokenForSession:(id)session connection:(id)connection;
+(BOOL)isPermissionsRequest:(id)request;
+(id)userAgent;
+(void)processGraphObject:(id)object forPath:(id)path withAction:(id)action;
+(void)processGraphObjectPropertyKey:(id)key value:(id)value action:(id)action passByValue:(BOOL)value4;
+(id)startForUploadStagingResourceWithImage:(id)image completionHandler:(id)handler;
+(id)startForUpdateOpenGraphObjectWithId:(id)anId title:(id)title image:(id)image url:(id)url description:(id)description objectProperties:(id)properties completionHandler:(id)handler;
+(id)startForUpdateOpenGraphObject:(id)updateOpenGraphObject completionHandler:(id)handler;
+(id)startForPostOpenGraphObjectWithType:(id)type title:(id)title image:(id)image url:(id)url description:(id)description objectProperties:(id)properties completionHandler:(id)handler;
+(id)startForPostOpenGraphObject:(id)postOpenGraphObject completionHandler:(id)handler;
+(id)startWithGraphPath:(id)graphPath parameters:(id)parameters HTTPMethod:(id)method completionHandler:(id)handler;
+(id)startForPostWithGraphPath:(id)graphPath graphObject:(id)object completionHandler:(id)handler;
+(id)startForDeleteObject:(id)deleteObject completionHandler:(id)handler;
+(id)startWithGraphPath:(id)graphPath completionHandler:(id)handler;
+(id)startForCustomAudienceThirdPartyID:(id)customAudienceThirdPartyID completionHandler:(id)handler;
+(id)startForPlacesSearchAtCoordinate:(XXStruct_zYrK5D)coordinate radiusInMeters:(int)meters resultsLimit:(int)limit searchText:(id)text completionHandler:(id)handler;
+(id)startForPostStatusUpdate:(id)postStatusUpdate place:(id)place tags:(id)tags completionHandler:(id)handler;
+(id)startForPostStatusUpdate:(id)postStatusUpdate completionHandler:(id)handler;
+(id)startForUploadPhoto:(id)uploadPhoto completionHandler:(id)handler;
+(id)startForMyFriendsWithCompletionHandler:(id)completionHandler;
+(id)startForMeWithCompletionHandler:(id)completionHandler;
-(void)retryManager:(id)manager willRetryWithRequestConnection:(id)requestConnection;
-(void)retryManagerDidFinishAbortingRetries:(id)retryManager;
-(void)retryManagerDidFinishWithNoRetries:(id)retryManager;
-(void)facebookURLConnection:(id)connection didSendBodyData:(int)data totalBytesWritten:(int)written totalBytesExpectedToWrite:(int)write;
-(id)getRequestMetadata:(id)metadata;
-(void)addPiggybackRequests;
-(void)registerTokenToOmitFromLog:(id)log;
-(BOOL)isExpiredTokenError:(id)error resultIndex:(unsigned)index;
-(BOOL)isPasswordChangeError:(id)error resultIndex:(unsigned)index;
-(BOOL)isInvalidSessionError:(id)error resultIndex:(unsigned)index;
-(BOOL)isInsufficientPermissionError:(id)error resultIndex:(unsigned)index;
-(id)checkConnectionError:(id)error statusCode:(int)code parsedJSONResponse:(id)response;
-(id)errorWithCode:(int)code statusCode:(int)code2 parsedJSONResponse:(id)response innerError:(id)error message:(id)message;
-(id)errorFromResult:(id)result;
-(void)completeWithResults:(id)results orError:(id)error;
-(void)logDeveloperError:(id)error forRequest:(id)request;
-(BOOL)shouldCloseRequestSession:(id)session;
-(id)unpackIndividualJSONResponseError:(id)error;
-(void)completeDeprecatedWithData:(id)data results:(id)results orError:(id)error;
-(id)parseJSONOrOtherwise:(id)otherwise error:(id*)error;
-(id)parseJSONResponse:(id)response error:(id*)error statusCode:(int)code;
-(void)completeWithResponse:(id)response data:(id)data orError:(id)error;
-(void)appendAttachments:(id)attachments toBody:(id)body addFormData:(BOOL)data logger:(id)logger;
-(BOOL)isAttachment:(id)attachment;
-(void)addRequest:(id)request toBatch:(id)batch attachments:(id)attachments;
-(void)appendJSONRequests:(id)requests toBody:(id)body andNameAttachments:(id)attachments logger:(id)logger;
-(id)accessTokenWithRequest:(id)request;
-(id)getBatchAppID:(id)anId;
-(id)urlStringForSingleRequest:(id)singleRequest forBatch:(BOOL)batch;
-(void)logRequest:(id)request bodyLength:(unsigned)length bodyLogger:(id)logger attachmentLogger:(id)logger4;
-(id)requestWithBatch:(id)batch timeout:(double)timeout;
-(id)newFBURLConnection;
-(void)startURLConnectionWithRequest:(id)request skipRoundTripIfCached:(BOOL)cached completionHandler:(id)handler;
-(void)startWithCacheIdentity:(id)cacheIdentity skipRoundtripIfCached:(BOOL)cached;
-(void)overrideVersionPartWith:(id)with;
-(void)cancel;
-(void)start;
-(void)addRequest:(id)request completionHandler:(id)handler batchParameters:(id)parameters behavior:(unsigned)behavior;
-(void)addRequest:(id)request completionHandler:(id)handler batchParameters:(id)parameters;
-(void)addRequest:(id)request completionHandler:(id)handler batchEntryName:(id)name;
-(void)addRequest:(id)request completionHandler:(id)handler;
-(void)dealloc;
-(id)initWithMetadata:(id)metadata;
-(id)initWithTimeout:(double)timeout;
-(id)init;
@end

