/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData, NSMutableData;

@interface FBRequestBody : XXUnknownSuperclass {
	NSMutableData* _mutableData;
}
@property(readonly, retain, nonatomic) NSMutableData* mutableData;
@property(readonly, retain, nonatomic) NSData* data;
+(id)mimeContentType;
-(void)appendWithKey:(id)key dataValue:(id)value logger:(id)logger;
-(void)appendWithKey:(id)key imageValue:(id)value logger:(id)logger;
-(void)appendWithKey:(id)key formValue:(id)value logger:(id)logger;
-(void)appendRecordBoundary;
-(void)appendUTF8:(id)a8;
-(void)dealloc;
-(id)init;
@end

