/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString, NSURLConnection, NSMutableData, FBSession, NSError;
@protocol FBGraphObject, FBRequestDelegate;

@interface FBRequest : XXUnknownSuperclass {
	id<FBRequestDelegate> _delegate;
	NSString* _url;
	NSString* _versionPart;
	NSURLConnection* _connection;
	NSMutableData* _responseText;
	unsigned _state;
	NSError* _error;
	BOOL _sessionDidExpire;
	id<FBGraphObject> _graphObject;
	BOOL _canCloseSessionOnError;
	BOOL _skipClientToken;
	NSMutableDictionary* _parameters;
	FBSession* _session;
	NSString* _graphPath;
	NSString* _HTTPMethod;
	NSString* _restMethod;
}
@property(copy, nonatomic) NSString* restMethod;
@property(readonly, assign) NSString* versionPart;
@property(assign, nonatomic) BOOL skipClientToken;
@property(assign, nonatomic) BOOL canCloseSessionOnError;
@property(retain, nonatomic) id<FBGraphObject> graphObject;
@property(copy, nonatomic) NSString* HTTPMethod;
@property(copy, nonatomic) NSString* graphPath;
@property(retain, nonatomic) FBSession* session;
@property(readonly, retain, nonatomic) NSMutableDictionary* parameters;
@property(retain, nonatomic) NSError* error;
@property(assign, nonatomic) BOOL sessionDidExpire;
@property(assign, nonatomic) unsigned state;
@property(retain, nonatomic) NSMutableData* responseText;
@property(retain, nonatomic) NSURLConnection* connection;
@property(retain, nonatomic) NSMutableDictionary* params;
@property(copy, nonatomic) NSString* httpMethod;
@property(copy, nonatomic) NSString* url;
@property(assign, nonatomic) id<FBRequestDelegate> delegate;
+(id)requestForUpdateOpenGraphObjectWithId:(id)anId graphObject:(id)object;
+(id)requestForUploadStagingResourceWithImage:(id)image;
+(id)requestForUpdateOpenGraphObjectWithId:(id)anId title:(id)title image:(id)image url:(id)url description:(id)description objectProperties:(id)properties;
+(id)requestForUpdateOpenGraphObject:(id)updateOpenGraphObject;
+(id)requestForPostOpenGraphObjectWithType:(id)type title:(id)title image:(id)image url:(id)url description:(id)description objectProperties:(id)properties;
+(id)requestForPostOpenGraphObject:(id)postOpenGraphObject;
+(id)requestForCustomAudienceThirdPartyID:(id)customAudienceThirdPartyID;
+(id)requestForPlacesSearchAtCoordinate:(XXStruct_zYrK5D)coordinate radiusInMeters:(int)meters resultsLimit:(int)limit searchText:(id)text;
+(id)requestWithGraphPath:(id)graphPath parameters:(id)parameters HTTPMethod:(id)method;
+(id)requestForPostStatusUpdate:(id)postStatusUpdate place:(id)place tags:(id)tags;
+(id)requestForPostStatusUpdate:(id)postStatusUpdate;
+(id)requestForPostWithGraphPath:(id)graphPath graphObject:(id)object;
+(id)requestForDeleteObject:(id)deleteObject;
+(id)requestForGraphPath:(id)graphPath;
+(id)requestForUploadPhoto:(id)uploadPhoto;
+(id)requestForMyFriends;
+(id)requestForMe;
+(id)serializeURL:(id)url params:(id)params httpMethod:(id)method;
+(id)serializeURL:(id)url params:(id)params;
-(id)createRequestConnection;
-(void)overrideVersionPartWith:(id)with;
-(id)startWithCompletionHandler:(id)completionHandler;
-(void)dealloc;
-(id)initWithSession:(id)session graphPath:(id)path parameters:(id)parameters HTTPMethod:(id)method;
-(id)initWithSession:(id)session restMethod:(id)method parameters:(id)parameters HTTPMethod:(id)method4;
-(id)initForPostWithSession:(id)session graphPath:(id)path graphObject:(id)object;
-(id)initWithSession:(id)session graphPath:(id)path;
-(id)init;
-(id)description;
-(BOOL)loading;
@end

