/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface FBSafeCollections : XXUnknownSuperclass {
}
+(id)objectOfKind:(Class)kind forKey:(id)key fromDictionary:(id)dictionary;
+(id)numberForKey:(id)key fromDictionary:(id)dictionary;
+(id)stringForKey:(id)key fromDictionary:(id)dictionary;
+(id)arrayForKey:(id)key fromDictionary:(id)dictionary;
+(id)dictionaryForKey:(id)key fromDictionary:(id)dictionary;
+(id)objectOfKind:(Class)kind atIndex:(unsigned)index fromArray:(id)array;
+(id)numberAtIndex:(unsigned)index fromArray:(id)array;
+(id)stringAtIndex:(unsigned)index fromArray:(id)array;
+(id)arrayAtIndex:(unsigned)index fromArray:(id)array;
+(id)dictionaryAtIndex:(unsigned)index fromArray:(id)array;
@end

