/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSessionLoginStrategy.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface FBSessionInlineWebViewLoginStategy : XXUnknownSuperclass <FBSessionLoginStrategy> {
}
@property(readonly, copy) NSString* methodName;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(BOOL)tryPerformAuthorizeWithParams:(id)params session:(id)session logger:(id)logger;
@end

