/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class FBSession, NSMutableDictionary, NSString;

@interface FBSessionAuthLogger : XXUnknownSuperclass {
	NSString* _ID;
	NSMutableDictionary* _extras;
	FBSession* _session;
	NSString* _authMethod;
}
@property(copy, nonatomic) NSString* authMethod;
@property(assign, nonatomic) FBSession* session;
@property(retain, nonatomic) NSMutableDictionary* extras;
@property(copy, nonatomic) NSString* ID;
-(id)newEventParameters;
-(void)logEndAuthWithResult:(id)result error:(id)error;
-(void)logEndAuthMethodWithResult:(id)result error:(id)error;
-(void)logStartAuthMethod:(id)method;
-(void)logStartAuth;
-(void)logEvent:(id)event result:(id)result error:(id)error;
-(void)logEvent:(id)event params:(id)params;
-(void)addExtrasForNextEvent:(id)nextEvent;
-(void)dealloc;
-(id)initWithSession:(id)session ID:(id)anId authMethod:(id)method;
-(id)initWithSession:(id)session;
@end

