/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSessionTokenCachingStrategy.h"

@class NSString, NSDate;

@interface FBSessionManualTokenCachingStrategy : FBSessionTokenCachingStrategy {
	NSString* _accessToken;
	NSDate* _expirationDate;
}
@property(copy) NSDate* expirationDate;
@property(copy) NSString* accessToken;
-(void)clearToken;
-(id)fetchTokenInformation;
-(void)cacheTokenInformation:(id)information;
-(void)dealloc;
@end

