/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface FBSessionUtility : XXUnknownSuperclass {
}
+(id)audienceNameWithAudience:(unsigned)audience;
+(id)userIDFromSignedRequest:(id)signedRequest;
+(unsigned)loginBehaviorForLoginType:(unsigned)loginType;
+(BOOL)logIfFoundUnexpectedPermissions:(id)permissions isRead:(BOOL)read;
+(void)extractPermissionsFromResponse:(id)response allPermissions:(id)permissions grantedPermissions:(id)permissions3 declinedPermissions:(id)permissions4;
+(void)validateRequestForPermissions:(id)permissions defaultAudience:(unsigned)audience allowSystemAccount:(BOOL)account isRead:(BOOL)read;
+(BOOL)areRequiredPermissions:(id)permissions aSubsetOfPermissions:(id)permissions2;
+(id)expirationDateFromResponseParams:(id)responseParams;
+(void)addWebLoginStartTimeToParams:(id)params;
+(id)sessionStateDescription:(unsigned)description;
+(id)clientStateFromQueryParams:(id)queryParams;
+(id)queryParamsFromLoginURL:(id)loginURL appID:(id)anId urlSchemeSuffix:(id)suffix;
+(BOOL)isOpenSessionResponseURL:(id)url;
@end

