/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface FBSessionAppEventsState : XXUnknownSuperclass {
	BOOL _requestInFlight;
	NSMutableArray* _accumulatedEvents;
	NSMutableArray* _inFlightEvents;
	unsigned _numSkippedEventsDueToFullBuffer;
}
@property(assign) BOOL requestInFlight;
@property(assign) unsigned numSkippedEventsDueToFullBuffer;
@property(retain) NSMutableArray* inFlightEvents;
@property(retain) NSMutableArray* accumulatedEvents;
-(id)jsonEncodeInFlightEvents:(BOOL)flightEvents;
-(BOOL)areAllEventsImplicit;
-(void)clearInFlightAndStats;
-(unsigned)getAccumulatedEventCount;
-(void)addEvent:(id)event isImplicit:(BOOL)implicit;
-(void)dealloc;
-(id)init;
@end

