/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class FBTask;

@interface FBTaskCompletionSource : XXUnknownSuperclass {
	FBTask* _task;
}
@property(retain, nonatomic) FBTask* task;
+(id)taskCompletionSource;
-(BOOL)trySetCancelled;
-(BOOL)trySetException:(id)exception;
-(BOOL)trySetError:(id)error;
-(BOOL)trySetResult:(id)result;
-(void)cancel;
-(void)setException:(id)exception;
-(void)setError:(id)error;
-(void)setResult:(id)result;
-(void)dealloc;
-(id)init;
@end

