/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSException, NSCondition, NSMutableArray, NSObject, NSError;
@protocol NSObject;

@interface FBTask : XXUnknownSuperclass {
	id<NSObject> _result;
	NSError* _error;
	NSException* _exception;
	BOOL _cancelled;
	BOOL _completed;
	NSObject* _lock;
	NSCondition* _condition;
	NSMutableArray* _callbacks;
}
@property(retain, nonatomic) NSMutableArray* callbacks;
@property(assign, nonatomic) BOOL completed;
@property(retain, nonatomic) NSCondition* condition;
@property(retain, nonatomic) NSObject* lock;
+(id)taskWithDelay:(unsigned long long)delay;
+(id)taskDependentOnTasks:(id)tasks;
+(id)cancelledTask;
+(id)taskWithException:(id)exception;
+(id)taskWithError:(id)error;
+(id)taskWithResult:(id)result;
-(id)waitForResult:(id*)result;
-(void)waitUntilFinished;
-(void)warnOperationOnMainThreadNoOp;
-(void)warnOperationOnMainThread;
-(id)completionTaskWithQueue:(id)queue block:(id)block;
-(id)completionTaskWithBlock:(id)block;
-(id)dependentTaskWithBlock:(id)block queue:(id)queue;
-(id)dependentTaskWithBlock:(id)block;
-(void)runContinuations;
-(void)setCompleted;
-(BOOL)isCompleted;
-(BOOL)trySetCancelled;
-(void)cancel;
-(BOOL)isCancelled;
-(BOOL)trySetException:(id)exception;
-(void)setException:(id)exception;
-(id)exception;
-(BOOL)trySetError:(id)error;
-(void)setError:(id)error;
-(id)error;
-(BOOL)trySetResult:(id)result;
-(void)setResult:(id)result;
-(id)result;
-(void)dealloc;
-(id)init;
@end

