/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSession.h"

@class NSString;

@interface FBTestSession : FBSession {
	BOOL _forceAccessTokenRefresh;
	BOOL _disableReauthorize;
	NSString* _appAccessToken;
	NSString* _testUserID;
	NSString* _testUserName;
	NSString* _testAppID;
	NSString* _testAppSecret;
	NSString* _machineUniqueUserTag;
	NSString* _sessionUniqueUserTag;
	unsigned _mode;
	NSString* _testAppClientToken;
}
@property(copy) NSString* testAppClientToken;
@property(assign) BOOL forceAccessTokenRefresh;
@property(assign) unsigned mode;
@property(readonly, copy) NSString* sharedTestUserIdentifier;
@property(readonly, copy) NSString* permissionsString;
@property(copy) NSString* sessionUniqueUserTag;
@property(copy) NSString* machineUniqueUserTag;
@property(assign) BOOL disableReauthorize;
@property(copy) NSString* testAppSecret;
@property(copy) NSString* testAppID;
@property(copy) NSString* testUserName;
@property(copy) NSString* testUserID;
@property(copy) NSString* appAccessToken;
+(void)deleteUnitTestUser:(id)user accessToken:(id)token;
+(id)sessionForUnitTestingWithPermissions:(id)permissions mode:(unsigned)mode sessionUniqueUserTag:(id)tag;
+(id)sessionWithPrivateUserWithPermissions:(id)permissions;
+(id)sessionWithSharedUserWithPermissions:(id)permissions;
+(id)sessionWithSharedUserWithPermissions:(id)permissions uniqueUserTag:(id)tag;
-(BOOL)shouldExtendAccessToken;
-(void)authorizeWithPermissions:(id)permissions behavior:(unsigned)behavior defaultAudience:(unsigned)audience isReauthorize:(BOOL)reauthorize;
-(BOOL)transitionToState:(unsigned)state withAccessTokenData:(id)accessTokenData shouldCache:(BOOL)cache;
-(void)findOrCreateSharedUser;
-(id)validNameStringFromInteger:(unsigned)integer;
-(void)retrieveTestUsersForApp;
-(void)populateTestUsers:(id)users testAccounts:(id)accounts;
-(void)raiseException:(id)exception;
-(void)transitionToOpenWithToken:(id)token;
-(void)createNewTestUser;
-(void)dealloc;
-(id)initWithAppID:(id)appID appSecret:(id)secret clientToken:(id)token machineUniqueUserTag:(id)tag sessionUniqueUserTag:(id)tag5 mode:(unsigned)mode permissions:(id)permissions tokenCachingStrategy:(id)strategy;
@end

