/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBViewController.h"

@class NSBundle, NSArray, UILabel, UIButton, UIImageView, FBProfilePictureView;
@protocol FBGraphUser;

@interface FBUserSettingsViewController : FBViewController {
	BOOL _attemptingLogin;
	NSArray* _permissions;
	NSArray* _readPermissions;
	NSArray* _publishPermissions;
	unsigned _defaultAudience;
	FBProfilePictureView* _profilePicture;
	UIImageView* _backgroundImageView;
	UILabel* _connectedStateLabel;
	id<FBGraphUser> _me;
	UIButton* _loginLogoutButton;
	NSBundle* _bundle;
	id _sessionStateHandler;
	id _requestHandler;
}
@property(copy, nonatomic) id requestHandler;
@property(copy, nonatomic) id sessionStateHandler;
@property(retain, nonatomic) NSBundle* bundle;
@property(assign, nonatomic) BOOL attemptingLogin;
@property(retain, nonatomic) UIButton* loginLogoutButton;
@property(retain, nonatomic) id<FBGraphUser> me;
@property(retain, nonatomic) UILabel* connectedStateLabel;
@property(retain, nonatomic) UIImageView* backgroundImageView;
@property(retain, nonatomic) FBProfilePictureView* profilePicture;
@property(assign, nonatomic) unsigned defaultAudience;
@property(copy, nonatomic) NSArray* publishPermissions;
@property(copy, nonatomic) NSArray* readPermissions;
@property(copy, nonatomic) NSArray* permissions;
-(void)handleActiveSessionStateChanged:(id)changed;
-(void)loginLogoutButtonPressed:(id)pressed;
-(void)openSession:(BOOL)session;
-(void)sessionStateChanged:(id)changed state:(unsigned)state error:(id)error;
-(void)updateControls;
-(void)viewWillAppear:(BOOL)view;
-(BOOL)shouldAutorotate;
-(unsigned)supportedInterfaceOrientations;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidUnload;
-(void)updateBackgroundImage;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(id)initWithCoder:(id)coder;
-(id)init;
-(void)initializeBlocks;
@end

