/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface FBUtility : XXUnknownSuperclass {
}
+(void)deleteFacebookCookies;
+(BOOL)isSystemAccountStoreAvailable;
+(BOOL)isRunningOnOrAfter:(int)after;
+(BOOL)isUIKitLinkedOnOrAfter:(int)after;
+(BOOL)isMultitaskingSupported;
+(BOOL)isRetinaDisplay;
+(BOOL)isRegisteredURLScheme:(id)scheme;
+(id)dialogBaseURL;
+(id)buildFacebookUrlWithPre:(id)pre post:(id)post version:(id)version;
+(id)buildFacebookUrlWithPre:(id)pre withPost:(id)post;
+(id)buildFacebookUrlWithPre:(id)pre;
+(id)stringAppBaseUrlFromAppId:(id)appId urlSchemeSuffix:(id)suffix;
+(id)stringByURLEncodingString:(id)string;
+(id)stringByURLDecodingString:(id)string;
+(id)stringBySerializingQueryParameters:(id)parameters;
+(id)dictionaryByParsingURLQueryPart:(id)part;
+(id)queryParamsDictionaryFromFBURL:(id)fburl;
+(id)simpleJSONDecode:(id)decode error:(id*)error;
+(id)simpleJSONDecode:(id)decode;
+(id)simpleJSONEncode:(id)encode error:(id*)error writingOptions:(unsigned)options;
+(id)simpleJSONEncode:(id)encode;
+(id)activityParametersDictionaryForEvent:(id)event includeAttributionID:(BOOL)anId implicitEventsOnly:(BOOL)only shouldAccessAdvertisingID:(BOOL)anId4;
+(unsigned)advertisingTrackingStatus;
+(id)retrievePersistedAnonymousID;
+(void)persistAnonymousID:(id)anId;
+(id)advertiserOrAnonymousID:(BOOL)anId;
+(id)attributionID;
+(id)newUUIDString;
+(void)callTheFetchAppSettingsCallback:(id)callback;
+(BOOL)isFetchedFBAppSettingsStale;
+(id)fetchedAppSettings;
+(id)_parseDialogConfigs:(id)configs;
+(void)fetchAppSettings:(id)settings callback:(id)callback;
+(void)addBasicInfoPermission:(id)permission;
+(BOOL)areAllPermissionsReadPermissions:(id)permissions;
+(BOOL)isPublishPermission:(id)permission;
+(BOOL)isSafariBundleIdentifier:(id)identifier;
+(BOOL)isFacebookBundleIdentifier:(id)identifier;
+(id)facebookSDKBundle;
+(id)localizedStringForKey:(id)key withDefault:(id)aDefault inBundle:(id)bundle;
+(id)localizedStringForKey:(id)key withDefault:(id)aDefault;
+(id)expirationDateFromExpirationTimeIntervalString:(id)expirationTimeIntervalString;
+(id)expirationDateFromExpirationUnixTimeString:(id)expirationUnixTimeString;
+(double)randomTimeInterval:(double)interval withMaxValue:(double)maxValue;
+(unsigned long)currentTimeInMilliseconds;
+(void)centerView:(id)view tableView:(id)view2;
+(id)stringFBIDFromObject:(id)object;
+(id)graphObjectInArray:(id)array withSameIDAs:(id)sameIDAs;
@end

