/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIBarButtonItem, UINavigationBar, UIView;
@protocol FBViewControllerDelegate;

@interface FBViewController : XXUnknownSuperclass {
	BOOL _autoDismiss;
	BOOL _dismissAnimated;
	UIBarButtonItem* _cancelButton;
	UIBarButtonItem* _doneButton;
	id<FBViewControllerDelegate> _delegate;
	UIView* _canvasView;
	UINavigationBar* _navigationBar;
	id _handler;
}
@property(assign, nonatomic) BOOL dismissAnimated;
@property(assign, nonatomic) BOOL autoDismiss;
@property(copy, nonatomic) id handler;
@property(retain, nonatomic) UINavigationBar* navigationBar;
@property(retain, nonatomic) UIView* canvasView;
@property(assign, nonatomic) id<FBViewControllerDelegate> delegate;
@property(retain, nonatomic) UIBarButtonItem* doneButton;
@property(retain, nonatomic) UIBarButtonItem* cancelButton;
-(void)logAppEvents:(BOOL)events;
-(void)doneButtonPressed:(id)pressed;
-(void)cancelButtonPressed:(id)pressed;
-(void)setTitle:(id)title;
-(void)updateBarForNavigationMode;
-(void)updateBarForPresentedMode;
-(void)updateBar;
-(CGRect)contentBounds;
-(void)presentModallyFromViewController:(id)viewController animated:(BOOL)animated handler:(id)handler;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(id)initWithCoder:(id)coder;
-(id)init;
-(void)commonInit;
@end

