/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSHashTable, FBSession, NSString;

@interface FBViewImpressionTracker : XXUnknownSuperclass {
	NSHashTable* _trackedImpressions;
	NSString* _eventName;
	FBSession* _session;
}
@property(retain, nonatomic) FBSession* session;
@property(readonly, copy, nonatomic) NSString* eventName;
+(id)impressionTrackerWithEventName:(id)eventName;
-(void)_applicationDidEnterBackgroundNotification:(id)_application;
-(void)logImpressionWithView:(id)view identifier:(id)identifier parameters:(id)parameters;
-(void)dealloc;
-(id)initWithEventName:(id)eventName;
@end

