/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FBWebDialogsDelegate <NSObject>
@optional
-(void)webDialogsWillDismissDialog:(id)webDialogs parameters:(id)parameters session:(id)session result:(unsigned*)result url:(id*)url error:(id*)error;
-(BOOL)webDialogsDialog:(id)dialog parameters:(id)parameters session:(id)session shouldAutoHandleURL:(id)url;
-(void)webDialogsWillPresentDialog:(id)webDialogs parameters:(id)parameters session:(id)session;
@end

