/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBDialogDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDictionary, FBDialog, FBSession;
@protocol FBWebDialogsDelegate;

@interface FBWebDialogInternalDelegate : XXUnknownSuperclass <FBDialogDelegate> {
	BOOL _isSelfRetained;
	id _handler;
	FBDialog* _dialog;
	NSString* _dialogMethod;
	NSDictionary* _parameters;
	FBSession* _session;
	id<FBWebDialogsDelegate> _delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) id<FBWebDialogsDelegate> delegate;
@property(retain, nonatomic) FBSession* session;
@property(copy, nonatomic) NSDictionary* parameters;
@property(copy, nonatomic) NSString* dialogMethod;
@property(retain, nonatomic) FBDialog* dialog;
@property(copy, nonatomic) id handler;
-(void)dialog:(id)dialog didFailWithError:(id)error;
-(void)dialogDidNotComplete:(id)dialog;
-(void)dialogDidComplete:(id)dialog;
-(void)dialogDidNotCompleteWithUrl:(id)dialog;
-(void)dialogCompleteWithUrl:(id)url;
-(BOOL)dialog:(id)dialog shouldOpenURLInExternalBrowser:(id)externalBrowser;
-(void)completeWithResult:(unsigned)result url:(id)url error:(id)error;
-(void)releaseSelfIfNeeded;
-(void)goRetainYourself;
-(void)dealloc;
-(id)init;
@end

