/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIAlertViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol HelpshiftDelegate;

@interface Helpshift : XXUnknownSuperclass <UIAlertViewDelegate> {
	id<HelpshiftDelegate> delegate;
}
@property(retain, nonatomic) id<HelpshiftDelegate> delegate;
+(void)setMetadataDictionary:(id)dictionary;
+(void)setMetadataBlock:(id)block;
+(BOOL)hasApplicationUpdatedCheckOnce;
+(BOOL)hasApplicationUpdated;
+(void)leaveBreadCrumb:(id)crumb;
+(void)reachabilityChangedNotification:(id)notification;
+(void)handleBecomeActiveNotification;
+(void)handleEnterBackgroundNotification;
+(void)removeLocalNotificationsForIssue:(id)issue;
+(void)addLocalNotification:(id)notification forIssue:(id)issue;
+(void)remoteNotificationRecievedInForeground:(id)foreground;
+(void)processRemoteNotifications:(id)notifications;
+(void)displayInAppNotification:(id)appNotification;
+(void)addRemoteNotification:(id)notification forIssue:(id)issue;
+(id)removeRemoteNotificationsForIssue:(id)issue;
+(int)getRemoteNotificationCountForIssue:(id)issue;
+(void)setUseremail:(id)useremail;
+(void)setUsername:(id)username;
+(void)installForAppID:(id)appID domainName:(id)name apiKey:(id)key withOptions:(id)options;
+(void)installForAppID:(id)appID domainName:(id)name apiKey:(id)key;
+(void)showAlertToRateAppWithURL:(id)url withCompletionBlock:(id)completionBlock;
+(void)installForApiKey:(id)apiKey domainName:(id)name appID:(id)anId;
+(void)installForApiKey:(id)apiKey domainName:(id)name appID:(id)anId withOptions:(id)options;
+(void)pauseDisplayOfInAppNotification:(BOOL)appNotification;
+(void)setName:(id)name andEmail:(id)email;
+(void)setUserIdentifier:(id)identifier;
+(id)sharedInstance;
-(void)closeHelpshiftSessionFromViewController:(id)viewController isAnimated:(BOOL)animated;
-(void)closeHelpshiftSession;
-(id)topViewController:(id)controller;
-(void)showChatOnNotificationForIssue:(id)issue withController:(id)controller;
-(void)handleLocalNotification:(id)notification withController:(id)controller;
-(void)showDelayedChatInHandleRemoteNotification:(id)handleRemoteNotification;
-(void)handleRemoteNotification:(id)notification withController:(id)controller;
-(void)registerDeviceToken:(id)token;
-(BOOL)hasRegisteredForPush;
-(int)checkNotificationStatus;
-(void)registerIdentifier:(id)identifier forPartner:(id)partner;
-(void)clearBreadCrumbs;
-(void)clearUserData;
-(void)sendFeedback;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)alertReviewRequest;
-(void)notificationPollFailed;
-(void)notificationPollSucceeded:(id)succeeded;
-(BOOL)isShowingNotification;
-(id)bundleIssueUpdates:(id)updates;
-(void)triggerNotificationPolling;
-(void)updatePoller:(id)poller;
-(float)calculateNotificationInterval:(float)interval;
-(int)getNotificationCountFromRemote:(BOOL)remote;
-(void)handleNotification:(id)notification withController:(id)controller;
-(int)notificationCountAsync:(BOOL)async;
-(void)showInbox:(id)inbox;
-(void)showFAQ:(id)faq withController:(id)controller;
-(void)showFAQSection:(id)section withController:(id)controller;
-(void)reportIssue:(id)issue withOptions:(id)options;
-(void)reportIssue:(id)issue;
-(void)showFAQs:(id)faqs;
-(void)showSupport:(id)support;
-(void)showSupport:(id)support withOptions:(id)options;
-(void)launchConversation:(id)conversation;
-(void)launchMainScreenFromViewController:(id)viewController;
-(void)showSingleFAQ:(id)faq withController:(id)controller withOptions:(id)options;
-(void)showFAQSection:(id)section withController:(id)controller withOptions:(id)options;
-(void)showConversation:(id)conversation withOptions:(id)options;
-(void)showFAQs:(id)faqs withOptions:(id)options;
-(void)readOptionsDictionary:(id)dictionary;
-(void)initExtras;
-(void)initSupportUIWithViewController:(id)viewController isDecomposed:(BOOL)decomposed;
-(BOOL)initCrittercismSupport;
@end

