/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSAnalyzer : XXUnknownSuperclass {
}
+(id)analyzeFAQ:(id)faq;
+(id)countTermWithTypesFrequencies:(id)typesFrequencies;
+(unsigned)getBoost:(id)boost type:(id)type;
@end

