/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSIssueModelDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface HSBaseViewController : XXUnknownSuperclass <HSIssueModelDelegate> {
	int viewControllerType;
	NSString* _convPrefillText;
}
@property(assign, nonatomic) int viewControllerType;
@property(copy, nonatomic) NSString* convPrefillText;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)issueArrayUpdationFailure;
-(void)issueArrayUpdated;
-(id)getUILabelForFAQsStatus;
-(id)getUILabelForTableViewCell;
-(void)launchConversation:(id)conversation;
-(void)addRightConvButton;
-(void)loadView;
@end

