/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSBase64 : XXUnknownSuperclass {
}
+(id)base64forData:(id)data;
+(id)decodeBase64WithString:(id)string;
-(id)init;
@end

