/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableString, NSDictionary;

@interface HSConstantsManager : XXUnknownSuperclass {
	float TABLE_HEIGHT;
	float ANIMATION_DURATION;
	float VIEW_Y_FRAME;
	float HALF_HEIGHT;
	float COMPLETE_HEIGHT;
	float COMPLETE_WIDTH;
	float STANDARD_HEIGHT;
	float TEXT_EDIT_HEIGHT;
	float HEADER_HEIGHT;
	float STATUS_BAR_HEIGHT;
	CGRect FAQ_CELL_INITIAL_FRAME;
	CGRect FAQ_CELL_FINAL_FRAME;
	CGRect REPORT_AN_ISSUE_FRAME;
	CGRect MY_ISSUES_FRAME;
	CGRect FAQ_VIEW_FRAME;
	CGRect ISSUE_VIEW_FRAME;
	CGRect REPORT_ISSUE_VIEW_FRAME;
	CGRect FAQ_LIST_VIEW_FRAME;
	CGRect SINGLE_FAQ_VIEW_FRAME;
	CGRect SINGLE_FAQ_VIEW_TABLE_FRAME;
	CGRect CENTER_TITLE_LABEL_FRAME;
	CGRect CHAT_TITLE_LABEL_FRAME;
	CGRect PROMPT_USERNAME_VIEW_FRAME;
	CGRect REPORT_ISSUE_VIEW_HEADER_FRAME;
	CGRect REPORT_ISSUE_SUBMIT_FRAME;
	CGRect CHAT_VIEW_FRAME;
	CGRect CHAT_HEADER_FRAME;
	CGRect SEARCH_BAR_FRAME;
	CGRect CLOSE_BUTTON_LINE_FRAME;
	CGRect CLOSE_BUTTON_LINE_LEFT_FRAME;
	CGRect CLOSE_BUTTON_FRAME;
	CGRect STANDARD_RECESSED;
	CGRect COMPLETE_RECESSED;
	CGRect COMPLETE_FRAME;
	CGRect STANDARD_FRAME;
	CGRect NEXT_BUTTON_FRAME;
	CGRect BADGE_COUNT_FRAME;
	CGRect MAIN_VIEW_TABLE_FRAME;
	CGRect REPORT_ISSUE_TABLE_FRAME;
	BOOL isPortrait;
	int iOS6InterfaceOrientation;
	unsigned iOS6InterfaceOrientationMask;
	NSDictionary* deviceMakeDictionary;
	NSMutableString* userAgent;
	BOOL isUIDecomposed;
	BOOL isStatusBarHidden;
}
@property(assign, nonatomic) BOOL isStatusBarHidden;
@property(assign, nonatomic) BOOL isUIDecomposed;
@property(retain, nonatomic) NSMutableString* userAgent;
@property(retain, nonatomic) NSDictionary* deviceMakeDictionary;
@property(assign, nonatomic) unsigned iOS6InterfaceOrientationMask;
@property(assign, nonatomic) int iOS6InterfaceOrientation;
@property(assign, nonatomic) BOOL isPortrait;
@property(assign, nonatomic) CGRect REPORT_ISSUE_TABLE_FRAME;
@property(assign, nonatomic) CGRect MAIN_VIEW_TABLE_FRAME;
@property(assign, nonatomic) CGRect BADGE_COUNT_FRAME;
@property(assign, nonatomic) CGRect NEXT_BUTTON_FRAME;
@property(assign, nonatomic) CGRect STANDARD_FRAME;
@property(assign, nonatomic) CGRect COMPLETE_FRAME;
@property(assign, nonatomic) CGRect COMPLETE_RECESSED;
@property(assign, nonatomic) CGRect STANDARD_RECESSED;
@property(assign, nonatomic) CGRect CLOSE_BUTTON_FRAME;
@property(assign, nonatomic) CGRect CLOSE_BUTTON_LINE_LEFT_FRAME;
@property(assign, nonatomic) CGRect CLOSE_BUTTON_LINE_FRAME;
@property(assign, nonatomic) CGRect SEARCH_BAR_FRAME;
@property(assign, nonatomic) CGRect CHAT_HEADER_FRAME;
@property(assign, nonatomic) CGRect CHAT_VIEW_FRAME;
@property(assign, nonatomic) CGRect REPORT_ISSUE_SUBMIT_FRAME;
@property(assign, nonatomic) CGRect REPORT_ISSUE_VIEW_HEADER_FRAME;
@property(assign, nonatomic) CGRect PROMPT_USERNAME_VIEW_FRAME;
@property(assign, nonatomic) CGRect CHAT_TITLE_LABEL_FRAME;
@property(assign, nonatomic) CGRect CENTER_TITLE_LABEL_FRAME;
@property(assign, nonatomic) CGRect SINGLE_FAQ_VIEW_TABLE_FRAME;
@property(assign, nonatomic) CGRect SINGLE_FAQ_VIEW_FRAME;
@property(assign, nonatomic) CGRect FAQ_LIST_VIEW_FRAME;
@property(assign, nonatomic) CGRect REPORT_ISSUE_VIEW_FRAME;
@property(assign, nonatomic) CGRect ISSUE_VIEW_FRAME;
@property(assign, nonatomic) CGRect FAQ_VIEW_FRAME;
@property(assign, nonatomic) CGRect MY_ISSUES_FRAME;
@property(assign, nonatomic) CGRect REPORT_AN_ISSUE_FRAME;
@property(assign, nonatomic) CGRect FAQ_CELL_FINAL_FRAME;
@property(assign, nonatomic) CGRect FAQ_CELL_INITIAL_FRAME;
@property(assign, nonatomic) float STATUS_BAR_HEIGHT;
@property(assign, nonatomic) float COMPLETE_WIDTH;
@property(assign, nonatomic) float HEADER_HEIGHT;
@property(assign, nonatomic) float TEXT_EDIT_HEIGHT;
@property(assign, nonatomic) float COMPLETE_HEIGHT;
@property(assign, nonatomic) float STANDARD_HEIGHT;
@property(assign, nonatomic) float HALF_HEIGHT;
@property(assign, nonatomic) float VIEW_Y_FRAME;
@property(assign, nonatomic) float ANIMATION_DURATION;
@property(assign, nonatomic) float TABLE_HEIGHT;
+(id)sharedInstance;
-(void)initializeUIInterfaceOrientation;
-(void)initializeUIInterfaceOrientationMask;
-(void)initConstantForIPad;
-(void)initConstantSetPortraitForIphone4InchWithFullScreenOn:(BOOL)fullScreenOn;
-(void)initConstantSetPortraitForIphone3InchWithFullScreenOn:(BOOL)fullScreenOn;
-(void)initConstantSetLandscapeWithCompleteWidth:(float)completeWidth;
-(void)initConstantSetPortraitWithCompleteWidth:(float)completeWidth completeHeight:(float)height yFrame:(float)frame;
-(id)init;
@end

