/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSCoreAPICalls : XXUnknownSuperclass {
}
+(BOOL)adjustTimestampWithResponse:(id)response;
+(id)generateRequestFromURI:(id)uri withMethod:(id)method withApiData:(id)apiData;
+(id)generateHttpBodyForPostRequestWithSortedDictionary:(id)sortedDictionary apiData:(id)data andSignature:(id)signature;
+(id)generateQueryStringForGetRequestWithSortedDictionary:(id)sortedDictionary apiData:(id)data andSignature:(id)signature;
+(void)putApiData:(id)data inSortedDictionary:(id)sortedDictionary;
+(id)makeHSApiCallToURI:(id)uri method:(id)method data:(id)data response:(id*)response error:(id*)error;
@end

