/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary;

@interface HSConfigPlist : XXUnknownSuperclass {
	NSDictionary* pListDict;
	NSDictionary* _styleSheet;
}
@property(retain, nonatomic) NSDictionary* styleSheet;
-(id)getSpinnerView;
-(id)getStatusUpToDateView;
-(id)getAccessoryView;
-(void)applyStyleForView:(id)view;
-(void)setChatAckTextColor:(id)color;
-(void)setGlobalBoldFontIfAvailable:(id)available size:(float)size;
-(void)setGlobalFontIfAvailable:(id)available size:(float)size;
-(void)applyStyleForConvResolutionButton:(id)convResolutionButton withProperty:(int)property;
-(void)applyGlobalTextColorForLabel:(id)label withAlpha:(float)alpha;
-(void)applyStyleForCSATLabel:(id)csatlabel;
-(void)applyStyleForRatingStarButton:(id)ratingStarButton;
-(void)applyStyleForBarButtonItem:(id)barButtonItem;
-(void)applyStyleForBadgeView:(id)badgeView;
-(void)applyStyleForChatReplyBar:(id)chatReplyBar andTextView:(id)view;
-(void)applyStyleForNavigationBar:(id)navigationBar;
-(void)applyStyleForFAQsStatus:(id)faqsStatus forLabel:(id)label;
-(void)applyStyleForTableViewCell:(id)tableViewCell forLabel:(id)label;
-(void)applyStyleForTableViewCell:(id)tableViewCell;
-(void)applyBackgroundViewForTableView:(id)tableView;
-(void)applyStyleForTableView:(id)tableView;
-(void)applyStyleForSearchBar:(id)searchBar;
-(void)loadStylesheet;
-(id)getStyleDictByUIElement:(int)element;
-(id)getStyleByUIElement:(int)element property:(int)property;
-(id)getValue:(int)value property:(int)property;
-(id)getStyleValue:(int)value property:(int)property;
-(id)init;
@end

