/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class HSConfigPlist, UIColor, NSString, UIImage;

@interface HSConfigController : XXUnknownSuperclass {
	int breadCrumbLimit;
	int debugLogLimit;
	BOOL helpshiftLogo;
	BOOL fullscreenOn;
	UIColor* txtColor;
	UIColor* startColor;
	UIColor* endColor;
	NSString* reviewUrl;
	int reviewInterval;
	int reviewIntervalType;
	NSString* supportTitle;
	HSConfigPlist* _pListConfig;
	BOOL gotoConversationAfterContactUs;
	BOOL enableInAppNotification;
	BOOL profileFormEnabled;
	BOOL disableInAppConversation;
	BOOL requireNameAndEmail;
	BOOL presentFullScreenOniPad;
	BOOL pauseDisplayOfInAppNotification;
	BOOL isSDKSessionActive;
	NSString* preFillText;
	BOOL isCSATEnabled;
	int ticketAvoidanceOption;
	BOOL showThanksAlert;
	UIImage* backbuttonImage;
	UIImage* sendButtonImage;
	UIImage* chatButtonImage;
	id completionBlock;
}
@property(copy, nonatomic) id completionBlock;
@property(assign, nonatomic) int ticketAvoidanceOption;
@property(assign, nonatomic) BOOL isCSATEnabled;
@property(retain, nonatomic) NSString* preFillText;
@property(assign, nonatomic) BOOL isSDKSessionActive;
@property(assign, nonatomic) BOOL pauseDisplayOfInAppNotification;
@property(assign, nonatomic) BOOL presentFullScreenOniPad;
@property(assign, nonatomic) BOOL requireNameAndEmail;
@property(assign, nonatomic) BOOL disableInAppConversation;
@property(assign, nonatomic) BOOL profileFormEnabled;
@property(assign, nonatomic) BOOL enableInAppNotification;
@property(assign, nonatomic) BOOL showThanksAlert;
@property(assign, nonatomic) BOOL gotoConversationAfterContactUs;
@property(retain, nonatomic) HSConfigPlist* pListConfig;
@property(retain, nonatomic) UIImage* chatButtonImage;
@property(retain, nonatomic) UIImage* sendButtonImage;
@property(retain, nonatomic) UIImage* backButtonImage;
@property(retain, nonatomic) NSString* supportTitle;
@property(assign, nonatomic) int reviewIntervalType;
@property(assign, nonatomic) int reviewInterval;
@property(retain, nonatomic) NSString* reviewUrl;
@property(retain, nonatomic) UIColor* endColor;
@property(retain, nonatomic) UIColor* startColor;
@property(retain, nonatomic) UIColor* txtColor;
@property(assign, nonatomic) BOOL fullscreenOn;
@property(assign, nonatomic) BOOL helpshiftLogo;
@property(assign, nonatomic) int debugLogLimit;
@property(assign, nonatomic) int breadCrumbLimit;
+(id)sharedInstance;
-(BOOL)getPersistentHideNameEmail;
-(void)persistHideNameEmailWithBool:(BOOL)aBool;
-(void)resetPreFillText;
-(BOOL)getPersistentRequireEmail;
-(void)persistRequireEmailWithBool:(BOOL)aBool;
-(BOOL)isEmailUIRequired;
-(BOOL)isUserInfoUIRequired;
-(BOOL)isUserInfoRequired;
-(BOOL)getTicketAvoidanceOptionForLocation:(int)location;
-(void)readLocalConfig;
-(void)updateConfigFromDictionary:(id)dictionary;
-(BOOL)fetchConfig;
-(void)dealloc;
-(id)init;
@end

