/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSColorUtils : XXUnknownSuperclass {
}
+(id)colorWithAlpha:(id)alpha alpha:(float)alpha2;
+(id)darkerColorForColor:(id)color incBy:(float)by;
+(id)colorWithHexString:(id)hexString;
@end

