/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "UITextViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, HSPlaceHolderTextView, NSString;

@interface HSCSATViewController : XXUnknownSuperclass <UITextViewDelegate> {
	int rating;
	NSString* convID;
	BOOL didSendCSATRating;
	HSPlaceHolderTextView* descTextView;
	UIView* ratingInfoView;
}
@property(retain, nonatomic) UIView* ratingInfoView;
@property(retain, nonatomic) HSPlaceHolderTextView* descTextView;
@property(retain, nonatomic) NSString* convID;
@property(assign, nonatomic) int rating;
+(unsigned)animationOptionsForCurve:(int)curve;
-(void)dealloc;
-(void)sendButtonAction;
-(BOOL)prefersStatusBarHidden;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)resizeView:(id)view;
-(void)handleKeyboardWillHide:(id)handleKeyboard;
-(void)handleKeyboardWillShow:(id)handleKeyboard;
-(BOOL)textView:(id)view shouldChangeTextInRange:(NSRange)range replacementText:(id)text;
-(void)didReceiveMemoryWarning;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)loadView;
@end

