/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSDBThing : XXUnknownSuperclass {
}
+(id)getUnreadIssuesFromDB;
+(id)getIssueFromDBForIssueID:(id)issueID;
+(id)getCursorsFromDB;
+(id)getAllIssuesFromDB;
+(id)getIssuesFromDB;
+(void)updateMessageForMessageID:(id)messageID forIssueID:(id)issueID withMessage:(id)message;
+(void)deleteMessageForMessageID:(id)messageID;
+(id)getMessageForMessageID:(id)messageID forIssueID:(id)issueID;
+(id)getMessagesArrayForIssueID:(id)issueID;
+(void)removeHSDBThing:(int)thing;
+(id)retrieveHSThingForKey:(id)key;
+(BOOL)addHSThingData:(id)data key:(id)key value:(id)value;
+(BOOL)addHSThing:(id)thing rendercontent:(id)rendercontent forType:(int)type withSortKey:(id)sortKey;
+(BOOL)hsThingDataExists:(id)exists forKey:(id)key;
+(BOOL)hsThingExists:(id)exists;
@end

