/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UINavigationController, UIViewController, NSString;

@interface HSDispatchQueues : XXUnknownSuperclass {
	BOOL chatRefreshPolling;
	BOOL issueRefreshPolling;
	BOOL issueNotificationPolling;
	BOOL showingChatOnNotification;
	NSString* selectedIssueID;
	UIViewController* currentChatScreen;
	UINavigationController* currentNavigationController;
}
@property(retain, nonatomic) UINavigationController* currentNavigationController;
@property(retain, nonatomic) UIViewController* currentChatScreen;
@property(retain, nonatomic) NSString* selectedIssueID;
@property(assign, nonatomic) BOOL showingChatOnNotification;
@property(assign, nonatomic) BOOL issueNotificationPolling;
@property(assign, nonatomic) BOOL issueRefreshPolling;
@property(assign, nonatomic) BOOL chatRefreshPolling;
+(id)sharedInstance;
-(void)getNotificationUpdatesForPoll:(BOOL)poll;
-(id)init;
@end

