/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSFailedQueues : XXUnknownSuperclass {
	BOOL isRunning;
}
@property(assign, nonatomic) BOOL isRunning;
+(id)sharedInstance;
-(void)handleResponse:(id)response forRoute:(id)route;
-(void)makeCall;
-(void)saveFailedQueue:(id)queue;
-(id)getFailedQueue;
-(void)addApiDataToQueue:(id)queue forRoute:(id)route forMethod:(id)method forResponseCode:(int)responseCode withResponseStatusCode:(int)responseStatusCode;
-(BOOL)isStatusCodeRetriable:(int)retriable;
@end

