/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary;
@protocol HSSearchModelDelegate;

@interface HSFaqModel : XXUnknownSuperclass {
	NSDictionary* tfIdfIndex;
	BOOL isFetchingFaqs;
	id<HSSearchModelDelegate> searchDelegate;
}
@property(retain, nonatomic) id<HSSearchModelDelegate> searchDelegate;
@property(assign, nonatomic) BOOL isFetchingFaqs;
@property(retain, nonatomic) NSDictionary* tfIdfIndex;
+(void)markUnHelpful:(id)helpful;
+(void)markHelpful:(id)helpful;
+(void)clearFaqModel;
+(void)clearOlderFaqModel;
+(void)getFaq:(id)faq OnSuccess:(id)success onFailure:(id)failure;
+(int)getSectionsCount;
+(int)getFaqCountForSection:(id)section;
+(void)getSection:(id)section OnSuccess:(id)success onFailure:(id)failure;
+(id)getSection:(id)section;
+(id)getFaqForId:(id)anId;
+(id)getFaq:(id)faq;
+(id)getFaqTitlesForSection:(id)section;
+(id)getFaqsForSection:(id)section;
+(id)getSections;
+(void)getSectionsOnSuccess:(id)success onFailure:(id)failure;
+(id)getFaqArray;
+(id)sharedInstance;
-(void)createIndexesForFaqArray:(id)faqArray;
-(void)getAndStoreFaq:(id)faq OnSuccess:(id)success onFailure:(id)failure;
-(void)getAndStoreSectionsOnSuccess:(id)success onFailure:(id)failure;
-(void)markFaqHelpfulForFaqId:(id)faqId helpful:(BOOL)helpful onSuccess:(id)success onFailure:(id)failure;
-(id)getFaqIndex;
-(void)dealloc;
-(id)init;
@end

