/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "HSBaseViewController.h"
#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "HSSearchModelDelegate.h"

@class NSMutableArray, UIView, UITableView, HSSearchDisplayController, NSDictionary, UISearchBar, HSMBProgressHUD, NSString;

@interface HSFAQListScreen : HSBaseViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, UISearchDisplayDelegate, HSSearchModelDelegate> {
	UITableView* tableList;
	NSDictionary* _section;
	NSString* _faqSectionPublishID;
	HSMBProgressHUD* loadingScreen;
	UIView* header;
	HSSearchDisplayController* searchDisplayController;
	UISearchBar* searchBar;
	NSMutableArray* _filteredListContent;
	NSMutableArray* _filteredListIDs;
	NSString* faqSectionPublishID;
}
@property(retain, nonatomic) NSMutableArray* filteredListIDs;
@property(retain, nonatomic) NSMutableArray* filteredListContent;
@property(retain, nonatomic) NSDictionary* section;
@property(retain, nonatomic) HSMBProgressHUD* loadingScreen;
@property(retain, nonatomic) NSString* faqSectionPublishID;
@property(retain, nonatomic) UITableView* tableList;
-(BOOL)prefersStatusBarHidden;
-(void)searchIndexesUpdated;
-(void)filterContentForSearchText:(id)searchText;
-(void)searchBarSearchButtonClicked:(id)clicked;
-(void)searchBarCancelButtonClicked:(id)clicked;
-(void)searchBarTextDidBeginEditing:(id)searchBarText;
-(void)searchBarTextDidEndEditing:(id)searchBarText;
-(void)searchDisplayControllerDidEndSearch:(id)searchDisplayController;
-(BOOL)searchDisplayController:(id)controller shouldReloadTableForSearchScope:(int)searchScope;
-(BOOL)searchDisplayController:(id)controller shouldReloadTableForSearchString:(id)searchString;
-(void)searchDisplayController:(id)controller didLoadSearchResultsTableView:(id)view;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(CGSize)computeExpectedLabelSize:(id)size forFont:(id)font andWidth:(float)width;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)hideLoadingScreen;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidUnload;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)goBack;
-(void)launchConvFromSearch:(id)search;
-(id)getNoResultsFooterView;
-(id)getReportIssueFooterView;
-(void)loadView;
-(void)didMoveToParentViewController:(id)parentViewController;
-(void)dealloc;
-(id)init;
@end

