/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSFaqDb : XXUnknownSuperclass {
}
+(void)clearData;
+(BOOL)updateFaq:(id)faq withIsHelpful:(int)isHelpful;
+(id)getFaqIsHelpfulForId:(id)anId;
+(id)getFaqForId:(id)anId;
+(id)getFaqIdForPublishId:(id)publishId;
+(id)getFaq:(id)faq;
+(id)getAllFaqs;
+(id)getFaqTitlesForSection:(id)section;
+(id)getFaqsForSection:(id)section;
+(void)updateFaq:(id)faq;
+(void)storeFaq:(id)faq forSection:(id)section;
+(void)storeFaqs:(id)faqs forSection:(id)section;
+(id)doesExist:(id)exist;
+(id)getStringFromColumnBlob:(const void*)columnBlob withSize:(int)size;
+(id)getColumns:(id)columns;
@end

