/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSFaqAPICalls : XXUnknownSuperclass {
}
+(id)sharedInstance;
-(void)fetchFaqWithId:(id)anId OnSuccess:(id)success onFailure:(id)failure;
-(void)fetchSectionsOnSuccess:(id)success onFailure:(id)failure;
-(BOOL)markFaqHelpfulForFaqId:(id)faqId helpful:(BOOL)helpful onSuccess:(id)success onFailure:(id)failure;
-(void)dealloc;
-(id)init;
@end

