/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

@interface HSFunnelModel : XXUnknownSuperclass {
	NSArray* funnelEvents;
}
@property(retain, nonatomic) NSArray* funnelEvents;
+(void)clearSession;
+(void)sendSessionEvents;
+(id)getSessionEvents;
+(void)addHSEvent:(int)event withData:(id)data;
+(void)addHSEvent:(int)event;
+(void)appendHSEvent:(int)event withData:(id)data;
+(void)handleHsCloseForEvent:(int)event;
+(BOOL)handleHsOpenForEvent:(int)event;
+(BOOL)isHsOpen;
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
@end

