/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSImageUtils : XXUnknownSuperclass {
}
+(id)tintImage:(id)image withColor:(id)color;
+(void)addGradientToButton:(id)button;
+(id)thumbImageWithSideOfWidth:(float)width height:(float)height forImage:(id)image;
-(id)init;
@end

