/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSTimer;
@protocol HSIssueModelDelegate;

@interface HSIssueModel : XXUnknownSuperclass {
	id<HSIssueModelDelegate> delegate;
	NSTimer* issuePoller;
	NSMutableArray* issueIDArray;
	NSMutableArray* issueTitleArray;
	NSMutableArray* issueArray;
	NSMutableArray* cursorArray;
	NSMutableArray* issueUnreadArray;
}
@property(retain, nonatomic) id<HSIssueModelDelegate> delegate;
@property(retain, nonatomic) NSTimer* issuePoller;
@property(retain, nonatomic) NSMutableArray* issueUnreadArray;
@property(retain, nonatomic) NSMutableArray* cursorArray;
@property(retain, nonatomic) NSMutableArray* issueArray;
@property(retain, nonatomic) NSMutableArray* issueIDArray;
@property(retain, nonatomic) NSMutableArray* issueTitleArray;
+(void)sendCustomerSatisfactionRating:(int)rating withFeedback:(id)feedback forIssue:(id)issue onSuccess:(id)success onFailure:(id)failure;
+(void)refetchIssues;
+(void)stopPolling;
+(void)clearOldIssuesModel;
+(void)clearIssuesModel;
+(void)setIssueStatusForIssueID:(id)issueID withStatus:(int)status;
+(void)setUnreadCountForIssueID:(id)issueID withCount:(int)count;
+(void)updateUnreadCountForIssueID:(id)issueID toCount:(int)count;
+(void)markMessagesAsReadForIssueID:(id)issueID;
+(void)addMessagesArray:(id)array toUnreadCollectionForIssueID:(id)issueID;
+(void)initLastReadMessageForIssueID:(id)issueID;
+(void)nullifyIssueUnreadCount:(id)count;
+(BOOL)addIssue:(id)issue;
+(void)setCursorForIssueID:(id)issueID toCursor:(id)cursor;
+(int)getTotalUnreadCount;
+(int)getUnreadCountForIssueAtIndex:(int)index;
+(int)getUnreadCountForIssueID:(id)issueID;
+(id)getCursorJson;
+(id)getCursorForIssueID:(id)issueID;
+(id)getIssueUnreadArray;
+(id)getCursorArray;
+(id)getIssuesArray;
+(int)getIssuesCount;
+(id)getIssueTitleForId:(id)anId;
+(id)getIssueTitleAtIndex:(int)index;
+(id)getIssueIDAtIndex:(int)index;
+(int)getIssueIndexFromID:(id)anId;
+(id)sharedInstance;
-(void)triggerIssuesExponentialPolling;
-(void)updateIssuesPoller:(id)poller;
-(float)calculateNotificationInterval:(float)interval;
-(void)getIssues:(id)issues;
-(void)dealloc;
-(id)init;
@end

