/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class HSIssueModel;
@protocol HSIssueControllerDelegate;

@interface HSIssueController : XXUnknownSuperclass {
	id<HSIssueControllerDelegate> delegate;
	HSIssueModel* _issueModel;
}
@property(retain, nonatomic) id<HSIssueControllerDelegate> delegate;
@property(retain, nonatomic) HSIssueModel* issueModel;
+(void)loadIssuesIntoIssueIDArray:(id)array issueTitleArray:(id)array2;
+(int)getIndexForIssueID:(id)issueID;
+(BOOL)containsIssue:(id)issue;
+(void)csatDoneForConvId:(id)convId;
+(BOOL)isCSATDoneForConvId:(id)convId;
+(BOOL)isConvIDCleared:(id)cleared;
+(void)updateCurrentConversationToIssueID:(id)issueID;
+(void)updateCurrentConversation;
+(void)updateCurrentConversationStatus;
+(void)mungeData:(id)data forMessages:(BOOL)messages;
+(void)reloadIssues;
+(void)startIssuesReload;
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
@end

