/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSIssueMessagesController : XXUnknownSuperclass {
}
+(void)sendScreenShotForMessageIndex:(int)messageIndex forIssueID:(id)issueID withImage:(id)image withImageMessageIndex:(int)imageMessageIndex;
+(void)sendBlockedMessageForMessageIndex:(int)messageIndex forIssueID:(id)issueID;
+(void)sendYesMessageForIssueID:(id)issueID;
+(void)sendNoMessageForIssueID:(id)issueID;
+(void)sendYesMessageForMessageIndex:(int)messageIndex forIssueID:(id)issueID;
+(void)sendNoMessageForMessageIndex:(int)messageIndex forIssueID:(id)issueID;
+(void)sendAcceptReviewForIssueID:(id)issueID atIndex:(int)index;
+(void)sendMessageString:(id)string forIssueID:(id)issueID;
+(void)updateMessageStatusAtIndex:(int)index toState:(id)state;
+(void)updateMessageStateAtIndex:(int)index toState:(id)state;
+(void)updateMessageBodyAtIndex:(int)index toObject:(id)object;
+(void)addHappyToHelpMessageForIssueID:(id)issueID;
+(void)addSorryMessageForIssueID:(id)issueID;
+(void)addUserRejectionAutoResponseForIssueID:(id)issueID toLocal:(BOOL)local toDB:(BOOL)db;
+(void)addStateForMessageType:(id)messageType fromMessageMetaDictionary:(id)messageMetaDictionary;
+(void)loadMessagesAtIssueIndex:(int)issueIndex;
+(void)unloadMessageArrays;
+(void)updateIssueSingleMessage:(id)message atIssueIndex:(int)issueIndex;
+(void)updateIssueMessagesArray:(id)array atIssueIndex:(unsigned)issueIndex;
+(int)addIssueMessages:(id)messages forIssueID:(id)issueID;
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
@end

