/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSLocalization : XXUnknownSuperclass {
}
+(BOOL)isLanguageRTL:(id)rtl;
+(id)languageForString:(id)string;
+(BOOL)isDeviceLanguageRTL;
+(id)getLocalizedString:(id)string;
+(id)getLocalizedString:(id)string alter:(id)alter;
+(void)setLanguage:(id)language;
+(id)getLanguage;
+(void)initialize;
@end

