/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITextFieldDelegate.h"
#import "HSBaseViewController.h"
#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "HSSearchModelDelegate.h"

@class NSMutableArray, HSIssueController, UIView, UITableView, HSSearchDisplayController, HSMBProgressHUD, UISearchBar, NSArray, HSButton;

@interface HSMainViewController : HSBaseViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate, UISearchDisplayDelegate, UISearchBarDelegate, UITableViewDelegate, UITableViewDataSource, HSSearchModelDelegate> {
	HSButton* searchButton;
	UIView* containerView;
	NSMutableArray* _filteredListContent;
	NSMutableArray* _filteredListIDs;
	NSArray* _sections;
	NSArray* _faqs;
	HSIssueController* issueController;
	HSSearchDisplayController* searchDisplayController;
	UISearchBar* searchBar;
	HSMBProgressHUD* loadingScreen;
	UITableView* table;
	BOOL issuesEmpty;
}
@property(retain, nonatomic) NSArray* faqs;
@property(retain, nonatomic) NSArray* sections;
@property(retain, nonatomic) NSMutableArray* filteredListIDs;
@property(retain, nonatomic) NSMutableArray* filteredListContent;
@property(retain, nonatomic) HSMBProgressHUD* loadingScreen;
@property(assign, nonatomic) BOOL issuesEmpty;
+(id)sharedInstance;
-(BOOL)prefersStatusBarHidden;
-(void)searchIndexesUpdated;
-(void)filterContentForSearchText:(id)searchText;
-(void)searchBarSearchButtonClicked:(id)clicked;
-(void)searchBarCancelButtonClicked:(id)clicked;
-(void)searchBarTextDidBeginEditing:(id)searchBarText;
-(void)searchBarTextDidEndEditing:(id)searchBarText;
-(void)searchDisplayControllerDidEndSearch:(id)searchDisplayController;
-(BOOL)searchDisplayController:(id)controller shouldReloadTableForSearchScope:(int)searchScope;
-(BOOL)searchDisplayController:(id)controller shouldReloadTableForSearchString:(id)searchString;
-(void)searchDisplayController:(id)controller didLoadSearchResultsTableView:(id)view;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(CGSize)computeExpectedLabelSize:(id)size forFont:(id)font andWidth:(float)width;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(void)textFieldDidBeginEditing:(id)textField;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)hideLoadingScreen;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dismissVC;
-(id)getNoResultsFooterView;
-(id)getReportIssueFooterView;
-(void)launchConvFromSearch:(id)search;
-(void)loadView;
@end

