/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UIFont, NSDate, NSTimer, NSString, UILabel;
@protocol HSMBProgressHUDDelegate;

@interface HSMBProgressHUD : XXUnknownSuperclass {
	int mode;
	int animationType;
	SEL methodForExecution;
	id targetForExecution;
	id objectForExecution;
	BOOL useAnimation;
	float yOffset;
	float xOffset;
	float width;
	float height;
	float margin;
	BOOL dimBackground;
	BOOL taskInProgress;
	float graceTime;
	float minShowTime;
	NSTimer* graceTimer;
	NSTimer* minShowTimer;
	NSDate* showStarted;
	UIView* indicator;
	UILabel* label;
	UILabel* detailsLabel;
	float progress;
	id<HSMBProgressHUDDelegate> delegate;
	NSString* labelText;
	NSString* detailsLabelText;
	float opacity;
	UIFont* labelFont;
	UIFont* detailsLabelFont;
	BOOL isFinished;
	BOOL removeFromSuperViewOnHide;
	UIView* customView;
	CGAffineTransform rotationTransform;
}
@property(retain) NSDate* showStarted;
@property(retain) NSTimer* minShowTimer;
@property(retain) NSTimer* graceTimer;
@property(assign) float height;
@property(assign) float width;
@property(retain) UIView* indicator;
@property(assign) float progress;
@property(retain) UIFont* detailsLabelFont;
@property(retain) UIFont* labelFont;
@property(assign) BOOL removeFromSuperViewOnHide;
@property(assign) BOOL taskInProgress;
@property(assign) float minShowTime;
@property(assign) float graceTime;
@property(assign) BOOL dimBackground;
@property(assign) float margin;
@property(assign) float yOffset;
@property(assign) float xOffset;
@property(assign) float opacity;
@property(copy) NSString* detailsLabelText;
@property(copy) NSString* labelText;
@property(assign) id<HSMBProgressHUDDelegate> delegate;
@property(assign) int animationType;
@property(assign) int mode;
@property(retain) UIView* customView;
+(BOOL)hideHUDForView:(id)view animated:(BOOL)animated;
+(id)showHUDAddedTo:(id)to animated:(BOOL)animated;
-(void)setTransformForCurrentOrientation:(BOOL)currentOrientation;
-(void)deviceOrientationDidChange:(id)deviceOrientation;
-(void)drawRect:(CGRect)rect;
-(void)hideUsingAnimation:(BOOL)animation;
-(void)showUsingAnimation:(BOOL)animation;
-(void)cleanUp;
-(void)done;
-(void)animationFinished:(id)finished finished:(BOOL)finished2 context:(void*)context;
-(void)launchExecution;
-(void)showWhileExecuting:(SEL)executing onTarget:(id)target withObject:(id)object animated:(BOOL)animated;
-(void)handleMinShowTimer:(id)timer;
-(void)handleGraceTimer:(id)timer;
-(void)hideDelayed:(id)delayed;
-(void)hide:(BOOL)hide afterDelay:(double)delay;
-(void)hide:(BOOL)hide;
-(void)show:(BOOL)show;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithView:(id)view;
-(id)initWithWindow:(id)window;
-(void)updateIndicators;
-(void)updateProgress;
-(void)updateDetailsLabelText:(id)text;
-(void)updateLabelText:(id)text;
@end

