/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary;

@interface HSMetaDataController : XXUnknownSuperclass {
	id metaDataBlock;
	NSDictionary* metaData;
}
@property(copy, nonatomic) NSDictionary* metaData;
@property(copy, nonatomic) id metaDataBlock;
+(void)clearMetaData;
+(void)registerMetaData:(id)data;
+(void)registerMetaDataBlock:(id)block;
+(void)addLog:(id)log;
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
@end

