/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UINavigationControllerDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UITextViewDelegate.h"
#import "HSIssueMessagesDelegate.h"
#import "HSPreviewControllerDelegate.h"

@class UIImage, UITextField, UIView, UIImageView, HSPlaceHolderTextView, UIPopoverController, NSString, HSButton;

@interface HSNewConvViewController : XXUnknownSuperclass <UITextViewDelegate, UINavigationControllerDelegate, UIImagePickerControllerDelegate, HSIssueMessagesDelegate, HSPreviewControllerDelegate> {
	BOOL didChooseImage;
	BOOL willChooseImage;
	HSButton* attachButton;
	UIImage* screenshot;
	UIImageView* thumbnail;
	UIPopoverController* popover;
	float userInfoViewFrameY;
	BOOL _isParentDecomposed;
	BOOL _showUserInfoView;
	NSString* _prefillDesc;
	HSPlaceHolderTextView* _descTextView;
	UIView* _userInfoView;
	UITextField* _nameTextField;
	UITextField* _emailTextField;
}
@property(retain, nonatomic) UITextField* emailTextField;
@property(retain, nonatomic) UITextField* nameTextField;
@property(retain, nonatomic) UIView* userInfoView;
@property(retain, nonatomic) HSPlaceHolderTextView* descTextView;
@property(assign, nonatomic) BOOL showUserInfoView;
@property(assign, nonatomic) BOOL willChooseImage;
@property(assign, nonatomic) BOOL didChooseImage;
@property(assign, nonatomic) BOOL isParentDecomposed;
@property(copy, nonatomic) NSString* prefillDesc;
@property(retain, nonatomic) HSButton* attachButton;
@property(copy, nonatomic) UIImage* screenshot;
@property(retain, nonatomic) UIImageView* thumbnail;
@property(retain, nonatomic) UIPopoverController* popover;
+(unsigned)animationOptionsForCurve:(int)curve;
-(void)sendScreenShotFailureForMesgID:(id)mesgID mesgIndex:(int)index forIssueID:(id)issueID forError:(int)error withImageMessageIndex:(int)imageMessageIndex;
-(void)sendScreenShotSuccessForMesgID:(id)mesgID mesgIndex:(int)index forIssueID:(id)issueID withImage:(id)image imageUrl:(id)url withImageMessageIndex:(int)imageMessageIndex;
-(void)sendImage;
-(void)didSelectImage:(id)image;
-(void)imagePickerControllerDidCancel:(id)imagePickerController;
-(void)imagePickerController:(id)controller didFinishPickingMediaWithInfo:(id)info;
-(void)pickGalleryImageIPad;
-(void)pickGalleryImage;
-(void)chooseFromGallery;
-(void)deleteAttachment;
-(void)dealloc;
-(void)didReceiveMemoryWarning;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(BOOL)prefersStatusBarHidden;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)resizeView:(id)view;
-(void)handleKeyboardDidChangeFrame:(id)handleKeyboard;
-(void)handleKeyboardWillHide:(id)handleKeyboard;
-(void)handleKeyboardWillShow:(id)handleKeyboard;
-(BOOL)textView:(id)view shouldChangeTextInRange:(NSRange)range replacementText:(id)text;
-(BOOL)validateWithAlert:(BOOL)alert;
-(void)showAlertWithTitle:(id)title message:(id)message identifier:(id)identifier;
-(BOOL)validateEmail:(id)email;
-(void)showChatScreen;
-(void)createProfileAndAddNewIssue:(id)issue;
-(void)nextFieldAction;
-(void)sendButtonAction;
-(void)closeButtonAction;
-(void)initNavigationItem;
-(void)addAttachmentButton;
-(void)loadView;
@end

