/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSParser : XXUnknownSuperclass {
}
+(id)parseQuery:(id)query needTokenTypes:(BOOL)types;
+(id)parseDocument:(id)document needTokenTypes:(BOOL)types;
+(id)explodeQueryTokens:(id)tokens needTypes:(BOOL)types;
+(id)explodeTokens:(id)tokens needTypes:(BOOL)types;
@end

