/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface HSPersistentDataModel : XXUnknownSuperclass {
	sqlite3* hsDB;
}
+(sqlite3*)getHsftFaqsDbConn;
+(sqlite3*)getHSDBConn;
+(void)moveIssueUnreadArrayToDB:(id)db;
+(void)moveCursorArrayToDB:(id)db;
+(void)migrateHelpshiftData;
+(void)updateUAToken;
+(id)getPartnerIDForName:(id)name;
+(void)registerID:(id)anId forPartner:(id)partner;
+(double)doubleForKey:(id)key;
+(int)integerForKey:(id)key;
+(id)objectForKey:(id)key;
+(void)setDouble:(double)aDouble forKey:(id)key;
+(void)setInteger:(int)integer forKey:(id)key;
+(void)removeObjectForKey:(id)key;
+(void)setObject:(id)object forKey:(id)key;
+(void)initHelpshiftUserDefaults;
+(id)readLogs:(id)logs;
+(id)interface;
+(id)getFreeDiskspace;
+(id)getBreadCrumbs;
+(id)getDeviceMetadata;
+(id)cleanUpTagsArray:(id)array;
+(id)getUseremail;
+(id)getUsername;
+(id)getUserIdentifier;
+(id)getDeviceIdentifier;
+(id)getDeviceUdid;
+(void)removeEtagForRoute:(id)route;
+(id)getEtagForRoute:(id)route;
+(void)setEtag:(id)etag forRoute:(id)route;
+(void)clearData;
+(void)removeCSATDoneConversationIDs;
+(id)getCSATDoneConversationIDs;
+(void)pullBackConvIDFromClearedList:(id)clearedList;
+(void)clearConvID:(id)anId;
+(void)removeClearedConversationIDs;
+(id)getClearedConversationIDs;
+(void)removeCurrentConv;
+(id)getCurrentConv;
+(void)setCurrentConv:(id)conv;
+(void)didReceivePausedInAppInfo:(BOOL)appInfo forIssueID:(id)issueID;
+(void)removePauseInAppInfo;
+(id)getPauseInAppInfo;
+(void)setPauseInAppInfo:(id)appInfo;
+(void)setProfileID:(id)anId;
+(id)getProfileIDRemote;
+(id)getProfileID;
+(id)getAPIKey;
+(id)getAppID;
+(id)getDomain;
+(BOOL)isSDKInstalledCorrectly;
+(id)getSince;
+(id)sharedInstance;
+(HSDatabaseConstants)getHSDbConstants;
@end

