/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView, UIImage;
@protocol HSPreviewControllerDelegate;

@interface HSPreviewController : XXUnknownSuperclass {
	id<HSPreviewControllerDelegate> previewDelegate;
	int convType;
	UIImage* pickerImage;
	UIImageView* previewImageView;
}
@property(assign, nonatomic) int convType;
@property(retain, nonatomic) id<HSPreviewControllerDelegate> previewDelegate;
@property(retain, nonatomic) UIImageView* previewImageView;
@property(retain, nonatomic) UIImage* pickerImage;
-(void)dealloc;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)sendImage;
-(void)didReceiveMemoryWarning;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)loadView;
@end

