/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSSanitiser : XXUnknownSuperclass {
}
+(id)sanitise:(id)sanitise;
+(id)stripHtmlTags:(id)tags;
+(id)stripWhiteSpaces:(id)spaces;
+(id)trim:(id)trim;
+(id)rTrim:(id)trim;
+(id)lTrim:(id)trim;
+(id)asciiFolding:(id)folding;
+(id)lowercase:(id)lowercase;
@end

