/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSSearchController : XXUnknownSuperclass {
}
+(id)createSearchIndex:(id)index;
+(id)loadSearchIndex;
+(id)getFAQSearchResultTitleArray:(id)array;
+(id)getFAQSearchResultIDs:(id)ids;
+(id)getFAQSearchIndex;
@end

