/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSSignature : XXUnknownSuperclass {
}
-(id)hmacShaForKeyAndData:(id)keyAndData data:(id)data;
-(id)getSignatureFromSortedDictionary:(id)sortedDictionary;
-(id)init;
@end

