/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSBaseViewController.h"
#import "headshot-Structs.h"
#import "UIWebViewDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class UIView, NSDictionary, HSMBProgressHUD, UIWebView, UITableView, NSString;

@interface HSSingleFAQScreen : HSBaseViewController <UITableViewDelegate, UITableViewDataSource, UIWebViewDelegate> {
	NSDictionary* faq;
	NSString* faqPublishID;
	UITableView* tableSingle;
	NSString* faqTitle;
	NSString* faqBody;
	NSString* faqisRTL;
	HSMBProgressHUD* loadingScreen;
	UIView* header;
	UIWebView* webView;
	UIView* statusView;
	BOOL isParentDecomposed;
}
@property(assign, nonatomic) BOOL isParentDecomposed;
@property(retain, nonatomic) HSMBProgressHUD* loadingScreen;
@property(retain, nonatomic) NSString* faqisRTL;
@property(retain, nonatomic) NSString* faqPublishID;
@property(retain, nonatomic) NSString* faqBody;
@property(retain, nonatomic) NSString* faqTitle;
@property(retain, nonatomic) NSDictionary* faq;
@property(retain, nonatomic) UITableView* tableSingle;
-(BOOL)prefersStatusBarHidden;
-(void)addFAQStatusView;
-(void)hideLoadingScreen;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)webViewDidFinishLoad:(id)webView;
-(void)markHelpfulSet;
-(void)notHelpful;
-(void)launchNewConversation:(id)conversation;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)launchConversation:(id)conversation;
-(id)sanitizeFAQ;
-(void)goBack;
-(void)didMoveToParentViewController:(id)parentViewController;
-(void)videoExitedFullScreen:(id)screen;
-(void)videoFullScreen:(id)screen;
-(void)createAndLoadWebview;
-(void)loadView;
-(void)dealloc;
-(id)init;
@end

