/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSStringUtils : XXUnknownSuperclass {
}
+(int)regexCheckForWordCharacters:(id)wordCharacters;
+(BOOL)validateName:(id)name;
+(BOOL)validateEmail:(id)email;
+(BOOL)isProfileIDEmpty:(id)empty;
+(BOOL)isEmpty:(id)empty;
+(id)UTF8StringFromNSString:(id)nsstring;
+(id)stringByUnescapingFromHTML:(id)html;
+(id)urlencodeString:(id)string;
+(id)trimString:(id)string;
@end

