/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface HSTokeniser : XXUnknownSuperclass {
}
+(id)wordNGrams:(id)grams minLength:(unsigned)length maxLength:(unsigned)length3 needTypes:(BOOL)types;
+(id)splitWords:(id)words;
@end

