/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MATReachability;
@protocol MATEventQueueDelegate;

@interface MATAppToAppTracker : XXUnknownSuperclass {
	MATReachability* reachability;
	id<MATEventQueueDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<MATEventQueueDelegate> delegate;
+(id)getTrackingId;
+(id)getCampaignId;
+(id)getAdvertiserId;
+(id)getSessionDateTime;
+(id)getPublisherBundleId;
-(void).cxx_destruct;
-(void)storeToPasteBoardTrackingId:(id)pasteBoardTrackingId;
-(void)failedToRequestTrackingId:(id)requestTrackingId withError:(id)error;
-(void)startTrackingSessionForTargetBundleId:(id)targetBundleId publisherBundleId:(id)anId advertiserId:(id)anId3 campaignId:(id)anId4 publisherId:(id)anId5 redirect:(BOOL)redirect domainName:(id)name;
-(id)init;
@end

