/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MATCWorks : XXUnknownSuperclass {
}
+(id)MAT_getImpressions:(id)impressions;
+(id)MAT_getClicks:(id)clicks;
+(void)MAT_setDict:(id)dict forPasteboard:(id)pasteboard;
+(id)MAT_getDictFromPasteboard:(id)pasteboard;
+(id)MAT_getMD5:(id)a5;
@end

