/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSOperationQueue, NSString;

@interface MATDeferredDplinkr : XXUnknownSuperclass {
	BOOL _adTrackingEnabled;
	NSOperationQueue* _deeplinkOpQueue;
	NSString* _advertiserId;
	NSString* _conversionKey;
	NSString* _bundleId;
	NSString* _ifa;
}
@property(assign, nonatomic) BOOL adTrackingEnabled;
@property(copy, nonatomic) NSString* ifa;
@property(copy, nonatomic) NSString* bundleId;
@property(copy, nonatomic) NSString* conversionKey;
@property(copy, nonatomic) NSString* advertiserId;
@property(retain, nonatomic) NSOperationQueue* deeplinkOpQueue;
+(void)checkForDeferredDeeplinkWithTimeout:(double)timeout;
+(void)setIFA:(id)ifa trackingEnabled:(BOOL)enabled;
+(void)setPackageName:(id)name;
+(void)setAdvertiserId:(id)anId conversionKey:(id)key;
+(void)initialize;
-(void).cxx_destruct;
-(id)init;
@end

