/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MATEncrypter : XXUnknownSuperclass {
}
+(id)hexEncode:(id)encode;
+(id)aesEncryptData:(id)data withKey:(id)key;
+(id)encryptString:(id)string withKey:(id)key;
@end

