/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol MobileAppTrackerRegionDelegate;

@interface MATRegionMonitor : XXUnknownSuperclass {
	id<MobileAppTrackerRegionDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<MobileAppTrackerRegionDelegate> delegate;
-(void).cxx_destruct;
-(void)addBeaconRegion:(id)region nameId:(id)anId majorId:(unsigned)anId3 minorId:(unsigned)anId4;
-(void)startLocationManager;
@end

