/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MATUtils : XXUnknownSuperclass {
}
+(id)MATbase64EncodedStringFromData:(id)data;
+(id)MATdataFromBase64String:(id)base64String;
+(id)jsonSerialize:(id)serialize;
+(BOOL)addSkipBackupAttributeToItemAtURL:(id)url;
+(float)numericiOSSystemVersion;
+(float)numericiOSVersion:(id)version;
+(BOOL)isNetworkReachable;
+(id)installDate;
+(id)bundleId;
+(BOOL)checkJailBreak;
+(void)synchronizeUserDefaults;
+(void)setUserDefaultValue:(id)value forKey:(id)key;
+(id)userDefaultValueforKey:(id)key;
+(id)getStringForKey:(id)key fromPasteBoard:(id)pasteBoard;
+(id)parseXmlString:(id)string forTag:(id)tag;
+(id)getUUID;
+(id)generateFBCookieIdString;
+(int)daysBetweenDate:(id)date andDate:(id)date2;
@end

