/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MessagePackPacker : XXUnknownSuperclass {
}
+(id)pack:(id)pack;
+(void)packObject:(id)object into:(msgpack_packer*)into;
+(void)packNumber:(id)number into:(msgpack_packer*)into;
@end

