/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MessagePackParser : XXUnknownSuperclass {
	msgpack_unpacker unpacker;
}
+(id)parseData:(id)data;
+(id)createUnpackedObject:(msgpack_object)object;
-(id)next;
-(void)feed:(id)feed;
-(id)initWithBufferSize:(int)bufferSize;
-(id)init;
@end

