/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MobileAppTracker : XXUnknownSuperclass {
}
+(void)startMonitoringForBeaconRegion:(id)beaconRegion nameId:(id)anId majorId:(unsigned)anId3 minorId:(unsigned)anId4;
+(void)applicationDidOpenURL:(id)application sourceApplication:(id)application2;
+(void)startAppToAppTracking:(id)appTracking advertiserId:(id)anId offerId:(id)anId3 publisherId:(id)anId4 redirect:(BOOL)redirect;
+(void)setRedirectUrl:(id)url;
+(void)setUseCookieTracking:(BOOL)tracking;
+(void)measureActionWithEventId:(int)eventId eventItems:(id)items referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code transactionState:(int)state receipt:(id)receipt;
+(void)measureActionWithEventId:(int)eventId eventItems:(id)items referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code transactionState:(int)state;
+(void)measureActionWithEventId:(int)eventId eventItems:(id)items referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureActionWithEventId:(int)eventId eventItems:(id)items revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureActionWithEventId:(int)eventId eventItems:(id)items referenceId:(id)anId;
+(void)measureActionWithEventId:(int)eventId eventItems:(id)items;
+(void)measureActionWithEventId:(int)eventId referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureActionWithEventId:(int)eventId revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureActionWithEventId:(int)eventId referenceId:(id)anId;
+(void)measureActionWithEventId:(int)eventId;
+(void)measureAction:(id)action eventItems:(id)items referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code transactionState:(int)state receipt:(id)receipt;
+(void)measureAction:(id)action eventItems:(id)items referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code transactionState:(int)state;
+(void)measureAction:(id)action eventItems:(id)items referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureAction:(id)action eventItems:(id)items revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureAction:(id)action eventItems:(id)items referenceId:(id)anId;
+(void)measureAction:(id)action eventItems:(id)items;
+(void)measureAction:(id)action referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureAction:(id)action revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureAction:(id)action referenceId:(id)anId;
+(void)measureAction:(id)action;
+(void)measureSession;
+(void)removeiAd;
+(void)displayiAdInView:(id)view;
+(BOOL)isPayingUser;
+(id)openLogId;
+(id)matId;
+(void)setFacebookEventLogging:(BOOL)logging limitEventAndDataUsage:(BOOL)usage;
+(void)setPayingUser:(BOOL)user;
+(void)setEventAttribute5:(id)a5;
+(void)setEventAttribute4:(id)a4;
+(void)setEventAttribute3:(id)a3;
+(void)setEventAttribute2:(id)a2;
+(void)setEventAttribute1:(id)a1;
+(void)setEventDate2:(id)a2;
+(void)setEventDate1:(id)a1;
+(void)setEventRating:(float)rating;
+(void)setEventSearchString:(id)string;
+(void)setEventQuantity:(int)quantity;
+(void)setEventLevel:(int)level;
+(void)setEventContentId:(id)anId;
+(void)setEventContentType:(id)type;
+(void)setLocationAuthorizationStatus:(int)status;
+(void)setRegionName:(id)name;
+(void)setPluginName:(id)name;
+(void)setAppAdTracking:(BOOL)tracking;
+(void)setLatitude:(double)latitude longitude:(double)longitude altitude:(double)altitude;
+(void)setLatitude:(double)latitude longitude:(double)longitude;
+(void)setGender:(int)gender;
+(void)setAge:(int)age;
+(void)setGoogleUserId:(id)anId;
+(void)setTwitterUserId:(id)anId;
+(void)setFacebookUserId:(id)anId;
+(void)setUserName:(id)name;
+(void)setUserId:(id)anId;
+(void)setUserEmail:(id)email;
+(void)setTRUSTeId:(id)anId;
+(void)setSiteId:(id)anId;
+(void)setShouldAutoGenerateAppleVendorIdentifier:(BOOL)autoGenerateAppleVendorIdentifier;
+(void)setShouldAutoDetectJailbroken:(BOOL)autoDetectJailbroken;
+(void)setPackageName:(id)name;
+(void)setJailbroken:(BOOL)jailbroken;
+(void)setCurrencyCode:(id)code;
+(void)setAppleVendorIdentifier:(id)identifier;
+(void)setAppleAdvertisingIdentifier:(id)identifier advertisingTrackingEnabled:(BOOL)enabled;
+(void)setExistingUser:(BOOL)user;
+(void)setRegionDelegate:(id)delegate;
+(void)checkForDeferredDeeplinkWithTimeout:(double)timeout;
+(void)setDelegate:(id)delegate;
+(void)setAllowDuplicateRequests:(BOOL)requests;
+(void)setDebugMode:(BOOL)mode;
+(void)initializeWithMATAdvertiserId:(id)matadvertiserId MATConversionKey:(id)key;
+(id)sharedManager;
+(void)initialize;
@end

