/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDate, NSDictionary, NANReachability, NSMutableArray;

@interface NANTrackingData : XXUnknownSuperclass {
	dispatch_queue_s* requestDispatchQueue;
	NSString* storagePath;
	NSString* queuedRequestsPath;
	NSMutableArray* queuedRequests;
	NANReachability* reachability;
	NSDate* lastTimeCheckedForEventFiltering;
	BOOL nanHashExists;
	BOOL debugMode;
	BOOL _requestBeingDispatched;
	NSString* fbAppId;
	NSString* appId;
	NSString* userId;
	NSString* apiVersion;
	NSString* advertisingId;
	NSString* nanHash;
	NSDate* lastAppVisitTime;
	NSDictionary* _eventTypeFilter;
	NSDictionary* _eventNameFilter;
	NSMutableArray* _requestObservers;
}
@property(readonly, assign, nonatomic) BOOL nanHashExists;
@property(retain, nonatomic) NSMutableArray* requestObservers;
@property(retain, nonatomic) NSDictionary* eventNameFilter;
@property(retain, nonatomic) NSDictionary* eventTypeFilter;
@property(retain, nonatomic) NSDate* lastTimeCheckedForEventFiltering;
@property(assign, nonatomic) BOOL requestBeingDispatched;
@property(readonly, assign, nonatomic) NANReachability* reachability;
@property(readonly, assign, nonatomic) dispatch_queue_s* requestDispatchQueue;
@property(retain, nonatomic) NSDate* lastAppVisitTime;
@property(readonly, assign, nonatomic) NSString* nanHash;
@property(readonly, assign, nonatomic) NSString* advertisingId;
@property(retain, nonatomic) NSString* apiVersion;
@property(retain, nonatomic) NSString* userId;
@property(retain, nonatomic) NSString* appId;
@property(retain, nonatomic) NSString* fbAppId;
@property(assign, nonatomic) BOOL debugMode;
@property(readonly, assign, nonatomic) BOOL trackingEnabled;
+(id)sharedInstance;
-(void).cxx_destruct;
-(id)popQueuedRequest;
-(id)peekQueuedRequest;
-(void)pushQueuedRequest:(id)request;
-(id)init;
@end

