/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class NSURL, NSString;

@protocol QLPreviewItem <NSObject>
@optional
@property(readonly, assign) NSString* previewItemTitle;
@required
@property(readonly, assign) NSURL* previewItemURL;
@end

