/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SDImageCache, SDWebImageDownloader, NSMutableArray;
@protocol SDWebImageManagerDelegate;

__attribute__((visibility("hidden")))
@interface SDWebImageManager : XXUnknownSuperclass {
	id<SDWebImageManagerDelegate> _delegate;
	SDImageCache* _imageCache;
	SDWebImageDownloader* _imageDownloader;
	id _cacheKeyFilter;
	NSMutableArray* _failedURLs;
	NSMutableArray* _runningOperations;
}
@property(retain, nonatomic) NSMutableArray* runningOperations;
@property(retain, nonatomic) NSMutableArray* failedURLs;
@property(copy) id cacheKeyFilter;
@property(retain, nonatomic) SDWebImageDownloader* imageDownloader;
@property(retain, nonatomic) SDImageCache* imageCache;
@property(assign, nonatomic) __weak id<SDWebImageManagerDelegate> delegate;
+(id)sharedManager;
-(void).cxx_destruct;
-(BOOL)isRunning;
-(void)cancelAll;
-(void)saveImageToCache:(id)cache forURL:(id)url;
-(id)downloadImageWithURL:(id)url options:(unsigned)options progress:(id)progress completed:(id)completed;
-(BOOL)diskImageExistsForURL:(id)url;
-(BOOL)cachedImageExistsForURL:(id)url;
-(id)cacheKeyForURL:(id)url;
-(id)createCache;
-(id)init;
-(id)downloadWithURL:(id)url options:(unsigned)options progress:(id)progress completed:(id)completed;
-(id)nearestURLWithURL:(id)url;
@end

