/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSOperation, NSOperationQueue, NSMutableDictionary, NSObject;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SDWebImageDownloader : XXUnknownSuperclass {
	int _executionOrder;
	id _headersFilter;
	NSOperationQueue* _downloadQueue;
	NSOperation* _lastAddedOperation;
	NSMutableDictionary* _URLCallbacks;
	NSMutableDictionary* _HTTPHeaders;
	NSObject<OS_dispatch_queue>* _barrierQueue;
	double _downloadTimeout;
}
@property(retain, nonatomic) NSObject<OS_dispatch_queue>* barrierQueue;
@property(retain, nonatomic) NSMutableDictionary* HTTPHeaders;
@property(retain, nonatomic) NSMutableDictionary* URLCallbacks;
@property(assign, nonatomic) __weak NSOperation* lastAddedOperation;
@property(retain, nonatomic) NSOperationQueue* downloadQueue;
@property(copy, nonatomic) id headersFilter;
@property(assign, nonatomic) int executionOrder;
@property(assign, nonatomic) double downloadTimeout;
@property(readonly, assign, nonatomic) unsigned currentDownloadCount;
@property(assign, nonatomic) int maxConcurrentDownloads;
+(id)sharedDownloader;
+(void)initialize;
-(void).cxx_destruct;
-(void)setSuspended:(BOOL)suspended;
-(void)removeCallbacksForURL:(id)url;
-(id)callbacksForURL:(id)url;
-(void)addProgressCallback:(id)callback andCompletedBlock:(id)block forURL:(id)url createCallback:(id)callback4;
-(id)downloadImageWithURL:(id)url options:(unsigned)options progress:(id)progress completed:(id)completed;
-(id)valueForHTTPHeaderField:(id)httpheaderField;
-(void)setValue:(id)value forHTTPHeaderField:(id)httpheaderField;
-(void)dealloc;
-(id)init;
@end

