/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SDWebImageManager, NSArray;
@protocol SDWebImagePrefetcherDelegate;

__attribute__((visibility("hidden")))
@interface SDWebImagePrefetcher : XXUnknownSuperclass {
	SDWebImageManager* _manager;
	unsigned _options;
	id<SDWebImagePrefetcherDelegate> _delegate;
	NSArray* _prefetchURLs;
	unsigned _requestedCount;
	unsigned _skippedCount;
	unsigned _finishedCount;
	id _completionBlock;
	id _progressBlock;
	double _startedTime;
}
@property(copy, nonatomic) id progressBlock;
@property(copy, nonatomic) id completionBlock;
@property(assign, nonatomic) double startedTime;
@property(assign, nonatomic) unsigned finishedCount;
@property(assign, nonatomic) unsigned skippedCount;
@property(assign, nonatomic) unsigned requestedCount;
@property(retain, nonatomic) NSArray* prefetchURLs;
@property(assign, nonatomic) __weak id<SDWebImagePrefetcherDelegate> delegate;
@property(assign, nonatomic) unsigned options;
@property(assign, nonatomic) unsigned maxConcurrentDownloads;
@property(retain, nonatomic) SDWebImageManager* manager;
+(id)sharedImagePrefetcher;
-(void).cxx_destruct;
-(void)cancelPrefetching;
-(void)prefetchURLs:(id)urls progress:(id)progress completed:(id)completed;
-(void)prefetchURLs:(id)urls;
-(void)reportStatus;
-(void)startPrefetchingAtIndex:(unsigned)index;
-(id)init;
@end

