/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol NSCopying, NSObject;

__attribute__((visibility("hidden")))
@interface Tuple : XXUnknownSuperclass {
	id<NSCopying, NSObject> _key;
	id _value;
}
@property(retain, nonatomic) id value;
@property(retain, nonatomic) id<NSCopying, NSObject> key;
+(id)tupleWithValue:(id)value forKey:(id)key;
-(void)dealloc;
-(BOOL)isEqual:(id)equal;
-(id)initWithValue:(id)value forKey:(id)key;
@end

