/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "NSCopying.h"
#import "WBPersistedObject.h"

@class NSNumber, NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface WBAnalyticEvent : WBPersistedObject <NSCopying> {
	NSString* _name;
	int _type;
	int _priority;
	NSNumber* _dupIndex;
	NSMutableDictionary* _parameters;
	int _index;
	long long _time;
}
@property(assign, nonatomic) int index;
@property(retain, nonatomic) NSMutableDictionary* parameters;
@property(retain, nonatomic) NSNumber* dupIndex;
@property(assign, nonatomic) int priority;
@property(readonly, assign, nonatomic) long long time;
@property(readonly, assign, nonatomic) int type;
@property(copy, nonatomic) NSString* name;
-(void).cxx_destruct;
-(id)description;
-(id)objectForPost;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithName:(id)name type:(int)type parameters:(id)parameters;
@end

