/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBAnalyticPayload.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface WBAnalyticSessionPayload : WBAnalyticPayload {
	BOOL _persisted;
	NSString* _deviceToken;
}
@property(retain, nonatomic) NSString* payloadId;
@property(retain, nonatomic) NSString* deviceToken;
@property(assign, nonatomic) BOOL persisted;
+(id)persistedSessionPayloadDirectory;
-(void).cxx_destruct;
-(id)httpUrl;
-(void)remove;
-(void)persist;
-(id)initWithSession:(id)session deviceToken:(id)token buildType:(int)type;
-(id)initWithSavedSessionPath:(id)savedSessionPath deviceToken:(id)token;
@end

