/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray;

__attribute__((visibility("hidden")))
@interface WBAnalyticSession : XXUnknownSuperclass {
	NSString* _sessionId;
	NSMutableArray* _internalEvents;
}
@property(retain, nonatomic) NSMutableArray* internalEvents;
@property(retain, nonatomic) NSString* sessionId;
-(void).cxx_destruct;
-(void)collapseDuplicateEvents;
-(void)clear;
-(unsigned)count;
-(id)events;
-(void)queueEvent:(id)event;
-(id)init;
@end

