/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "NSCopying.h"
#import "WBPersistedObject.h"

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface WBAnalyticDeviceInfo : WBPersistedObject <NSCopying> {
	BOOL _pushEnabled;
	NSString* _os;
	NSString* _osVersion;
	NSString* _sdkVersion;
	NSString* _session;
	NSString* _locale;
	NSString* _advertisingIdentifier;
	NSString* _identifierForVendor;
	NSString* _platform;
	NSString* _bundle;
	NSString* _model;
	NSString* _appVersion;
	NSString* _store;
	int _buildType;
	NSString* _email;
	NSNumber* _lat;
	NSNumber* _lng;
	NSNumber* _age;
	unsigned _gender;
	NSString* _pushToken;
	NSString* _userId;
	NSString* _facebookId;
	NSString* _gameCenterPlayerId;
}
@property(retain, nonatomic) NSString* gameCenterPlayerId;
@property(retain, nonatomic) NSString* facebookId;
@property(retain, nonatomic) NSString* userId;
@property(retain, nonatomic) NSString* pushToken;
@property(assign, nonatomic) unsigned gender;
@property(retain, nonatomic) NSNumber* age;
@property(retain, nonatomic) NSNumber* lng;
@property(retain, nonatomic) NSNumber* lat;
@property(retain, nonatomic) NSString* email;
@property(assign, nonatomic) BOOL pushEnabled;
@property(assign, nonatomic) int buildType;
@property(retain, nonatomic) NSString* store;
@property(retain, nonatomic) NSString* appVersion;
@property(retain, nonatomic) NSString* model;
@property(retain, nonatomic) NSString* bundle;
@property(retain, nonatomic) NSString* platform;
@property(retain, nonatomic) NSString* identifierForVendor;
@property(retain, nonatomic) NSString* advertisingIdentifier;
@property(retain, nonatomic) NSString* locale;
@property(retain, nonatomic) NSString* session;
@property(retain, nonatomic) NSString* sdkVersion;
@property(retain, nonatomic) NSString* osVersion;
@property(retain, nonatomic) NSString* os;
-(void).cxx_destruct;
-(void)updateProperty:(id)property toValue:(id)value;
-(BOOL)updateDeviceInfo:(id)info;
-(id)copyWithZone:(NSZone*)zone;
-(id)objectForPost;
-(void)_onDeviceProperty:(id)property changedToValue:(id)value;
-(id)initWithSettings:(id)settings;
@end

