/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData, NSString;

__attribute__((visibility("hidden")))
@interface WBAnalyticPayload : XXUnknownSuperclass {
	NSData* _payload;
	unsigned _retryCount;
	NSString* _payloadId;
}
@property(readonly, assign, nonatomic) NSData* payload;
@property(retain, nonatomic) NSString* payloadId;
@property(assign, nonatomic) unsigned retryCount;
+(BOOL)isValidPayloadId:(id)anId;
-(void).cxx_destruct;
-(id)httpMethod;
-(id)httpUrl;
-(id)init;
@end

