/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface WBAnalyticSettings : XXUnknownSuperclass {
	BOOL _allowUseOfAdvertisingIdentifier;
	BOOL _trackInstall;
	BOOL _enableTimerFlushing;
	BOOL _automaticallyUpdateDeviceToken;
	int _buildType;
}
@property(assign, nonatomic) BOOL automaticallyUpdateDeviceToken;
@property(assign, nonatomic) BOOL enableTimerFlushing;
@property(assign, nonatomic) int buildType;
@property(assign, nonatomic) BOOL trackInstall;
@property(assign, nonatomic) BOOL allowUseOfAdvertisingIdentifier;
-(id)init;
@end

