/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIAlertViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class WBAnalyticSettings, WBAnalyticSession, WBWeakTimer, NSString, NSError;

__attribute__((visibility("hidden")))
@interface WBAnalyticEngine : XXUnknownSuperclass <UIAlertViewDelegate> {
	NSString* _applicationKey;
	WBAnalyticSettings* _settings;
	NSString* _deviceToken;
	WBWeakTimer* _timer;
	unsigned _cachedPayloadSize;
	WBAnalyticSession* _session;
	NSError* _strictModeError;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSError* strictModeError;
@property(retain, nonatomic) WBAnalyticSession* session;
@property(assign) unsigned cachedPayloadSize;
@property(retain, nonatomic) WBWeakTimer* timer;
@property(retain) NSString* deviceToken;
@property(readonly, assign, nonatomic) WBAnalyticSettings* settings;
@property(readonly, assign, nonatomic) NSString* applicationKey;
+(void)turnOffEngine;
+(BOOL)isEngineInitialized;
+(void)startEngineWithApplicationKey:(id)applicationKey settings:(id)settings;
+(id)sharedEngine;
-(void).cxx_destruct;
-(BOOL)flush:(id)flush;
-(BOOL)flush;
-(void)clearQueue;
-(void)queueEvent:(id)event;
-(void)endSession;
-(void)startSession;
-(id)deviceInfo;
-(void)setDeviceInfo:(id)info;
-(BOOL)isStrictModeEnabled;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)_flushPayload:(id)payload completionHandler:(id)handler;
-(void)_timerTick:(id)tick;
-(void)_checkForUpdatedDeviceInfo;
-(id)_cachedDeviceInfo;
-(void)_saveDeviceInfo:(id)info;
-(void)_saveDeviceToken:(id)token;
-(void)_registerDeviceProperty:(id)property value:(id)value;
-(void)_initialRegisterDeviceProperty:(id)property value:(id)value;
-(void)_processPersistedPayloads;
-(void)_getDeviceToken;
-(void)networkStatusChanged:(id)changed;
-(void)deviceInfoChanged:(id)changed;
-(void)dealloc;
-(id)initWithApplicationKey:(id)applicationKey settings:(id)settings;
@end

