/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBService.h"


__attribute__((visibility("hidden")))
@interface WBAssetCache : WBService {
}
+(void)cacheFileStream:(id)stream completionHandler:(id)handler;
+(id)cacheFileStream:(id)stream error:(id*)error;
+(BOOL)removeContentForUrl:(id)url useTemporaryStorage:(BOOL)storage error:(id*)error;
+(id)cachedFilePathForUrl:(id)url useTemporaryStorage:(BOOL)storage;
+(BOOL)removeContent:(id)content error:(id*)error;
+(id)cachedFilePathForContent:(id)content;
+(void)_checkCacheSpaceLastItemAdded:(id)added;
@end

