/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface WBCache : XXUnknownSuperclass {
}
+(void)flush;
+(void)removeObjectForKey:(id)key;
+(void)setObject:(id)object forKey:(id)key;
+(id)objectForKey:(id)key itemNotFoundHandler:(id)handler;
+(id)objectForKey:(id)key;
+(void)setObject:(id)object forKeyedSubscript:(id)keyedSubscript;
+(id)objectForKeyedSubscript:(id)keyedSubscript;
+(id)cache;
@end

