/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class WBWeakTimer, NSHashTable;

__attribute__((visibility("hidden")))
@interface WBClock : XXUnknownSuperclass {
	NSHashTable* _secondsObservers;
	WBWeakTimer* _secondsTimer;
}
@property(retain, nonatomic) WBWeakTimer* secondsTimer;
@property(retain, nonatomic) NSHashTable* secondsObservers;
+(void)unregisterForSecondsPrecision:(id)secondsPrecision;
+(void)registerForSecondsPrecision:(id)secondsPrecision;
+(id)shared;
-(void).cxx_destruct;
-(void)_tick:(id)tick;
-(id)init;
@end

