/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDateFormatter;

__attribute__((visibility("hidden")))
@interface WBDateFormatter : XXUnknownSuperclass {
	NSDateFormatter* _longDateTime;
	NSDateFormatter* _utcDateTime;
	NSDateFormatter* _iso8601WithTimezoneTime;
	NSDateFormatter* _utcTimestampWithFractionalSeconds;
	NSDateFormatter* _mdyDate;
}
@property(retain, nonatomic) NSDateFormatter* mdyDate;
@property(retain, nonatomic) NSDateFormatter* utcTimestampWithFractionalSeconds;
@property(retain, nonatomic) NSDateFormatter* iso8601WithTimezoneTime;
@property(retain, nonatomic) NSDateFormatter* utcDateTime;
@property(retain, nonatomic) NSDateFormatter* longDateTime;
+(id)dateFromIso8601String:(id)iso8601String;
+(id)dateFromMDYString:(id)mdystring;
+(id)utcDateFromString:(id)string;
+(id)sharedFormatter;
-(void).cxx_destruct;
-(id)stringFromDate:(id)date;
-(id)utcDateTimeString:(id)string;
-(id)init;
@end

