/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBCache.h"


__attribute__((visibility("hidden")))
@interface WBDiskBasedCache : WBCache {
}
+(void)flush;
+(void)setObject:(id)object forKey:(id)key;
+(id)objectForKey:(id)key itemNotFoundHandler:(id)handler;
+(id)objectForKey:(id)key;
+(id)_pathForKey:(id)key;
+(void)initialize;
@end

