/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WBDownloadableContent <NSObject>
-(BOOL)useTemporaryStorage;
-(BOOL)isContentAvailable;
-(id)contentUrl;
-(id)contentPath;
-(BOOL)hasDownloadableContent;
@optional
-(BOOL)allowsCellularAccess;
-(id)contentThumbnailUrl;
-(id)contentPreviewUrl;
@end

