/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBDownloadableContent.h"
#import "WBObject.h"

@class NSString, NSURL;

__attribute__((visibility("hidden")))
@interface WBDownloadContentRequest : WBObject <WBDownloadableContent> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSURL* contentPath;
@property(readonly, assign, nonatomic) BOOL useTemporaryStorage;
@property(readonly, assign, nonatomic) NSString* contentUrl;
-(BOOL)isContentAvailable;
-(BOOL)hasDownloadableContent;
@end

