/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBService.h"

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface WBExperimentService : WBService {
	NSDictionary* _cachedValues;
}
@property(retain, nonatomic) NSDictionary* cachedValues;
+(void)requestExperiments:(id)experiments;
+(void)processUpdatedEnrollments:(id)enrollments;
+(void)saveEnrollments:(id)enrollments;
+(id)loadCachedEnrollments;
+(void)saveEntityTag:(id)tag;
+(id)getEntityTag;
+(void)saveValues:(id)values;
+(id)loadCachedValues;
+(id)getValueForKey:(id)key defaultValue:(id)value;
+(id)getValueForKey:(id)key;
+(id)sharedInstance;
+(void)initialize;
-(void).cxx_destruct;
-(void)_fetchEnrollmentsWithCompletionHandler:(id)completionHandler remainingRetries:(int)retries;
-(id)init;
@end

