/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, NSURL;
@protocol OS_dispatch_io;

__attribute__((visibility("hidden")))
@interface WBFileStream : XXUnknownSuperclass {
	BOOL _userDidCancel;
	BOOL _closing;
	NSURL* _filePath;
	id _completionHandler;
	NSURL* _tempPath;
	NSURL* _path;
	NSObject<OS_dispatch_io>* _stream;
	int _errorNumber;
	long long _totalBytes;
	long long _bytesWritten;
}
@property(assign, nonatomic) int errorNumber;
@property(assign, nonatomic) BOOL closing;
@property(assign, nonatomic) BOOL userDidCancel;
@property(assign, nonatomic) long long bytesWritten;
@property(assign, nonatomic) long long totalBytes;
@property(retain, nonatomic) NSObject<OS_dispatch_io>* stream;
@property(copy, nonatomic) NSURL* path;
@property(copy, nonatomic) NSURL* tempPath;
@property(copy, nonatomic) id completionHandler;
@property(copy, nonatomic) NSURL* filePath;
-(void).cxx_destruct;
-(void)close;
-(void)cancel;
-(void)writeData:(id)data;
-(void)beginWriteOperationWithExpectedLength:(long long)expectedLength offset:(long long)offset;
-(long long)checkPartialDownloadOffset;
-(id)initWithFilePath:(id)filePath tempPath:(id)path;
-(id)initWithFilePath:(id)filePath;
@end

