/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBService.h"


__attribute__((visibility("hidden")))
@interface WBIO : WBService {
}
+(BOOL)removeAllFiles:(id*)files;
+(BOOL)removeDirectory:(id)directory error:(id*)error;
+(BOOL)removeAllFilesInDirectory:(id)directory error:(id*)error;
+(id)fileStreamForUrl:(id)url useTemporaryStorage:(BOOL)storage;
+(BOOL)removeContentForUrl:(id)url useTemporaryStorage:(BOOL)storage;
+(id)filePathForUrl:(id)url useTemporaryStorage:(BOOL)storage;
+(id)downloadDirectory;
+(id)cacheDirectory;
+(id)cacheSubDirectory:(id)directory;
+(id)documentsDirectory;
@end

