/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface WBLogging : XXUnknownSuperclass {
	NSMutableDictionary* _logs;
}
@property(retain, nonatomic) NSMutableDictionary* logs;
+(void)log:(id)log;
+(id)logger;
-(void).cxx_destruct;
-(id)logMessagesForLevel:(unsigned)level type:(unsigned)type;
-(id)logMessagesForLevel:(unsigned)level;
-(id)setForLevel:(unsigned)level;
-(void)log:(id)log;
-(void)clearType:(unsigned)type;
-(void)clear;
-(id)init;
@end

