/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface WBLog : XXUnknownSuperclass {
	unsigned _level;
	unsigned _type;
	NSString* _message;
	NSString* _lineNumber;
	double _timestamp;
}
@property(assign, nonatomic) double timestamp;
@property(retain, nonatomic) NSString* lineNumber;
@property(retain, nonatomic) NSString* message;
@property(assign, nonatomic) unsigned type;
@property(assign, nonatomic) unsigned level;
+(id)logWithLevel:(unsigned)level type:(unsigned)type lineNumber:(id)number message:(id)message;
+(id)logWithLevel:(unsigned)level type:(unsigned)type message:(id)message;
+(id)logWithLevel:(unsigned)level message:(id)message;
-(void).cxx_destruct;
-(id)description;
-(id)initWithLevel:(unsigned)level type:(unsigned)type lineNumber:(id)number message:(id)message;
-(id)init;
@end

