/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBObject.h"

@class NSArray, NSString, NSDate;

__attribute__((visibility("hidden")))
@interface WBMaintenanceMode : WBObject {
}
@property(readonly, assign, nonatomic) NSArray* platforms;
@property(readonly, assign, nonatomic) NSString* status;
@property(readonly, assign, nonatomic) NSDate* upDate;
@property(readonly, assign, nonatomic) NSString* message;
+(id)maintenanceMode;
+(void)setMaintenanceMode:(id)mode;
-(id)formattedUpDate;
@end

