/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBService.h"


__attribute__((visibility("hidden")))
@interface WBNetworkService : WBService {
}
+(void)_networkStatusChanged:(id)changed;
+(BOOL)online;
+(int)networkStatus;
+(id)networkOperationQueue;
+(id)networkThread;
+(void)networkThreadEntryPoint:(id)point;
+(void)enqueueContentForBackgroundDownload:(id)backgroundDownload;
+(void)startBackgroundDownloads;
+(void)applicationWillEnterForeground:(id)application;
+(void)applicationDidEnterBackground:(id)application;
+(void)initialize;
+(id)downloadContentSynchronously:(id)synchronously error:(id*)error;
+(void)downloadContent:(id)content progressHandler:(id)handler completionHandler:(id)handler3;
+(id)cacheableDownloadOperationForUrl:(id)url useTemporaryStorage:(BOOL)storage progressHandler:(id)handler completionHandler:(id)handler4;
+(void)_downloadFileAtUrl:(id)url useTemporaryStorage:(BOOL)storage progressHandler:(id)handler completionHandler:(id)handler4;
@end

