/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "WBObject.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray;

__attribute__((visibility("hidden")))
@interface WBObjectArray : XXUnknownSuperclass <WBObject> {
	BOOL _disableObjectifying;
	int _serverCase;
	int _options;
	NSMutableArray* _internalArray;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableArray* internalArray;
@property(assign, nonatomic) BOOL disableObjectifying;
@property(assign, nonatomic) int options;
@property(assign, nonatomic) int serverCase;
-(void).cxx_destruct;
-(id)reverseObjectEnumerator;
-(id)objectEnumerator;
-(id)objectAtIndex:(unsigned)index;
-(unsigned)count;
-(void)replaceObjectAtIndex:(unsigned)index withObject:(id)object;
-(void)removeLastObject;
-(void)addObject:(id)object;
-(void)removeObjectAtIndex:(unsigned)index;
-(void)insertObject:(id)object atIndex:(unsigned)index;
-(id)initWithCapacity:(unsigned)capacity;
-(Class)classForKeyedArchiver;
-(Class)classForCoder;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)copyWithZone:(NSZone*)zone;
-(void)wbObjectifyAll;
-(id)wbObjectifyAtIndex:(unsigned)index;
-(id)initWithJsonArray:(id)jsonArray options:(int)options;
-(id)init;
@end

