/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "WBObject.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSObject.h"

@class NSString, NSMutableDictionary;

@protocol WBObject <NSObject>
@end

__attribute__((visibility("hidden")))
@interface WBObject : XXUnknownSuperclass <WBObject> {
	BOOL _disableObjectifying;
	int _serverCase;
	int _options;
	NSMutableDictionary* _internalDictionary;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableDictionary* internalDictionary;
@property(assign, nonatomic) BOOL disableObjectifying;
@property(assign, nonatomic) int options;
@property(assign, nonatomic) int serverCase;
+(int)inferredImplTypeForSelector:(SEL)selector;
+(id)convertObject:(id)object toType:(WBType)type;
+(BOOL)class:(Class)aClass isKindOfClass:(Class)aClass2;
+(id)objectifyObjects:(id)objects;
+(id)wbObjectWithObject:(id)object;
+(id)wbObject;
+(id)wbObjectWithJsonObject:(id)jsonObject options:(int)options;
-(void).cxx_destruct;
-(void)wbObjectifyAll;
-(void)objectify;
-(id)wbObjectifyAtKey:(id)key;
-(id)objectForKey:(id)key withType:(WBType)type;
-(void)setUnsignedChar:(unsigned char)aChar forKey:(id)key;
-(unsigned char)unsignedCharForKey:(id)key;
-(void)setChar:(BOOL)aChar forKey:(id)key;
-(BOOL)charForKey:(id)key;
-(void)setUnsignedShort:(unsigned short)aShort forKey:(id)key;
-(unsigned short)unsignedShortForKey:(id)key;
-(void)setUnsignedLongLong:(unsigned long long)aLong forKey:(id)key;
-(unsigned long long)unsignedLongLongForKey:(id)key;
-(void)setUnsignedLong:(unsigned long)aLong forKey:(id)key;
-(unsigned long)unsignedLongForKey:(id)key;
-(void)setUnsignedInt:(unsigned)int forKey:(id)key;
-(unsigned)unsignedIntForKey:(id)key;
-(void)setBool:(BOOL)aBool forKey:(id)key;
-(BOOL)boolForKey:(id)key;
-(void)setShort:(short)aShort forKey:(id)key;
-(short)shortForKey:(id)key;
-(void)setLongLong:(long long)aLong forKey:(id)key;
-(long long)longLongForKey:(id)key;
-(void)setLong:(long)aLong forKey:(id)key;
-(long)longForKey:(id)key;
-(void)setDouble:(double)aDouble forKey:(id)key;
-(double)doubleForKey:(id)key;
-(void)setFloat:(float)aFloat forKey:(id)key;
-(float)floatForKey:(id)key;
-(void)setInt:(int)int forKey:(id)key;
-(int)intForKey:(id)key;
-(id)jsonCopy;
-(id)objectForPost;
-(id)keyEnumerator;
-(id)objectForKey:(id)key;
-(unsigned)count;
-(void)removeObjectForKey:(id)key;
-(void)setObject:(id)object forKey:(id)key;
-(id)initWithObjects:(id)objects forKeys:(id)keys;
-(id)initWithCapacity:(unsigned)capacity;
-(Class)classForKeyedArchiver;
-(Class)classForCoder;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)copyWithZone:(NSZone*)zone;
-(void)forwardInvocation:(id)invocation;
-(id)methodSignatureForSelector:(SEL)selector;
-(SEL)selectorForType:(WBType)type selectorInferredType:(int)type2;
-(BOOL)respondsToSelector:(SEL)selector;
-(id)initWithJsonDictionary:(id)jsonDictionary options:(int)options;
-(id)initWithDictionary:(id)dictionary options:(int)options;
-(id)init;
@end

