/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "headshot-Structs.h"
#import "NSCoding.h"


__attribute__((visibility("hidden")))
@interface WBPersistedObject : XXUnknownSuperclass <NSCoding, NSCopying> {
}
-(id)objectForPost;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
@end

