/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBService.h"


__attribute__((visibility("hidden")))
@interface WBSettingService : WBService {
}
+(id)bundleSettingForKey:(id)key;
+(id)settingForKey:(id)key;
+(id)serverPathForZone:(id)zone;
@end

