/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AVAudioPlayerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, NSString;

__attribute__((visibility("hidden")))
@interface WBSoundService : XXUnknownSuperclass <AVAudioPlayerDelegate> {
	BOOL _soundOn;
	NSMutableSet* _audioPlayers;
	NSMutableSet* _audioFilesPlaying;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL soundOn;
@property(retain, nonatomic) NSMutableSet* audioFilesPlaying;
@property(retain, nonatomic) NSMutableSet* audioPlayers;
+(void)playSoundNamed:(id)named;
+(void)setSoundOn:(BOOL)on;
+(void)_playSoundNamed:(id)named allowMultiple:(BOOL)multiple;
+(id)sharedService;
-(void).cxx_destruct;
-(void)audioPlayerDecodeErrorDidOccur:(id)audioPlayerDecodeError error:(id)error;
-(void)audioPlayerDidFinishPlaying:(id)audioPlayer successfully:(BOOL)successfully;
-(void)dealloc;
-(id)init;
@end

