/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBObject.h"


__attribute__((visibility("hidden")))
@interface WBTimeSpan : WBObject {
}
@property(assign, nonatomic) long long ticks;
+(id)daysHoursMinutesSecondsStringFromTimeInterval:(double)timeInterval withMaxUnits:(int)maxUnits;
+(id)fromTicks:(long long)ticks;
+(id)timeSpanWithDay:(int)day hours:(int)hours minutes:(int)minutes seconds:(int)seconds;
+(id)timeSpanWithHours:(int)hours minutes:(int)minutes seconds:(int)seconds;
+(id)timeSpanWithDay:(int)day hours:(int)hours minutes:(int)minutes seconds:(int)seconds milliseconds:(int)milliseconds;
+(id)timeSpanWithTimeInterval:(double)timeInterval;
+(id)minValue;
+(id)maxValue;
-(id)daysHoursMinutesSecondsStringWithMaxUnits:(int)maxUnits;
-(id)addTimeSpan:(id)span;
-(id)addTicks:(long long)ticks;
-(int)compareTo:(id)to;
-(BOOL)isEqual:(id)equal;
-(double)timeInterval;
-(double)totalMilliseconds;
-(double)totalSeconds;
-(double)totalMinutes;
-(double)totalHours;
-(double)totalDays;
-(int)milliseconds;
-(int)seconds;
-(int)minutes;
-(int)hours;
-(int)days;
@end

