/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "WBPersistedObject.h"

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface WBTouchPoint : WBPersistedObject {
	NSString* _area;
	NSNumber* _x;
	NSNumber* _y;
	NSNumber* _z;
}
@property(retain, nonatomic) NSNumber* z;
@property(retain, nonatomic) NSNumber* y;
@property(retain, nonatomic) NSNumber* x;
@property(retain, nonatomic) NSString* area;
-(void).cxx_destruct;
-(id)initWithArea:(id)area x:(id)x y:(id)y z:(id)z;
-(id)initWithArea:(id)area point:(CGPoint)point;
-(id)initWithArea:(id)area;
@end

