/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDate, NSTimer;

__attribute__((visibility("hidden")))
@interface WBWeakTimer : XXUnknownSuperclass {
	id _target;
	SEL _selector;
	NSTimer* _timer;
	NSDate* _previousFireDate;
	id _firingHandler;
}
@property(copy, nonatomic) id firingHandler;
@property(retain, nonatomic) NSDate* previousFireDate;
@property(assign, nonatomic) __weak NSTimer* timer;
@property(assign, nonatomic) SEL selector;
@property(assign, nonatomic) __weak id target;
+(id)weakTimerAtDate:(id)date block:(id)block;
+(id)weakTimerWithTimeInterval:(double)timeInterval target:(id)target selector:(SEL)selector userInfo:(id)info repeats:(BOOL)repeats;
-(void).cxx_destruct;
-(void)dealloc;
-(id)block;
-(id)userInfo;
-(id)fireDate;
-(void)resume;
-(void)pause;
-(void)invalidate;
-(void)timerFired:(id)fired;
-(id)init;
@end

