/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "headshot-Structs.h"
#import "UIActionSheetDelegate.h"
#import "UIAlertViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSString;

@interface XXUnknownSuperclass (ADJAdditions)
-(void)adjSetIad:(id)iad;
-(id)adjVendorId;
-(id)adjCreateUuid;
-(id)adjDeviceName;
-(id)adjDeviceType;
-(id)adjMacAddress;
-(id)adjFbAttributionId;
-(id)adjIdForAdvertisers;
-(BOOL)adjTrackingEnabled;
@end

@interface XXUnknownSuperclass (ADJAdditions)
+(BOOL)adjIsEqual:(id)equal toString:(id)string;
+(id)adjJoin:(id)join;
-(id)adjRemoveColons;
-(id)adjUrlEncode;
-(id)adjSha1;
-(id)adjMd5;
-(id)adjTrim;
@end

@interface XXUnknownSuperclass (MATURLEncoding)
-(id)urlEncodeUsingEncoding:(unsigned)encoding;
@end

@interface XXUnknownSuperclass (MATGTMNSStringXMLAdditions)
-(id)MATgtm_stringBySanitizingToXMLSpec;
-(id)MATgtm_stringBySanitizingAndEscapingForXML;
@end

@interface XXUnknownSuperclass (MATURLEncoding)
-(id)urlEncodeUsingEncoding:(unsigned)encoding;
@end

@interface XXUnknownSuperclass (MATGTMNSStringXMLAdditions)
-(id)MATgtm_stringBySanitizingToXMLSpec;
-(id)MATgtm_stringBySanitizingAndEscapingForXML;
@end

@interface XXUnknownSuperclass (MATURLEncoding)
-(id)urlEncodeUsingEncoding:(unsigned)encoding;
@end

@interface XXUnknownSuperclass (MATGTMNSStringXMLAdditions)
-(id)MATgtm_stringBySanitizingToXMLSpec;
-(id)MATgtm_stringBySanitizingAndEscapingForXML;
@end

@interface XXUnknownSuperclass (URLEncoding)
+(id)urlEncodeValue:(id)value;
-(id)urlEncode;
@end

@interface XXUnknownSuperclass (Checksum)
-(id)checksum;
@end

@interface XXUnknownSuperclass (TimeSpanValue)
-(id)timeSpanValue;
@end

@interface XXUnknownSuperclass (WeakTimerManagement)
-(void)rescheduleTimers:(id)timers;
-(void)scheduleBlock:(id)block atDate:(id)date;
-(id)managedWeakTimers;
-(void)setManagedWeakTimers:(id)timers;
@end

@interface XXUnknownSuperclass (Rotation)
-(CGRect)applicationFrameConsideringRotation;
@end

@interface XXUnknownSuperclass (BundleImage)
+(id)imageNamed:(id)named bundle:(id)bundle;
@end

@interface XXUnknownSuperclass (JSONValue)
-(id)jsonValue;
@end

@interface XXUnknownSuperclass (Validation)
-(BOOL)isValidEmailWithError:(id*)error;
-(BOOL)isValidEmail;
-(BOOL)isValidUsernameChange:(NSRange)change replacementString:(id)string;
-(BOOL)isValidUsernameWithError:(id*)error;
-(BOOL)isValidUsername;
-(BOOL)isValidPasswordWithError:(id*)error;
-(BOOL)isValidPassword;
@end

@interface XXUnknownSuperclass (QueryString)
-(id)queryString;
@end

@interface XXUnknownSuperclass (ImageNamedForDevice)
+(id)imageNamedForDevice:(id)device;
@end

@interface XXUnknownSuperclass (ConvertToImage)
+(id)imageWithColor:(id)color;
-(id)image;
@end

@interface XXUnknownSuperclass (ShouldExecute)
+(void)executed;
+(BOOL)shouldExecute:(double)execute;
+(BOOL)shouldExecute:(double)execute withParameter:(id)parameter;
+(BOOL)_shouldExecute:(double)execute forKey:(id)key;
@end

@interface XXUnknownSuperclass (DateValue)
-(id)dateValue;
@end

@interface XXUnknownSuperclass (AbbreviatedStringValue)
-(id)abbreviatedStringValue;
@end

@interface XXUnknownSuperclass (ImageEffects)
-(id)applyBlurWithRadius:(float)radius tintColor:(id)color saturationDeltaFactor:(float)factor maskImage:(id)image;
-(id)applyTintEffectWithColor:(id)color;
-(id)applyDarkEffect;
-(id)applyExtraLightEffect;
-(id)applyLightEffect;
@end

@interface XXUnknownSuperclass (IsRetina)
-(BOOL)isRetina;
@end

@interface XXUnknownSuperclass (Comprehensions)
-(id)mappedArrayUsingBlock:(id)block;
-(id)mappedDictionaryUsingBlock:(id)block;
@end

@interface XXUnknownSuperclass (Filter)
-(id)filteredDictionaryUsingBlock:(id)block;
@end

@interface XXUnknownSuperclass (Tuple)
+(id)dictionaryWithTuples:(id)tuples;
-(id)tuples;
-(id)initWithTuples:(id)tuples;
@end

@interface XXUnknownSuperclass (Tuple)
-(void)addTuple:(id)tuple;
@end

@interface XXUnknownSuperclass (Map)
-(id)map:(id)map onQueue:(id)queue;
-(id)mappedArrayUsingBlock:(id)block;
@end

@interface XXUnknownSuperclass (MapAndJoin)
-(id)mapAndJoin:(id)join onQueue:(id)queue;
-(id)mappedAndJoinedArrayUsingBlock:(id)block;
@end

@interface XXUnknownSuperclass (Filter)
-(id)filter:(id)filter onQueue:(id)queue;
-(id)filteredArrayUsingBlock:(id)block;
@end

@interface XXUnknownSuperclass (FilterFirstObject)
-(id)firstObjectMatchingFilter:(id)filter onQueue:(id)queue;
-(id)firstObjectMatchingFilter:(id)filter;
@end

@interface XXUnknownSuperclass (Archive)
@end

@interface XXUnknownSuperclass (ColorOverlay)
-(id)imageWithColor:(id)color;
@end

@interface XXUnknownSuperclass (CurrencyName)
+(id)currencyNamePlural;
+(id)currencyNameSingular;
+(id)currencyNameWithAmount:(int)amount;
@end

@interface XXUnknownSuperclass (EqualTo)
-(BOOL)isEqualToObject:(id)object;
@end

@interface XXUnknownSuperclass (WebCache)
-(void)cancelCurrentImageLoad;
-(void)sd_setImageWithURL:(id)url placeholderImage:(id)image options:(unsigned)options completed:(id)completed;
-(void)sd_setImageWithURL:(id)url placeholderImage:(id)image completed:(id)completed;
-(void)sd_setImageWithURL:(id)url completed:(id)completed;
-(void)sd_setImageWithURL:(id)url placeholderImage:(id)image options:(unsigned)options;
-(void)sd_setImageWithURL:(id)url placeholderImage:(id)image;
-(void)sd_setImageWithURL:(id)url;
-(id)imageURL;
@end

@interface XXUnknownSuperclass (WebCacheDeprecated)
-(void)setImageWithURL:(id)url placeholderImage:(id)image options:(unsigned)options completed:(id)completed;
-(void)setImageWithURL:(id)url placeholderImage:(id)image completed:(id)completed;
-(void)setImageWithURL:(id)url completed:(id)completed;
-(void)setImageWithURL:(id)url placeholderImage:(id)image options:(unsigned)options;
-(void)setImageWithURL:(id)url placeholderImage:(id)image;
-(void)setImageWithURL:(id)url;
@end

@interface XXUnknownSuperclass (RotateToOrientation)
-(void)rotateToOrientation;
@end

@interface XXUnknownSuperclass (DeviceURL)
-(id)deviceURL;
@end

@interface XXUnknownSuperclass (GIF)
+(id)sd_animatedGIFNamed:(id)named;
+(float)frameDurationAtIndex:(unsigned)index source:(CGImageSourceRef)source;
+(id)sd_animatedGIFWithData:(id)data;
-(id)sd_animatedImageByScalingAndCroppingToSize:(CGSize)size;
@end

@interface XXUnknownSuperclass (CompletionHandler) <UIAlertViewDelegate>
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) id promptValidation;
@property(copy, nonatomic) id completionHandler;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)showPromptWithValidation:(id)validation completion:(id)completion;
@end

@interface XXUnknownSuperclass (Platform)
-(id)friendlyPlatform;
@end

@interface XXUnknownSuperclass (Extensions)
@property(assign, nonatomic) WBType type;
@property(retain, nonatomic) NSString* propertyName;
@property(assign, nonatomic) SEL alternateSelector;
@property(assign, nonatomic) int selectorInferredType;
@end

@interface XXUnknownSuperclass (NSData_MessagePack)
-(id)messagePackParse;
@end

@interface XXUnknownSuperclass (NumberValue)
-(id)numberValue;
@end

@interface XXUnknownSuperclass (Contains)
-(BOOL)contains:(id)contains;
@end

@interface XXUnknownSuperclass (Response)
@property(retain, nonatomic) NSDictionary* responseHeaders;
@property(assign, nonatomic) int statusCode;
@end

@interface XXUnknownSuperclass (Sha1)
-(id)sha1;
@end

@interface XXUnknownSuperclass (MultiFormat)
+(int)sd_exifOrientationToiOSOrientation:(int)orientation;
+(int)sd_imageOrientationFromImageData:(id)imageData;
+(id)sd_imageWithData:(id)data;
@end

@interface XXUnknownSuperclass (WebCache)
-(id)imageURLStorage;
-(void)cancelCurrentImageLoad;
-(void)sd_setBackgroundImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image options:(unsigned)options completed:(id)completed;
-(void)sd_setBackgroundImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image completed:(id)completed;
-(void)sd_setBackgroundImageWithURL:(id)url forState:(unsigned)state completed:(id)completed;
-(void)sd_setBackgroundImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image options:(unsigned)options;
-(void)sd_setBackgroundImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image;
-(void)sd_setBackgroundImageWithURL:(id)url forState:(unsigned)state;
-(void)sd_setImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image options:(unsigned)options completed:(id)completed;
-(void)sd_setImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image completed:(id)completed;
-(void)sd_setImageWithURL:(id)url forState:(unsigned)state completed:(id)completed;
-(void)sd_setImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image options:(unsigned)options;
-(void)sd_setImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image;
-(void)sd_setImageWithURL:(id)url forState:(unsigned)state;
-(id)imageURLForState:(unsigned)state;
-(id)currentImageURL;
@end

@interface XXUnknownSuperclass (WebCacheDeprecated)
-(void)setBackgroundImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image options:(unsigned)options completed:(id)completed;
-(void)setBackgroundImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image completed:(id)completed;
-(void)setBackgroundImageWithURL:(id)url forState:(unsigned)state completed:(id)completed;
-(void)setBackgroundImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image options:(unsigned)options;
-(void)setBackgroundImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image;
-(void)setBackgroundImageWithURL:(id)url forState:(unsigned)state;
-(void)setImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image options:(unsigned)options completed:(id)completed;
-(void)setImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image completed:(id)completed;
-(void)setImageWithURL:(id)url forState:(unsigned)state completed:(id)completed;
-(void)setImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image options:(unsigned)options;
-(void)setImageWithURL:(id)url forState:(unsigned)state placeholderImage:(id)image;
-(void)setImageWithURL:(id)url forState:(unsigned)state;
@end

@interface XXUnknownSuperclass (ChildViewController)
-(void)properlyRemoveChildViewController:(id)controller;
-(void)properlyAddChildViewController:(id)controller belowView:(id)view;
-(void)properlyAddChildViewController:(id)controller aboveView:(id)view;
-(void)properlyAddChildViewController:(id)controller toView:(id)view;
-(void)properlyAddChildViewController:(id)controller;
@end

@interface XXUnknownSuperclass (ExtendedOperations)
-(id)popObjectForKey:(id)key;
-(void)replaceKey:(id)key withKey:(id)key2;
@end

@interface XXUnknownSuperclass (ApplyAttributes)
-(void)applyAttributes:(id)attributes;
@end

@interface XXUnknownSuperclass (CommaDelimited)
-(id)commaDelimitedValue;
@end

@interface XXUnknownSuperclass (Snapshot)
-(id)snapshotImageAfterScreenUpdates:(BOOL)updates;
-(id)snapshotImage;
@end

@interface XXUnknownSuperclass (CompletionHandler) <UIActionSheetDelegate>
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) id completionHandler;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
@end

@interface XXUnknownSuperclass (Object)
+(id)objectsWithDictionaries:(id)dictionaries serverCase:(int)aCase;
+(id)objectsWithDictionaries:(id)dictionaries;
+(id)objectWithDictionary:(id)dictionary serverCase:(int)aCase;
+(id)objectWithDictionary:(id)dictionary;
+(id)object;
-(id)jsonSafeValue;
-(id)dictionaryWithObjectAndServerCase:(int)objectAndServerCase;
-(id)dictionaryWithObject;
@end

@interface XXUnknownSuperclass (WBError)
+(id)errorWithCode:(int)code;
+(id)errorWithRequestStatus:(int)requestStatus httpStatusCode:(int)code;
+(id)errorWithRequestStatus:(int)requestStatus errorCode:(int)code;
+(id)errorWithRequestStatus:(int)requestStatus errorCode:(int)code context:(id)context recoveryAttempter:(id)attempter;
+(id)errorWithTitle:(id)title description:(id)description errorCode:(int)code;
+(id)errorWithRequestStatus:(int)requestStatus errorCode:(int)code httpStatusCode:(int)code3 context:(id)context recoveryAttempter:(id)attempter;
-(void)setHttpStatusCode:(int)code;
-(int)httpStatusCode;
-(id)localizedShortDescription;
@end

@interface XXUnknownSuperclass (WBParsing)
+(id)dataWithWBObject:(id)wbobject;
+(id)wbObjectWithData:(id)data;
+(id)wbObjectWithData:(id)data wbSubclass:(Class)subclass;
@end

@interface XXUnknownSuperclass (WBParsing)
-(id)wbObjectFromJSONString;
@end

@interface XXUnknownSuperclass (WBParsing)
-(id)JSONString;
-(id)JSONData;
@end

@interface XXUnknownSuperclass (WBParsing)
-(id)JSONString;
-(id)JSONData;
@end

@interface XXUnknownSuperclass (WebCache)
-(void)cancelCurrentArrayLoad;
-(void)cancelCurrentImageLoad;
-(void)setAnimationImagesWithURLs:(id)urls;
-(id)imageURL;
-(void)sd_setImageWithURL:(id)url placeholderImage:(id)image options:(unsigned)options progress:(id)progress completed:(id)completed;
-(void)sd_setImageWithURL:(id)url placeholderImage:(id)image options:(unsigned)options completed:(id)completed;
-(void)sd_setImageWithURL:(id)url placeholderImage:(id)image completed:(id)completed;
-(void)sd_setImageWithURL:(id)url completed:(id)completed;
-(void)sd_setImageWithURL:(id)url placeholderImage:(id)image options:(unsigned)options;
-(void)sd_setImageWithURL:(id)url placeholderImage:(id)image;
-(void)sd_setImageWithURL:(id)url;
@end

@interface XXUnknownSuperclass (WebCacheDeprecated)
-(void)setImageWithURL:(id)url placeholderImage:(id)image options:(unsigned)options progress:(id)progress completed:(id)completed;
-(void)setImageWithURL:(id)url placeholderImage:(id)image options:(unsigned)options completed:(id)completed;
-(void)setImageWithURL:(id)url placeholderImage:(id)image completed:(id)completed;
-(void)setImageWithURL:(id)url completed:(id)completed;
-(void)setImageWithURL:(id)url placeholderImage:(id)image options:(unsigned)options;
-(void)setImageWithURL:(id)url placeholderImage:(id)image;
-(void)setImageWithURL:(id)url;
@end

@interface XXUnknownSuperclass (TimeFunctions)
-(BOOL)isRoughlyEqualToDate:(id)date;
-(id)formattedTimeSince;
-(double)timeSince;
-(id)timeLeft;
-(id)formattedTimeUntilWithGranularity:(int)granularity;
-(id)formattedTimeUntil;
-(double)timeUntil;
-(BOOL)hasElapsed;
@end

@interface XXUnknownSuperclass (Checksum)
-(id)checksum;
@end

@interface XXUnknownSuperclass (ScreenSize)
-(BOOL)shouldEnableRetina;
-(BOOL)tallScreen;
@end

@interface XXUnknownSuperclass (HighlightAnimation)
-(BOOL)isShowingHighlightAnimation;
-(void)stopHighlightAnimation;
-(void)startHighlightAnimation;
-(void)highlightAnimationWithRepeatCount:(float)repeatCount completionHandler:(id)handler;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)animationDidStart:(id)animation;
-(void)_startHighlightAnimationWithRepeatCount:(float)repeatCount completionHandler:(id)handler;
-(id)completionHandler;
-(void)setCompletionHandler:(id)handler;
@end

@interface XXUnknownSuperclass (ViewPositioning)
-(void)applyFrameModeHorizontal:(unsigned)horizontal;
-(void)applyFrameModeVertical:(unsigned)vertical;
-(void)setResizeModeForWidth:(unsigned)width height:(unsigned)height topMargin:(unsigned)margin rightMargin:(unsigned)margin4 bottomMargin:(unsigned)margin5 leftMargin:(unsigned)margin6;
-(void)setResizeModeForWidth:(unsigned)width height:(unsigned)height verticalMargins:(unsigned)margins horizontalMargins:(unsigned)margins4;
-(void)setResizeModeForWidth:(unsigned)width height:(unsigned)height allMargins:(unsigned)margins;
-(void)setResizeModeForVerticalMargins:(unsigned)verticalMargins horizontalMargins:(unsigned)margins;
-(void)setResizeModeForAllMargins:(unsigned)allMargins;
-(void)setResizeModeForHorizontalMargins:(unsigned)horizontalMargins;
-(void)setResizeModeForVerticalMargins:(unsigned)verticalMargins;
-(void)setResizeModeForTopMargin:(unsigned)topMargin rightMargin:(unsigned)margin bottomMargin:(unsigned)margin3 leftMargin:(unsigned)margin4;
-(void)setResizeModeForWidth:(unsigned)width height:(unsigned)height;
-(void)setResizeModeForLeftMargin:(unsigned)leftMargin;
-(void)setResizeModeForBottomMargin:(unsigned)bottomMargin;
-(void)setResizeModeForRightMargin:(unsigned)rightMargin;
-(void)setResizeModeForTopMargin:(unsigned)topMargin;
-(void)setResizeModeForHeight:(unsigned)height;
-(void)setResizeModeForWidth:(unsigned)width;
-(void)_setResizeMaskBit:(unsigned)bit toMode:(unsigned)mode;
-(void)changeSizeBySize:(CGSize)size;
-(void)moveOriginByOffset:(CGPoint)offset;
-(void)bottomAlignWithView:(id)view;
-(void)rightAlignWithView:(id)view;
-(void)leftAlignWithView:(id)view;
-(void)topAlignWithView:(id)view;
-(void)bottomAlignInSuperviewWithMargin:(float)margin;
-(void)rightAlignInSuperviewWithMargin:(float)margin;
-(void)leftAlignInSuperviewWithMargin:(float)margin;
-(void)topAlignInSuperviewWithMargin:(float)margin;
-(void)setSize:(CGSize)size;
-(void)setOrigin:(CGPoint)origin;
-(void)setY:(float)y;
-(void)setX:(float)x;
-(CGSize)size;
-(CGPoint)origin;
-(void)centerVerticallyInSuperview;
-(void)centerHorizontallyInSuperview;
@end

@interface XXUnknownSuperclass (ExtendedAttributes)
-(BOOL)getExtendedAttributeValue:(out id*)value forKey:(id)key;
-(BOOL)setExtendedAttributeValue:(id)value forKey:(id)key;
-(BOOL)removeExtendedAttributeForKey:(id)key;
@end

@interface XXUnknownSuperclass (Path)
-(id)downloadPath;
-(id)cachePath;
-(id)path;
@end

@interface XXUnknownSuperclass (ResizeFontToFit)
-(void)resizeFontToFit;
-(void)resizeFontToFit:(int)fit minSize:(int)size;
@end

@interface XXUnknownSuperclass (ImageContentType)
+(id)contentTypeForImageData:(id)imageData;
@end

@interface XXUnknownSuperclass (NSDictionary_MessagePack)
-(id)messagePack;
@end

@interface XXUnknownSuperclass (Unarchive)
@end

@interface XXUnknownSuperclass (NSArray_MessagePack)
-(id)messagePack;
@end

@interface XXUnknownSuperclass (ForceDecode)
+(id)decodedImageWithImage:(id)image;
@end

@interface XXUnknownSuperclass (FBError)
@property(readonly, assign) BOOL fberrorIsTransient;
@property(readonly, copy) NSString* fberrorUserTitle;
@property(readonly, copy) NSString* fberrorUserMessage;
@property(readonly, assign) BOOL fberrorShouldNotifyUser;
@property(readonly, assign) int fberrorCategory;
@end

